eclipse-platform/eclipse.platform.swt

bundles/org.eclipse.swt/buildSWT.xml
- Updating buildSWT.xml gitroot path to point to github
Change-Id: I76ba4dc06a8822a2dbc20acf5fe4bdee43de739a
=> Moving SWT to github

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Button.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Button.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Button.java
Javadoc in Button#setImage still references to other platforms in addition to GTK, Win32 and MacOS
Fixes #7
=> Javadoc in Button#setImage still references to other platforms

bundles/org.eclipse.swt/Eclipse SWT Drag and Drop/gtk/org/eclipse/swt/dnd/TreeTableCommon.java
Continuation from https://git.eclipse.org/r/c/platform/eclipse.platform.swt/+/192265
=> Bug 577878 - [GTK] Limit Table/Tree drag image to contol's width

bundles/org.eclipse.swt/pom.xml
Improper Handling of Length Parameter Inconsistency in Apache Ant
When reading a specially crafted TAR archive an Apache Ant build can be made to allocate large amounts of memory that finally leads to an out of memory error, even for small inputs. This can be used to disrupt builds using Apache Ant. Apache Ant prior to 1.9.16 and 1.10.11 were affected.
=>  Dependabot security alert: Ant

bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Widget.java
When a window lost focus, gtk_focus_out_event was not being called in GTK4.
=> Bug 579299 - [GTK4]  Call gtk_focus_out_event when window loses focus

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/GC.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_graphics_GC.java
Fixes a regression introduced with commit 22797d3f9f09ca67bfd29c864f2aaf8eb452c75c that was reported in [Bug 493455 (comment 51)](https://bugs.eclipse.org/bugs/show_bug.cgi?id=493455#c51).
=> Bug 493455 - [win32] fix: source position ignored when drawing transparent image

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java, tests/org.eclipse.swt.tests/ManualTests/org/eclipse/swt/tests/manual/Issue0021_HdcLeak_ImageCreateGdipImage.java
Signed-off-by: Alexandr Miloslavskiy <alexandr.miloslavskiy@syntevo.com>
=> #21 [win32] HDC leak in Image.createGdipImage()

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Button.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_Button.java
Signed-off-by: Rolf Theunissen <rolf.theunissen@gmail.com>
=> #6 [win32] Keyboard shortcuts for radio buttons don't work anymore

bundles/org.eclipse.swt/Eclipse SWT PI/win32/library/os.c, bundles/org.eclipse.swt/Eclipse SWT PI/win32/library/os_stats.c, bundles/org.eclipse.swt/Eclipse SWT PI/win32/library/os_stats.h, bundles/org.eclipse.swt/Eclipse SWT PI/win32/org/eclipse/swt/internal/win32/OS.java, bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/ToolBar.java, bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/ToolItem.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/ToolBar.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/ToolItem.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/ToolBar.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/ToolItem.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Widget.java, bundles/org.eclipse.swt/META-INF/MANIFEST.MF, bundles/org.eclipse.swt/build.xml, bundles/org.eclipse.swt/pom.xml, examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet153.java, tests/org.eclipse.swt.tests/META-INF/MANIFEST.MF
This patch adds new API for recoloring ToolItems. SWT version is bumped to 3.120.0.
Recolored toolbar buttons look decent, but there is some space for discussion. In particular, GTK drop-down buttons are made of two parts (the main button and the arrow button) and the patch recolors them individually. Also, separators ignore color properties, but in theory it's possible for them to respect foreground color.
Snippet153 has been extended for testing this patch. I've tested it on the latest stable versions of macOS, Windows and GNOME (GTK 3.24).
=> Bug 579470 - Add ToolItem background and foreground color properties

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_graphics_GC.java
https://github.com/eclipse-platform/eclipse.platform.swt/issues/30
Test fails due to
https://github.com/eclipse-platform/eclipse.platform.swt/issues/40.
Disable the failing test on Mac.
=> test_bug493455_drawImageAlpha_srcPos fails on both MAC platforms

bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Control.java
Previously, when the dialog was closed in Snippet 50, an swt_fixed_remove assertion error was logged in the console (issue #49). With this patch that no longer happens. 
- added a call to gtk_window_destroy which happens only if GTK_IS_WINDOW is true.
Tested using Snippet 50.
=> [GTK4] Call gtk_window_destroy if widget to be destroyed is a GtkWindow

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/internal/BidiUtil.java
- BidiUtil#resolveTextDirection() to avoid re-probing for LRT
eclipse-platform#44
=> Part2: Mixed RTL text(with LTR) is not rendered correctly in StyledText

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/graphics/Device.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/graphics/Device.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Device.java
Device.isDisposed() is called much more frequently then dispose() and
should not be costly synchronized. The isDisposed() check in dispose()
is still synchronized so that still there will be no double dispose().
=> Avoid synchronized in Device.isDisposed #74

bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/widgets/Synchronizer.java
When messages have been enqueued for async execution there is no thread
waiting anyway.
=> Synchronizer does not need to notify if nobody is waiting #81

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/performance/BenchmarkSwtMultithreading.java
To show the impact of many messages to
org.eclipse.swt.widgets.Synchronizer.addLast ()
org.eclipse.swt.graphics.Device.isDisposed ()
org.eclipse.swt.widgets.Synchronizer.asyncExec ()
org.eclipse.swt.widgets.Display.findDisplay ()
=> Added BenchmarkSwtMultithreading #74

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Display.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/widgets/Synchronizer.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Display.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Display.java
Synchronizer.messages grew with constant size leading to O(n^2)
performance for n messages.
Also the costly "synchronized" can be avoided by using
java.util.concurrent DataStructures.
The message queue size (which is not O(1) for java.util.concurrent) is
not needed since only checks for isEmpty() are used.
=> Use java.util.concurrent for Synchronizer.messages #74

bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/widgets/Synchronizer.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_Display.java
Insert at the beginning of the queue for backward compatibility
see https://github.com/eclipse-platform/eclipse.platform.swt/pull/77#pullrequestreview-958834521
@mickaelistria
=> fix org.eclipse.swt.widgets.Synchronizer.moveAllEventsTo(Synchronizer)

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Display.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Display.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Display.java
There is only 1 display - no need to search in an array of 4 displays
during Display.findDisplay()
It's a minor optimization for Display.findDisplay (). The greatest
bottle neck is still the "synchronized" statement.
=> make Display.Displays size 1 by default #74

bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/widgets/Synchronizer.java
This reverts commit 1a57687d2eae3329f77fe40487ddc7700ccccb9e.
Reason for revert: this patch breaks Eclipse test execution in IDE.
After the test that starts IDE is done, IDE is not shut down anymore.
=> Revert "Synchronizer does not need to notify if nobody is waiting #81

bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/layout/BorderLayout.java, examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet379.java
Fix https://github.com/eclipse-platform/eclipse.platform.swt/issues/32
FYI @joel-majano
=> NullPointerException in BorderLayout when Layout Data is null

tests/org.eclipse.swt.tests.win32/JUnit Tests/org/eclipse/swt/tests/win32/AllWin32Tests.java, tests/org.eclipse.swt.tests.win32/JUnit Tests/org/eclipse/swt/widgets/Test_org_eclipse_swt_widgets_Display.java, tests/org.eclipse.swt.tests.win32/META-INF/MANIFEST.MF, tests/org.eclipse.swt.tests.win32/pom.xml
eclipse-platform#98
Change-Id: Id36bd8491165e645334cddba3fb6b30fc745ea8e
=> Windows Compile fails due to missing Display#isXMouseActive

bundles/org.eclipse.swt/Eclipse SWT Drag and Drop/gtk/org/eclipse/swt/dnd/Clipboard.java, bundles/org.eclipse.swt/Eclipse SWT Drag and Drop/gtk/org/eclipse/swt/dnd/ClipboardProxy.java, bundles/org.eclipse.swt/Eclipse SWT Drag and Drop/gtk/org/eclipse/swt/dnd/RTFTransfer.java, bundles/org.eclipse.swt/Eclipse SWT Drag and Drop/gtk/org/eclipse/swt/dnd/TextTransfer.java, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/gtk4.c, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/gtk4_stats.c, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/gtk4_stats.h, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/org/eclipse/swt/internal/gtk/OS.java, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/org/eclipse/swt/internal/gtk4/GTK4.java
- added handling for Rich text (RTF)
- Fixed errors logged to console if trying to paste with empty clipboard
- made sure registerType is not called in TextTransfer
I discussed other ways of doing RTF with the GTK devs through IRC. There were a few suggestions that did not work, and their suggestion was to use the gdk_clipboard_read function. Since this function is async, it adds another level of complexity that did not exist with the wait_for_contents function in GTK3. The solution implemented was the most reasonable one, and maintains similar functionality.
=> RTFTransfer fix, small fixes for empty clipboard and TextTransfer IDs

bundles/org.eclipse.swt/Eclipse SWT Drag and Drop/gtk/org/eclipse/swt/dnd/ImageTransfer.java
- Change value of transferData.format from 32 to 16
- See #146
=> Fix Clipboard ImageTransfer not working on Linux x86_64

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/AllBrowserTests.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_browser_Browser.java
- use TracingSuite to dump after hanging for 60 seconds
- make sure all tests run in same (sorted) order on all systems/JVM's
- print system properties and environment at startup
- print memory use after each test
See https://github.com/eclipse-platform/eclipse.platform.swt/issues/108
=> Add more debug info for AllBrowserTests (#108)

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_browser_Browser.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_Composite.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_Control.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_Widget.java
- drain SWT event queue after every test
This fixes growing number of opened file descriptors (GTK events not
processed so browser processes created by test wait for the GTK events
and don't release allocated resources).
- added started threads count info
- added opened file descriptors info on Linux
- added system limits dump on Linux
- dispose all shells / browsers created by test
- dispose shell leaking in test_setVisibility_and_sizing
- assert that all shells and browsers are disposed
See https://github.com/eclipse-platform/eclipse.platform.swt/issues/108
=> AllBrowserTests running out of file descriptors on Linux (Fixes #108)

bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/layout/BorderData.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/layout/BorderLayout.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_layout_BorderLayout.java
If components has not an intrinsic preferred size but can adapt to the
available space e.g. with wrapping, calling just their preferred size
without restrictions gives false results e.g. for the height.
Fix https://github.com/eclipse-platform/eclipse.platform.swt/issues/163
I know its late in the release, but still like to ask to get PMC approval to include this bugfix as it is very local and there is a unit test covering this area of code.
=> BorderLayout must pass the maximum width to control computation.

bundles/org.eclipse.swt/Eclipse SWT PI/gtk/org/eclipse/swt/internal/gtk/GTK.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Display.java
Only symbolic images are "guaranteed" to be available and actually
available in adwaita-icon-theme 42.0. Thus request symbolic images but
pass the flag to prefer the colorfull images if available.
Fixes #173 .
=> Request symbolic images on GTK but prefer colorful

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_browser_Browser.java, tests/org.eclipse.swt.tests/META-INF/MANIFEST.MF, tests/org.eclipse.swt.tests/pom.xml
It's same engine as on Cocoa (Webkit) and event size is just ignored.
Fixes long standing test failure on Linux.
=> Ignore test_VisibilityWindowListener_eventSize size check on WebKitGTK

Jenkinsfile, container/Dockerfile
Building and testing on Fedora 30 doesn't provide good enough
information as this version is EOLed long ago.
=> Switch to Fedora 36 swtbuild image

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_browser_Browser.java
It's same backend (Webkit) as MacOS and behaves in the same way.
=> Don't check LocationListener changing js eval on WebkitGTK

.github/workflows/rebase.yml
This allows the use of "/rebase" in a comment within a PR to rebase the changes. 
Right now, you need to rebase locally then push to GitHub to rebase, which can be tedious for old PRs. Having this feature will make it much easier to rebase those not so recent changes.
Tycho already does this, see here:
https://github.com/eclipse/tycho/blob/master/.github/workflows/rebase.yml
=> Create rebase.yml file for rebasing through GitHub PR page

bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Shell.java
Continues fixes for https://bugs.eclipse.org/bugs/show_bug.cgi?id=567333
- guarded call to gtk_window_set_keep_above as API not available in GTK4
- removed modification to allocation.height in forceResize as it was causing wrong behaviour when displaying contents
- Solved gtk size allocation errors by taking into account the "y" position of the widget (gtk appears to be subtracting it from the height requested)
- guarded calls to gtk3 only functions as gtk4 snippets appear to work fine without it (will be monitoring this fix to make sure it didnt break something else)
Tested with Snippet 50, 63, 295, 233, 104, 99, 248, 4
=> [GTK4] Various Shell fixes to allow more snippets to work

bundles/org.eclipse.swt/Eclipse SWT Drag and Drop/gtk/org/eclipse/swt/dnd/Clipboard.java, bundles/org.eclipse.swt/Eclipse SWT Drag and Drop/gtk/org/eclipse/swt/dnd/ClipboardProxy.java, bundles/org.eclipse.swt/Eclipse SWT Drag and Drop/gtk/org/eclipse/swt/dnd/ImageTransfer.java, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/gtk4.c, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/gtk4_stats.c, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/gtk4_stats.h, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/os.c, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/os_stats.c, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/os_stats.h, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/org/eclipse/swt/internal/gtk/OS.java, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/org/eclipse/swt/internal/gtk4/GTK4.java
Part of the fixes required for https://bugs.eclipse.org/bugs/show_bug.cgi?id=574949
- Added some required functions to OS.java and GTK4.java
- Added handling of images (pixbufs) to Clipboard.java/ClipboardProxy.java
- Restored functionality of getAvailableTypeNames
Tested with ClipboardExample.java from swt.examples. Only HTMLTransfer and FileTransfer remain to be fixed from ClipboardExample.
=> [GTK4] Clipboard Port: Fix for ImageTransfer and getAvailableTypeNames

pom.xml
This itself does not enable sonarcloud. But just in case someone would like to run sonarcloud on a fork: At least these parameters need to be added till a result can be obtained.
Example result see:
https://sonarcloud.io/summary/overall?id=jukzi_eclipse.platform.swt
=> Add minimal sonarcloud parameters to pom.xml

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Table.java
- Ignored visibility for empty table issue mentioned in https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/127#issuecomment-1170257023
- fixes #223 
Change-Id: If2da1df46b4b6328c537ce34585c585e86136452
=> Part3 - Table remains visible though setVisible(false) was called

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Table.java
- Fix Eclipse code completion popup which is currently empty unless
re-triggered.
Change-Id: I2c985d221d2d8048e5ad63a184145bff63906b7c
=> Part4: Table remains visible though setVisible(false) was called

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_graphics_TextLayout.java
Test has been adapted based on Mac behavior
=> Fix failing test case on Mac - TextLayout.test_getLineOffsets()

examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet282.java
This snippet currently does not provide any visual cue to let the user know that the image was pasted correctly.
For the user, it looks like the image did not change at all if the snippet works correctly.
With this patch, a simple console message is printed when an image is succesfully copied, or when it fails.
=> [GTK4] Snippet 282 needs clarity improvements

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_graphics_ImageData.java
Use assertThrows and other smaller assertion improvements.
Prep work before investigating test failure as reported in
https://github.com/eclipse-platform/eclipse.platform.swt/issues/232
=> Improve assertions in ImageData tests

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_graphics_TextLayout.java
Should reduce failing tests on Jenkins build.
=> Make sure to dispose TextLayout on test failure.

tests/org.eclipse.swt.tests/META-INF/MANIFEST.MF
This reverts commit 0b0d8663f993aece50455a1737dd17d5991de836.
Fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/267
=> Revert "Make SWT tests fragment."

bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/ToolBar.java
Missing semicolon caused Gtk to spit out many css parsing errors. Adding this semicolon fixes the issue.
=> [GTK4] Flood of CSS parsing errors when launching IDE

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/graphics/ImageDataTestHelper.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_graphics_ImageData.java
Move ImageDataTestHelper to it's own package to prevent split package
with swt bundle and thus signing issue. In order for that to work
switched to using reflection to call non-public ImageData methods in the
tests.
Fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/232
=> Fix ImageData tests

bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/FileDialog.java
+if no filename set defaults to location of file
The issue was caused by if no filename was set then it would try to open file "" as a default which creates an error. This is simply fixed by if no filename is set then set the filename to location of the file
Signed-off-by: Jason Wang <jaswan@redhat.com>
Original Issue #48
=> Issue #48 FileDialog created displays error if no fileFilter Path set

docs/gtk-dev-guide.md
The SWT GTK dev guide hosted here: https://wiki.eclipse.org/SWT/Devel/Gtk/Dev_guide was outdated and had to be updated. Porting it over to the repo makes this easier to access all SWT related information.
+ Converted dev guide to Markdown
+ Converted some diagrams to mermaid syntax
+ Updated references to gtk versions
Currently this markdown file contains direct links to images hosted on the Eclipse wiki, so these will have to be added to a folder in /docs.
=> Add SWT gtk dev guide as a markdown file

.github/aggregator.pom, .github/workflows/maven.yml
Currently the fragments are not build but taken from the I-Build in the
Gh actions, this fixes the problem by checkout and build the binary
repository as well.
Fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/251
=> GH: Build the swt fragments together with the rest of the build

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Display.java, bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Shell.java
It was caused by undocumented setting used to prevent Bug 578171.
This patch changes the workaround to a different one, where instead
of trying to make menu behave, it's now canceled just before showing
Shell.
Fixes #256
=> Issue #256 - [cocoa] Menus does not show on macOS 13 Ventura

bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Control.java, tests/org.eclipse.swt.tests/ManualTests/org/eclipse/swt/tests/manual/Issue0247_WaylandDragDropGetsStuck.java
Fixes #247
The problem was introduced in patch for Bug 541635, which accidentally
ignored calculated `dragging` variable, causing drag to begin
immediately when mouse is moved.
Also, it introduced a crazy loop, which, if it proceeds to second
iteration, will loop forever, because GTK events can't be processed when
main thread is busy running the infinite loop. Luckily, it seems that
the loop always exited on first iteration, and its meaning was simply to
`return false` when mouse is not down.
The reason why drag&drop can become stuck is not exactly clear, but I'm
confident that it was related to very short drag&drop mouse move
threshold (basically, 1px). With the regular threshold, the bug may
still be present, but it's almost impossible to reproduce.
The real case behind this bug is that …
=> Issue #247 - [GTK][Wayland] Drag&drop gets stuck

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java
=> Issue #301 - wrong transparency when drawing image (regression from PR #224)

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_graphics_TextLayout.java
=> Test_org_eclipse_swt_graphics_TextLayout#test_getLineOffsets() JUnit failing on Windows.

bundles/org.eclipse.swt/Eclipse SWT PI/gtk/org/eclipse/swt/internal/gtk/swt_theming_fixes_gtk_3_24_5.css
This was caused by a fix for
https://bugs.eclipse.org/bugs/show_bug.cgi?id=549117 which set the css
for buttons on latest Gtk versions to have different paddings for
top/bottom and left/right.
Changing it to be equal returns the proper round size of the close
button while preserving the fix in the mentioned.
=> Fix oval window close button on Gtk under Wayland

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Tree.java, tests/org.eclipse.swt.tests/ManualTests/org/eclipse/swt/tests/manual/Issue0287_Tree_indexOf_Negative.java
This patch solves two problems after `Tree.setItemCount()`
* Unexpected values of `Tree.indexOf()` - was caused by non-coherent
cached values in `Tree.lastIndexOf`, `Tree.hLastIndexOf`. This was an
oversight in Bug 575787 that optimized `Tree.setItemCount()`.
* `SWT.SetData` events were received with the same value in
`Event.index` - this was partially fixed years ago in Bug 206806,
but it overlooked the case of items that are direct descendants of
Tree root. It didn't matter much until `Tree.setItemCount()` was
optimized in Bug 575787, which changed how items are inserted.
Signed-off-by: Alexandr Miloslavskiy <alexandr.miloslavskiy@syntevo.com>
=> Issue #287: [win32] Tree.setItemCount caused Tree.indexOf to return wrong values

examples/org.eclipse.swt.snippets/Snippets.md
- These snippets were removed in 18326ae5bb99e1bc2fe12f7d3b1b1b678c9b97b5
=> Remove non-existing Snippet links from Snippets markdown file

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Link.java
=> [a11y] - Content Types Preference description can't be read by JAWS

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Link.java
- Minor code refactoring: improves original fix done via #341
- This fix improves #340
=> [a11y] part2 - Content Types Preference description can't be read by JAWS

bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/graphics/Image.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/internal/ImageList.java
This issue was caused by logic running Cairo scaling multiple times when it was not necessary.
There are two locations that were problematic, one, Image.java was applying a second scale when copying an image.
Two, ImageList.java was interpreting width/height returned from a Cairo function incorrectly.
+ Guarded cairo_surface_set_device_scale call if copy and original have the same device zoom in Image.java
+ Corrected width and height variables to interpret size correctly in ImageList.java
Fixes #315
=> [GTK] Disabled toolbar icons and button images are double size on hi-res screen

bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/FileDialog.java
In GTK3 gtk_file_chooser_get_files returns a GSList* but in GTK4, it retruns a GListModel*.
The rest of the computeResultChooserDialog function assumes that we are dealing with a GSList which is incorrect.
The fix is to adapt to the correct calls when dealing with GListModel.
Tested with Eclipse IDE in GTK4 and Snippet72.
Tracked in #228, Fixes #343
=> [GTK4] FileDialog with SWT.MULTI causes crash

bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Control.java
When entering text using a keyboard in StyledText snippets or TextEditor example, text would not show up until the window was resized.
+ Added gtk_widget_queue_draw in update()
Tested with TextEditor.java and a simple StyledText snippet.
Tracked in #228
=> [GTK4] Text entered in StyledText does not show up until window resized

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Link.java
- Code refactoring improves fix for #340
=> [a11y] part3 - Content Types Preference description can't be read by JAWS

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Display.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Display.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Display.java
getLastEventTime() can be slow on windows and is not needed for UI
Freeze Monitoring
=> WIN: do not query OS lastEventTime for UI Freeze Monitoring #360

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_browser_Browser.java, tests/org.eclipse.swt.tests/META-INF/MANIFEST.MF, tests/org.eclipse.swt.tests/pom.xml
Wait for the events that have to appear first before checking that no extra events are received.
Fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/110
=> Fix Browser tests failing in I-build

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_custom_CCombo.java
Process events for 100ms or until combo gains focus. It's needed as focus event is not immediate and depends on machine speed, WS and etc.
=> Stabilize CCombo setFocus test on GH action

bundles/org.eclipse.swt/Eclipse SWT WebKit/gtk/library/webkitgtk.h
WebkitGtk gained compile time option to compile/link against libsoup2 or libsoup3, in order to differentiate between both there is no *.so version for WebkitGtk - libwebkit2gtk-4.1.so.0 . As WebkitGtk backend in SWT is fully dynamic, support for it is a matter of enhancing SWT's dlopen calls to try the new one too.
Details are available at
https://fedoraproject.org/wiki/Changes/libsoup_3:_Part_One .
Fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/379
=> Add support for WebkitGtk linked against libsoup-3.0.so

bundles/org.eclipse.swt/Eclipse SWT Browser/common/org/eclipse/swt/browser/Browser.java, bundles/org.eclipse.swt/Eclipse SWT Browser/gtk/org/eclipse/swt/browser/BrowserFactory.java, bundles/org.eclipse.swt/Eclipse SWT WebKit/gtk/library/webkitgtk.h, bundles/org.eclipse.swt/Eclipse SWT WebKit/gtk/org/eclipse/swt/browser/WebKit.java
Now that Fedora 37 ships webkitgtk compiled against Gtk 4.x the new *.so name is finally known so we know which lib to dlopen. Guards preventing Browser instantiation when running Gtk 4.x are removed.
Extra change was to no longer manually connect signals like button_press/release, focus_in/out and etc. as they are by default now as per https://trac.webkit.org/changeset/262184/webkit (the web view is always the target of the events, so we don't really  need to send the events to GTK to process them.)
=> [GTK4] Add WebkitGtk support

bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/HTMLWriter.java, bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/RTFWriter.java, bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/StyledTextWriterBase.java
I don't know if it is generic enough to support other future formats.
But at least it puts in a common place the relatively complicated code that iterates and  outputs the line styled ranges.
I've tried to split it into separate commits that might be easier to follow, but I don't know if you prefer that style, or one single commit.
Let me know and I can squash.
Or only squash after you reviewed.
Also, if you think it is overengineered and not worth doing, that's also fine.
Thanks,
Mihai
=> Extracting common code between RTFWriter and HTMLWriter in a base class

bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/gtk3.c, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/gtk3_stats.c, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/gtk3_stats.h, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/org/eclipse/swt/internal/gtk3/GTK3.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Button.java
Button image was incorrectly scaled due to set_from_surface not behaving as expected.
+ Refactored image setting to use GdkPixbuf instead, which fixes the issue.
+ Added gtk_image_set_from_pixbuf to GTK3.java
Signed-off-by: Joel Majano <majanojoel@gmail.com>
Fixes #367
=> [Issue 367] Button Image is wrong size at hi-res scale

bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/StyledText.java
Let me know if you want me to create a new bug for this PR.
For now I've "attached" it to the existing one (#395)
=> Fix Javadoc to mention HTML format for clipboard copy (#292)

bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/widgets/Event.java
One can not link to tests in javadoc as javadoc for them is not generated nor it should ever be.
Moved the debugging part to plain old comment for people looking at the code.
Fixes issue created by https://github.com/eclipse-platform/eclipse.platform.swt/issues/351
=> Fix javadoc.

bundles/org.eclipse.swt/Eclipse SWT PI/win32/library/os_custom.c
The `AllowDarkModeForWindowWithTelemetryId` method was changed again in Windows 11 22H2. I haven't checked Windows 10 to see if the `AllowDarkModeForWindow` method was changed in Windows 10 22H2 or what the build number is for Windows 10 22H2.
=> Add support for AllowDarkModeForWindowWithTelemetryId for Windows 11 22H2

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Tree.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/TreeItem.java, tests/org.eclipse.swt.tests.win32/JUnit Tests/org/eclipse/swt/tests/win32/AllWin32Tests.java, tests/org.eclipse.swt.tests.win32/JUnit Tests/org/eclipse/swt/tests/win32/widgets/TestTreeColumn.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_TreeColumn.java
Since order is frequently needed but rarely changed. Especially the index of the first column is frequently used for each TreeItem.
On Win even such simple systemcalls are more then 50 times slower then jvm internal cache.
=> Win Tree: cache column order

bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/DPIUtil.java
- Add new "half" option for the "swt.autoScale" system property and evaluate in DPIUtil#getZoomForAutoscaleProperty
- Remove unneeded casts to int (Math.round with float argument already returns int)
Signed-off-by: Daniel Krügler <daniel.kruegler@gmail.com>
=> Issue #420: "swt.autoScale" should add new "half" option

bundles/org.eclipse.swt/META-INF/MANIFEST.MF, bundles/org.eclipse.swt/pom.xml
Fixed API tools error. Change in #448 is compatible, but requires version bump.
See https://download.eclipse.org/eclipse/downloads/drops4/I20221031-1800/apitools/analysis/html/org.eclipse.swt/report.html
=> Bump SWT minor version segment, StyledText.dispose() moved up to super

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Display.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Display.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Display.java, examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet380.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_Display.java
Concurrency could be challenging, especially when it comes to UI and
responsiveness. And even more with the single-threading model of SWT
(and other UI frameworks as well) as one easily could block the UI then.
Java for several year contains some where useful tool with the
concurrency framework but it is quite hard for users to interact with
that as SWT does not offer some basic primitives (most notable Executors
and CompletableFuture).
This add some Executor support to the Display to allow integration with
the Executor Framework handling some special requirements of SWT, e.g
the single thread model, disposal checking and exception handling.
See also https://github.com/eclipse-platform/eclipse.platform.swt/issues/64
=> Integrate the Display with the Executor Framework

bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/graphics/Device.java
To my understanding, all modern Linux supported by SWT shall use cairo auto scaling. KDE-based KUbuntu 18.04, where this wasn't the case, is no longer supported.
See also Bug 569233, which intends (not yet merged) to remove support for non-auto-scaling.
=> Issue #457 - Broken scaling on WSLg

bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/HTMLWriter.java, bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/RTFWriter.java, bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/StyledTextWriterBase.java
Tested on Win 11, MacOS  Ventura 13.0.1, Debian 10.
Tested Gmail, Google Docs, Google Slides:
- Win: Chrome & Firefox
- Debian: Chrome & Firefox
- MacOS: Chrome, Firefox, and Safari
Tested platform native apps:
- MS Word 2000 and PowerPoint 2000 on Win
- LibreOffice Writer (~Word / GDocs) and LibreOffice Impress (~PowerPoint / GSlides )
- The Apple Mail, Notes, and TextEdit apps on MacOS (they come with the system)
Screenshots for everything here: https://mihai-nita.net/eclipse_swt_467/
=> Fix #467: Paste as HTML collapses white spaces

bundles/org.eclipse.swt/build.xml
Maybe that build script is not used, which could by why this miss-alignment was not noted?
=> Align 'version.suffix' property to version of o.e.swt in build.xml

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Control.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Control.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Shell.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Control.java
This reverts commit 961810fe5fb0991171cc0d0f7849fd90e0e350fa.
The change causes regression in the code that opens new shells and expects some widget to have a focus in that new shell.
See comments on
https://github.com/eclipse-platform/eclipse.platform.swt/issues/450
=> Revert "Issue #450 - Control.setFocus must not bring the application to front if it is in the background"

bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/BusyIndicator.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/SwtRunnable.java, examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet130.java
Currently it is very hard in SWT to have code that takes a bit longer than executed directly but do not take long enought to show "heavy" feedback to the user like a progress monitor. BusyIndicator claims to help with this task but is hard to be used correctly and cumbersume to use when it comes to further work with the result data, and the Snippet130 demonstrate this complexity quite well: https://github.com/eclipse-platform/eclipse.platform.swt/blob/master/examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet130.java
This adds new methods to BusyIndicator that allows easy usage by integration using CompletableFutures. The Snippet 130 is adjusted to show this much more modern aproach that shows how easy is is to acomplish non blocking mid-lenth running operations.
This …
=> Add methods to execute tasks as CompletableFuture with a "busy" user feedback to BusyIndicator

Jenkinsfile
Skip the unncessary default check-out, because the build operates only on the later site-by-site checked-out sources of o.e.swt and o.e.swt.binaries. Skipping the default checkout can save about a minute for each verification build.
Only use tabs for indentation except for the yml section, where tabs are not supported.
And format lines to make them shorter.
=> [Build] Skip default checkout, add timestamps and only use tabs

Jenkinsfile
Fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/531
Lets see if this helps already.
=> [Build] Adapt to move of SWT's build pipeline to 'releng' Jenkins

bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Shell.java
bringToTop is ignored if the shell is not visible. Without the shell being activated, the behavior of restoreFocus requires the undesired shell activation of setFocus.
=> #536: [GTK] Shell.open: incorrect order of bringToTop and setVisible

bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Composite.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Display.java
SWT segfaults using GTK4/X11 backend when moving the mouse cursor out of the window:
Reproducer:
```
final Display display = new Display();
shell.setLayout(new FillLayout());
Text text = new Text(shell,SWT.NONE);
text.setText("This is a text box.");
shell.setText("GTK4Test");
shell.open();
while (!shell.isDisposed()) {
if (!display.readAndDispatch()) {
display.sleep();
}
}
display.dispose();
}
```
To reproduce, move mouse into, and then out of, the application window.
Resulting seg fault looks like this:
```
Stack: [0x00007f1c5c100000,0x00007f1c5c200000],  sp=0x00007f1c5c1fd2e8,  free space=1012k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C …
```
=> [GTK4] SegFault on X11 in Display#getCursorControl()

Jenkinsfile, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_custom_StyledText.java
If the problem can't be fixed / debugged properly, we should disable the test, otherwise other issues might be not noticed for new PR's.
Workaround for
https://github.com/eclipse-platform/eclipse.platform.swt/issues/294
=> Skip test that fails on Linux docker image on PR validation only (#294)

bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/gtk4.c, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/gtk4_stats.c, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/gtk4_stats.h, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/org/eclipse/swt/internal/gtk4/GTK4.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Button.java, examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet366.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_Button.java, tests/org.eclipse.swt.tests/META-INF/MANIFEST.MF, tests/org.eclipse.swt.tests/pom.xml
When setting the alignment or orientation of arrow buttons we get a UnsatisfiedLinkError, which can be seen in a GTK4 unit test failure and in the non-functioning of SWT Snippet366:
```
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'void org.eclipse.swt.internal.gtk3.GTK3.gtk_image_set_from_icon_name(long, byte[], int)'
at org.eclipse.swt.internal.gtk3.GTK3.gtk_image_set_from_icon_name(Native Method)
at org.eclipse.swt.widgets.Button.setOrientation(Button.java:1190)
at org.eclipse.swt.widgets.Control.setOrientation(Control.java:5808)
at org.eclipse.swt.snippets.Snippet366.lambda$0(Snippet366.java:62)
at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
at …
```
=> [GTK4] Linkage error in Buttons with SWT.ARROW style

Jenkinsfile, bundles/org.eclipse.swt/buildSWT.xml
First part of https://github.com/eclipse-platform/eclipse.platform.swt/issues/513
The build procedure is based on the configurations in https://ci.eclipse.org/releng/view/SWT%20Natives/
Namely these are:
- https://ci.eclipse.org/releng/job/SWT-Increment_if_needed/configure
- https://ci.eclipse.org/releng/job/cocoa_aarch64/configure
- https://ci.eclipse.org/releng/job/cocoa_x86_64/configure
- https://ci.eclipse.org/releng/job/gtk_linux_aarch64/configure
- https://ci.eclipse.org/releng/job/gtk_linux_ppc64le/configure
- https://ci.eclipse.org/releng/job/gtk_linux_x86_64/configure
- https://ci.eclipse.org/releng/job/win32_x86_64/configure
The steps of all those jobs are now perform in the Jenkins-build of this o.e.swt repo and thus makes all the mentioned jobs obsolete. This also makes …
=> Perform SWT-natives build as part of the master/verification build

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/FileDialog.java
`NSSavePanel.savePanel()` and `NSOpenPanel.openPanel()` can return null, so we need to handle this case gracefully.
=> Isseu 586: [macOS aarch64] NPE in org.eclipse.swt.widgets.FileDialog.open

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_Button.java
The test was introduced as part of dfaed5e but unfortunately the method under test has no effect on MacOS, so don't run the test on that platform.
For history see also:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=261270
=> Issue #591: Fix test failure on MacOS

.github/workflows/junit.yml, .github/workflows/maven.yml
Currently the matrix job succeeds if there are test-failures, this can be confusing for people. Also we can modernize the usage of the Test results check to show a +/- delta compared to current master build.
Fix https://github.com/eclipse-platform/eclipse.platform.swt/issues/594
FYI @iloveeclipse @mbooth101
=> Fail matrix job if there are test-failures as well as show delta

pom.xml
Currently SWT do not use the API tools in the build verification, but enabling the profile (-Papi-check) leads to multiple errors and then fails the build.
To allow using this build to unify the verification build infrastructure, SWT can simply declare that even if the profiles are active they are skipped.
=> Explicitly disable API tools execution

bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/MenuItem.java, tests/org.eclipse.swt.tests.gtk/ManualTests/org/eclipse/swt/tests/gtk/snippets/Issue346_JvmCrashRemovingMenuItemAccelerators.java
Null the handle reference after removing the shortcut from the menu item, to prevent it from trying to remove the shortcut more than once.
Also includes the manual test snippet.
=> Issue #346: [GTK4] gtk_shortcut_controller_remove_shortcut crash

Jenkinsfile
This reverts parts of commit 0447a9e50a962595debac122966d4ef978356af8, which was necessary since the Eclipse Releng JIPP was not setup for this.
This required https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2546.
FYI @laeubi.
=> Re-enable enhanced issue recording in Jenkins pipeline

bundles/org.eclipse.swt/.settings/.api_filters, bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/CTabFolder.java, bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/CTabFolder2Listener.java, bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/CTabFolderEvent.java, bundles/org.eclipse.swt/META-INF/MANIFEST.MF, bundles/org.eclipse.swt/pom.xml, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_custom_CTabFolder.java
- added CTabFolder2Listener.itemsCount(CTabFolderEvent) API
- added CTabFolder2Listener.itemsCountAdapter(Consumer<CTabFolderEvent>) API
- updated CTabFolder to notify CTabFolder2Listener on creating/removing items
- added unit test
- bumped minor version segment for new API added
Fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/620
=> CTabFolder should allow to listen on tab count changes

Jenkinsfile, bundles/org.eclipse.swt/buildSWT.xml
Replace the ant target `push_remote_from_workspace` by equivalent steps in the Jenkins pipeline.
This is part of the continued effort to simplify the SWT build and migrate off ANT scripts, as tracked in https://github.com/eclipse-platform/eclipse.platform.swt/issues/513.
It also has the advantage that for commits pushed to maintenance branches the follow-up commits created by the build pipeline are pushed to the same branch automatically.
Generally I suggest to backport the pipeline as it is after this change to active maintenance branches in order to avoid the need to build maintenance binaries locally.
This would eventually make the jobs in https://ci.eclipse.org/releng/view/SWT%20Natives/ obsolete.
=> [Jenkins-Build] Migrate push steps from ANT to Jenkins pipeline

Jenkinsfile
The parameter 'skipCommit' was accessed in a interpolated Groovy GString and therefore needs to be accessed via the params-object.
This was forgotten in commit c760d4b788fb45419f54c491e0dc6c58c3318e62 but for some reason did not show up in the verification build.
=> [Jenkins-Build] Fix access of 'skipCommit' pipeline parameter

.github/workflows/maven.yml, Jenkinsfile
With commit 34af5497383d3f77357c03de6a77d36f681af066 respectively PR https://github.com/eclipse-platform/eclipse.platform.swt/pull/638
The 'build-individual-bundles' profile is activated in the `maven.config` and does not have to be activated explicitly anymore.
=> Remove now unnecessary references of 'build-individual-bundles' profile and migrate to 'coactions/setup-xvfb'

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Composite.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Composite.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_browser_Browser.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_custom_CCombo.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_Composite.java
In the Windows and MacOS implementations of a `Composite`, the `setFocus` method tries to set focus on children even if they are not visible and will thus never receive focus. Depending on the realization of `setFocus` on the children, functionality may be executed that confuses the user as it belongs to a view they do not see (see #616).
The Linux implementation already validates whether a child is visible before setting focus on it. This change makes the implementations consistent across operating systems and ensures the consistent behavior with according regression tests.
https://github.com/eclipse-platform/eclipse.platform.swt/blob/d65eb73da26084e65c3090e7ede0892b3016a112/bundles/org.eclipse.swt/Eclipse%20SWT/gtk/org/eclipse/swt/widgets/Composite.java#L1667-L1675
=> Avoid setting focus on invisible children of Composite #616

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/ToolBar.java, examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet153.java
ToolItem with SWT.CHECK is not well displayed when checked and with background setted.
Fix : https://github.com/eclipse-platform/eclipse.platform.swt/issues/541
=> ToolItem with SWT.CHECK is not well displayed when checked and with background setted.

Jenkinsfile, bundles/org.eclipse.swt/Eclipse SWT PI/cocoa/library/build.sh, bundles/org.eclipse.swt/Eclipse SWT PI/cocoa/library/make_macosx.mak, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/build.sh, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/make_linux.mak, bundles/org.eclipse.swt/Eclipse SWT PI/win32/library/build.bat, bundles/org.eclipse.swt/Readme.Linux.md, bundles/org.eclipse.swt/buildSWT.xml
As described in https://github.com/eclipse-platform/eclipse.platform.swt/issues/626#issuecomment-1507719226 the SWT-natives are currently build against the JDK header files for different Java versions raging from 11 to 19. Because SWT now requires Java-17 (https://github.com/eclipse-platform/eclipse.platform.swt/issues/625), they all should be build against Java-17 headers.
This PR aims to achieve that and at the same time fixes the inconsistencies regarding the headers/libs in the natives build described in https://github.com/eclipse-platform/eclipse.platform.swt/issues/626#issuecomment-1507719226. 
- Use the C header files and shared native libraries from minimal JustJ JDKs when building the SWT native binaries on specialized build machines.
- Always specify the location of the JDK …
=> Build SWT-natives against Java-17 JDK header files

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_browser_Browser.java
The `org.eclipse.swt.tests.junitBrowser.Test_org_eclipse_swt_browser_Browser.test_getText*` tests expect the browser to return the same text as was set to it via `setText`, only ignoring formatting-related information such as capitalization and newline characters. In Windows tests, the browser returns a processed HTML document, which can also differ in other aspects while having the same semantics. One difference is the use of semicolons in style properties.
Since the tests only use basic HTML documents in which the semicolon has no meaning, the proposed change simply ignores semicolons when validating the expected result of Browser.getText.
A more sophisticated test could use the HTML DOM for comparison, but from my perspective the simple fix is sufficient as the comparison (1) is used …
=> Ignore semicolons in validation of Browser.getText tests #103

bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Canvas.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Caret.java, examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet126.java, tests/org.eclipse.swt.tests.gtk/ManualTests/org/eclipse/swt/tests/gtk/snippets/Issue644_CompleteTableEditor.java, tests/org.eclipse.swt.tests.gtk/ManualTests/org/eclipse/swt/tests/gtk/snippets/Issue644_TableEditorWithCanvas.java
Add missing repaints for Caret that is created for an embedded Canvas.
Fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/644
=> SWT TableEditor: Caret is not shown for StyledText Control

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/graphics/GC.java
This fixes the regression in [#631.](https://github.com/eclipse-platform/eclipse.platform.swt/issues/631#issuecomment-1524127112)
There are two commits to make things clearer:
1. Revert the revert of 9e996e825dbcaf2bc95a954cadadd24729b2ab8e
2. Use a unique cache key for each text character with different alpha, font and foreground color attributes
=> Fix regression in 631

bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/HTMLWriter.java, bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/StyledText.java
Does not add additional newline when pasting words to Teams/Word.
=> Copy HTML line fragment without block levels. fixes #593

examples/org.eclipse.swt.examples.watchdog/src/org/eclipse/swt/examples/watchdog/TimedEventWatchdog.java
SimpleDateFormat.format(new Date());
returns same string as immutable and thread-safe
DateTimeFormatter.format(new Date().toInstant())
=> Avoid reuse of not thread-safe SimpleDateFormat

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Control.java, bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Display.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Control.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Display.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Shell.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Control.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Display.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_Shell.java
If the application is in the background and the GUI is updated, especially a different control is getting focused, it might happen that the shell will be brought to front. This patch should fix that.
To get the previous behavior (activate the shell on control.forceFocus(), set the system property
"org.eclipse.swt.internal.activateShellOnForceFocus" to "true").
If you want an application window be brought to front, instead of relying on control.forceFocus() to bring the shell to front, use shell.forceActive().
Shell.open: an explicit bringToTop() is needed now, because the implicit one from setFocus/forceFocus() is not happening any more. For the first shell it needs to be forced, because otherwise it won't do anything (display.activeShell is null).
=> #450/Bug 578929 - Control.setFocus brings windows to front

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Button.java, tests/org.eclipse.swt.tests/ManualTests/org/eclipse/swt/tests/manual/Bug577129_Win11_NoButtonArrows.java
…(UP/DOWN/LEFT/RIGHT)
Buttons use arrows from scrollbar.
The problem is that on Win11, default arrow image for scrollbar is empty because scrollbars no longer show arrows unless pressed/disabled/hovered with mouse pointer.
Change-Id: I44413614690f92a5111dcf74d345e19667a7c89d
Reviewed-on: https://git.eclipse.org/r/c/platform/eclipse.platform.swt/+/191177
Tested-by: Platform Bot <platform-bot@eclipse.org>
Tested-by: Niraj Modi <niraj.modi@in.ibm.com>
Reviewed-by: Niraj Modi <niraj.modi@in.ibm.com>
=> Backport 577129 to 4.23 maintenance

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_Composite.java
Some `Composite` tests introduced with #617 currently fail randomly because waiting for the shell to become active when initializing the test times out.
This change increases the timeout to eliminate slow hardware or bad runtime behavior as a potential reason for failing tests.
Contributes to #616.
=> Increase timeout when waiting for shell to become active in tests #616

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/SwtTestUtil.java
The test utility to wait for a shell to activate introduced in #732 uses a workaround for MacOS to always enforce activation. The current behavior may have no effect because forcing activation before actually making the shell visible has no effect.
This change reorders the statements so that first the activation-triggering action is executed before enforcing activation for the situation that is does not work properly.
Contributes to https://github.com/eclipse-platform/eclipse.platform.swt/issues/724
=> Correct order for triggering shell event and forcing active in test #724

bundles/org.eclipse.swt/META-INF/MANIFEST.MF, bundles/org.eclipse.swt/pom.xml
Tracked in
https://github.com/eclipse-platform/eclipse.platform.swt/pull/717
=> version bump for Backport 577129 to 4.23 maintenance

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Table.java, bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Tree.java
Fixes :https://github.com/eclipse-platform/eclipse.platform.swt/issues/662
The table columns once collapsed one over the other, doesn't  reexpand to bring back to the original form.This is due to the very small spacing.width value of intercell spacing.This is a fix inorder to bring back the default spacing.width value (17.0) to avoid the collapsing problem.
cc/ @lshanmug
=> Enabling default value to spacing to avoid table collapsing in Mac.

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Table.java, bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Tree.java
Reverts eclipse-platform/eclipse.platform.swt#760
Fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/777
=> Revert "Enabling default value to spacing to avoid table collapsing in Mac."

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_browser_Browser.java, tests/org.eclipse.swt.tests/META-INF/MANIFEST.MF, tests/org.eclipse.swt.tests/pom.xml
See https://github.com/eclipse-platform/eclipse.platform.swt/issues/722
=> Disable unstable test_setUrl_remote() on Mac

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_graphics_GC.java
No basic tests exist for the `setLineDash` and `setLineAttributes` methods of the GC class. In addition, the functionalities for setting line width and line dash (including setting the LineAttributes), are not validated with respect to an applied device zoom.
This change adds according tests to the `Test_org_eclipse_swt_graphics_GC` class.
=> Add GC tests for line dash, line attributes and handling device scaling

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Display.java
- We need to set the sub-menu to the application name
- See https://github.com/eclipse-platform/eclipse.platform.swt/issues/779
=> Fix app name not shown in main menu on macOS Sonoma

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/TextLayout.java, bundles/org.eclipse.swt/META-INF/MANIFEST.MF, bundles/org.eclipse.swt/pom.xml, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_graphics_TextLayout.java
The code had been mistakenly splitting even though the style had already split the run.
Adapted manual test case in the bug to a JUnit test.
triggerWinGerrit
Also-by: Alexandr Miloslavskiy <alexandr.miloslavskiy@syntevo.com>
Change-Id: I9fea7f0ac8e30fa38e486dedcdae26034f7f40d2
Reviewed-on: https://git.eclipse.org/r/c/platform/eclipse.platform.swt/+/192078
Tested-by: Platform Bot <platform-bot@eclipse.org>
Reviewed-by: Alexandr Miloslavskiy <alexandr.miloslavskiy@syntevo.com>
Reviewed-by: Jonah Graham <jonah@kichwacoders.com>
cc/ @lshanmug We have a user on 4.23 facing this bug.
=> backport Bug 579335: Fix crash on long styled lines on Windows

bundles/org.eclipse.swt/pom.xml
Fixes : pom.xl changes required.
For issue: backport Bug 579335: Fix crash on long styled lines on Windows #823
cc/ @sravanlakkimsetti
=> Pom.xml changes for swt 

Jenkinsfile, bundles/org.eclipse.swt/buildSWT.xml
They have not been updated for six years and are not considered anymore. This is probably because they are written in another location than where the 'build.sha1' committed into the fragments reside.
But there is already an alternative mechanism used to check for changes, based on git tags.
In https://github.com/eclipse-platform/eclipse.platform.swt.binaries/pull/57 the remaining `build.sha1` files are removed from the binaries-repo.
=> [Build] Remove unnecessary processing of abandoned 'build.sha1' files

bundles/org.eclipse.swt/Eclipse SWT Drag and Drop/gtk/org/eclipse/swt/dnd/ClipboardProxy.java, bundles/org.eclipse.swt/Eclipse SWT Drag and Drop/gtk/org/eclipse/swt/dnd/TextTransfer.java
I now know the buzzwords are:
> "Eclipse support for Wayland clipboard content types (RFC-1341  types)"
https://github.com/eclipse-platform/eclipse.platform.swt/issues/851#issuecomment-1794539321
However the main motivation here is:
` "Being able to use Eclipse comfortably with a LTS based linux distro in a wayland session in  2023"`
The first commit already has an open pr #861 the second has  been tested to work via this method #858
and then cherry picked from R_29_maintenance branch onto master without any issues.
=> Wayland qt kde clipboard fix

bundles/org.eclipse.swt/Eclipse SWT Drag and Drop/gtk/org/eclipse/swt/dnd/ClipboardProxy.java, bundles/org.eclipse.swt/Eclipse SWT Drag and Drop/gtk/org/eclipse/swt/dnd/TextTransfer.java
1) The utf-8 content should be same as in UTF8_STRING, it just should use different label/type id.
2) The change in ClipboardProxy.setData() was non functional and makes no sense, it only leaks memory/wastes time
See https://github.com/eclipse-platform/eclipse.platform.swt/pull/863 See https://github.com/eclipse-platform/eclipse.platform.swt/issues/851
=> Fix wrong implementation of TEXT_PLAIN_UTF8 transfer feature

bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Tree.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/TreeItem.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/performance/Test_org_eclipse_swt_widgets_Tree.java
This eliminates a single hotspot. The full complexity for tree building is still quadratic.
Profile before the fix:
Profile after the fix:
=> [GTK] Optimize TreeItem constructor #882

examples/org.eclipse.swt.examples.launcher/META-INF/MANIFEST.MF, examples/org.eclipse.swt.examples.launcher/build.properties, examples/org.eclipse.swt.examples.ole.win32/META-INF/MANIFEST.MF, examples/org.eclipse.swt.examples.ole.win32/build.properties, examples/org.eclipse.swt.examples.ole.win32/pom.xml, examples/org.eclipse.swt.examples.views/META-INF/MANIFEST.MF, examples/org.eclipse.swt.examples.views/build.properties, examples/org.eclipse.swt.examples/META-INF/MANIFEST.MF, examples/org.eclipse.swt.examples/build.properties, examples/org.eclipse.swt.snippets/META-INF/MANIFEST.MF, examples/org.eclipse.swt.snippets/build.properties
Add missing output specifications in `build.properties`
=> Correct output specifications in build.properties

bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/gtk3.c, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/gtk3_stats.h, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/org/eclipse/swt/internal/gtk3/GTK3.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Control.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Display.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Text.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/ToolTip.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Tracker.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Widget.java
GTK sources say:
Deprecated: 3.12: Style contexts are invalidated automatically.
https://www.eclipse.org/swt/faq.php#gtkstartup says:
Eclipse/SWT 4.16.x: GTK+ 3.20.0 and its dependencies
Eclipse/SWT 4.15.x: GTK+ 3.14.0 and its dependencies
This means that it's been at least 3 years since SWT requires GTK 3.20. Sounds safe to stop using the deprecated function now.
Hopefully fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/697 I couldn't reproduce it in SWT snippet, so I didn't test this with SWT. But when I tested in native snippet, removing `gtk_style_context_invalidate()` changed things a bit and crash no longer occurred.
=> [GTK] Don't use deprecated gtk_style_context_invalidate()

Jenkinsfile
And add a not to the description of 'forceNativeBuilds' parameter that if enabled and 'skipCommit' is not set, the then build binaries will be pushed to the master branch.
FYI @akurtakov and @iloveeclipse
Requested in https://github.com/eclipse-platform/eclipse.platform.swt/pull/919#issuecomment-1833269324.
=> [Build] Build commits from releng-bot if natives build is enforced

.github/workflows/maven.yml, tests/org.eclipse.swt.tests/.project, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/performance/Test_situational.java
Enable PerformanceTests for Pull Requests labeled "performance".
See [discussion](https://github.com/eclipse-platform/eclipse.platform.swt/pull/903#discussion_r1405455957) on why tests can't be enabled on a permanent basis.
=> Enable PerformanceTests #882

bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/gtk3.c, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/gtk3_stats.h, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/org/eclipse/swt/internal/gtk3/GTK3.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Control.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Display.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Text.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/ToolTip.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Tracker.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Widget.java
Reverts eclipse-platform/eclipse.platform.swt#915
This has caused some test failures, see https://github.com/eclipse-platform/eclipse.platform.ui/issues/1351
Fixes https://github.com/eclipse-platform/eclipse.platform.ui/issues/1351
=> Revert "[GTK] Don't use deprecated gtk_style_context_invalidate()"

bundles/org.eclipse.swt/Eclipse SWT Accessibility/cocoa/org/eclipse/swt/accessibility/Accessible.java, bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Display.java, bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Tracker.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/graphics/ImageData.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/graphics/RGB.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/Callback.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/DPIUtil.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/image/JPEGDecoder.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/image/PngChunk.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/image/PngEncoder.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/image/PngIhdrChunk.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/image/PngTrnsChunk.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/layout/BorderData.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/layout/GridData.java
Code cleanup : modernize switch expressions
=> Code cleanup : modernize switch expressions

bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/CTabFolder.java, bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/CTabFolderRenderer.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_custom_CTabFolder.java
- Added new property "showSelectedImage" to CTabFolder parallel to existing property "showUnselectedImage"
- Image rendering in drawSelected method updated in CTabFolderRenderer with handling the new property "showSelectedImage"
- Added standard padding for text of tabs when tab icon is either not available or is hidden (both for selected and unselected tabs)
- Pre-requisite for [issue](https://github.com/eclipse-platform/eclipse.platform.ui/issues/735) and pull request : https://github.com/eclipse-platform/eclipse.platform.ui/pull/1071
=> CTabFolder: Add 'showSelectedImage' property

bundles/org.eclipse.swt/META-INF/MANIFEST.MF, bundles/org.eclipse.swt/pom.xml
=> Bump org.eclipse.swt version due to new API

bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/CTabFolderRenderer.java
Currently, all headers in CTabFolders without an image have a large text padding. This applies to both the case where no image is assigned to a tab item and the case where images shall not be shown as the properties showSelectedImage and showUnselectedImage are both false. While the latter is intended behavior to switch between image-based tab folders and image-less, padding-based tab folders (see #785), the former unintentionally breaks with the existing UI experience for CTabFolders that do not use images.
This change makes the identification of whether large text padding shall be applied explicit by factoring it out into a method (which may be replaced by a different implementation later on). It reduces the cases in which the large text padding is applied to the intended case …
=> Apply large padding only when image for tab item shall not be shown #945

bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Tree.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/TreeItem.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_TreeItem.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/performance/Test_org_eclipse_swt_widgets_Tree.java
This is a follow-up to #903
This is a second optimization for #882.
TreeItem and Tree have been checking indexes for bounds during indexed access and traversal (`GTK.gtk_tree_model_iter_n_children()`) . Such checks are slow as node size computation is an O(N) operation.
As Tree already does iteration of O(N) complexity when retrieving a TreeItem by its index, and such iteration detects out-of-bounds problems, preliminary model bounds check is redundant. Also, bounds check is avoidable during iteration over a node - instead of an index, GTK iterator applies directly.
Performance improvement proved by running `org.eclipse.swt.tests.junit.performance.Test_org_eclipse_swt_widgets_Tree.jfaceReveal()`.
In test jfaceReveal[Shape: STAR, virtual: true]:
10_000 elements: 1_523_338_044ns -> …
=> [GTK] Speedup TreeItem retrieval by removing redundant iterations #882

Jenkinsfile, binaries/binaries-parent/build.xml, binaries/pom.xml
Moving the binaries-parent/build.xml broke the native binaries build and fixing it would require the adjustments of many paths.
This reverts parts of commit 237811252b3f272fcc0dfca2d403b876a404ec64.
=> Revert move of binaries-parent/build.xml into binaries directory

bundles/org.eclipse.swt/Eclipse SWT WebKit/gtk/library/webkitgtk.h
This will change something only in the case when both libs are installed on the machine to make the 4.1(aka compiled against libsoup3) be preferred.
If only one of the libs is installed nothing will change as it will dlopen one or the other no matter the order of trying them. This is an effort to mitigate
https://github.com/eclipse-platform/eclipse.platform.swt/issues/350 where people see crashes with the old version which btw is even scheduled for removal soon from Fedora
https://fedoraproject.org/wiki/Changes/Remove_webkit2gtk-4.0_API_Version .
=> Prefer libwebkit2gtk-4.1.so.0 over libwebkit2gtk-4.0.so.37

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Button.java, tests/org.eclipse.swt.tests/ManualTests/org/eclipse/swt/tests/manual/Issue0519_ButtonAlignmentExample.java
Button's setAlignment() is calculating the right margin value now when text and image are set depending on the alignment of the button.
Fixes
https://github.com/eclipse-platform/eclipse.platform.swt/issues/519
@niraj-modi 
@sravanlakkimsetti 
Can anyone of you review the changes and let me know your comments please.
=> Button's setAlignment() is being considered and right margin value is recalculated depending on alignment set.

.github/workflows/maven.yml
The working directory was incorrectly removed in
https://github.com/eclipse-platform/eclipse.platform.swt/pull/956 but instead just should have been to the changed check-out location.
=> [Build] Fix performance test in GH workflow

binaries/pom.xml
Tycho uses the manifest's Eclipse-PlatformFilter proper without it.
=> Remove unneeded target-platform-environments.

Jenkinsfile, binaries/pom.xml, bundles/org.eclipse.swt/.classpath_cocoa_aarch64, bundles/org.eclipse.swt/.classpath_cocoa_x86_64, bundles/org.eclipse.swt/.classpath_gtk, bundles/org.eclipse.swt/.classpath_win32, bundles/org.eclipse.swt/.gitignore, bundles/org.eclipse.swt/build-scripts/CollectSources.java, bundles/org.eclipse.swt/buildSWT.xml, bundles/org.eclipse.swt/nativeSourceFolders.properties
in order to replace ANT tasks with JavaScript (which require Java-11) in Jenkins pipeline.
Stash native sources not-zipped to save the zip and unzip steps.
Additionally move all remaining ANT tasks to run a native build in a local Maven for the running platform completely to the
maven-antrun-plugin configuration.
Furthermore move declaration of tools to the common Jenkins pipeline section to make them usable in all stages.
Since https://github.com/eclipse-platform/eclipse.platform.swt/pull/633 the JDK on the native-build-agent's PATH is not used anymore when building the native binaries and thus it is not required anymore to keep the PATH untouched.
Part of
- https://github.com/eclipse-platform/eclipse.platform.swt/issues/513
- https://github.com/eclipse-platform/eclipse.platform.swt/issue …
=> [Build] Collect native sources in Jenkins pipeline with Java script

binaries/binaries-parent/build.xml, binaries/pom.xml, bundles/org.eclipse.swt/buildFragment.xml
This avoids the need to compile the swt.jar and src.zip embedded in the SWT zips separately by ANT, which makes the build simpler and faster. 
Perform all intermediate assembling in a sub-directory of the already git-ignored target directory.
Part of https://github.com/eclipse-platform/eclipse.platform.swt/issues/513
=> [Build] Add jars packed by Maven to SWT-zips instead of ANT-built jars

bundles/org.eclipse.swt.tools/Oomph/platformSwt.setup
With https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1719 the required jgit.lfs Plug-in is now installed for all projects in the `Platform` container. Keeping it in the SWT setup is just a duplication.
=> Remove P2Directory elements moved to Platform container from SWT-setup

binaries/pom.xml
This increases the probability that the same jvm running the maven build is used to run the java source scripts.
Maven's launch script by default uses the java executable referenced in $JAVA_HOME/bin first and only then searches the PATH environment variable.
Using the java exe at JAVA_HOME also simplifies to control which jvm is actually used. For example when launching a Maven build from the Eclipse IDE JAVA_HOME is set to the jvm running that build by Eclipse automatically, but PATH is not modified.
This would also have fixed https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1724.
=> [Build] Use JDK in JAVA_HOME to run the Java source scripts

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/List.java, bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Table.java, bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Tree.java
Fixes: #677  
A new function named as `getInset()` is created in `Table.java`. This function calculates the inset value of a cell in a table for aarch64 architecture. The inset value of a row in a table is calculated by subtracting the height of a cell from a frame.This calculated inset value is added to the height in `setItemHeight()` function.
The inset value of 1 is retained for x86_64 architecture.
/cc @lshanmug
=> Fixing the Item height for Table and Tree when the default font is set

.github/workflows/maven.yml, Jenkinsfile, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_SWT.java
and disable the Test_org_eclipse_swt_SWT.test_isLocal() test within the Jenkins pipeline.
And use assumeFalse() to not run said test if the 'disable.test_isLocal' property is set.
Fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/983
=> [Build] Disable p2-baseline-replacement for GH workflows

.github/workflows/maven.yml, binaries/org.eclipse.swt.cocoa.macosx.aarch64/build.properties, binaries/org.eclipse.swt.cocoa.macosx.x86_64/build.properties, binaries/pom.xml, bundles/org.eclipse.swt/build-scripts/CollectSources.java
This allows to test changes in the natives in verification builds on all platforms and not only on Linux because Jenkins re-builds the binaries.
=> [Build] Run SWT native binary build in GH workflows

Jenkinsfile
Increment the Library revision also for enforced native binary re-builds. Besides allowing simplifications of the build, this ensures
the git-based qualifier of the org.eclipse.swt and consequently its native fragments (which use the same qualifier) is updated in that case and a subsequently 'manually' enforced qualifier update is not necessary. Furthermore letter-suffixes for revision git tags are not necessary too.
And remove superfluous steps.
Part of https://github.com/eclipse-platform/eclipse.platform.swt/issues/513
=> [Build] Further streamlining and simplifications of SWT build pipeline

Build-SWT-native-binaries-for-running-platform.launch
In the SWT maven build local building of the native binaries can be activated by setting the system property `native` to `${ws}.${os}.${arch}`.
Consequently the full command for a complete Maven build of SWT that also builds the natives is (with the SWT-repo root as working directory):
`mvn clean verify -Dnative=${ws}.${os}.${arch}`
This full build takes a few minutes and if one skips the test execution, by appending `-DskipTests`, the complete build terminates earlier.
The fastest way to build the native binaries for a platform with Maven is to only run the execution of the `maven-antrun-plugin` that contains the local natives build. On the CLI this would be (with the SWT-repo root as working directory):
`mvn clean antrun:run@build-native-binaries -f …
=> Add  Maven launch-config to build native binaries of running platform

bundles/org.eclipse.swt/Eclipse SWT Program/cocoa/org/eclipse/swt/program/Program.java, bundles/org.eclipse.swt/Eclipse SWT Program/gtk/org/eclipse/swt/program/Program.java, bundles/org.eclipse.swt/Eclipse SWT Program/win32/org/eclipse/swt/program/Program.java
Add zoom level support for Program image data.
=> Add zoom level support for program image data

.github/workflows/maven.yml, Jenkinsfile, tests/org.eclipse.swt.tests.cocoa/META-INF/MANIFEST.MF, tests/org.eclipse.swt.tests.gtk/META-INF/MANIFEST.MF, tests/org.eclipse.swt.tests.win32/META-INF/MANIFEST.MF
All the fragments can build in parallel so this should speed-up the build.
=> [Build] Run Maven build in parallel and only up until the verify phase

Jenkinsfile, binaries/org.eclipse.swt.cocoa.macosx.aarch64/build.properties, binaries/org.eclipse.swt.cocoa.macosx.x86_64/build.properties, binaries/org.eclipse.swt.gtk.linux.aarch64/build.properties, binaries/org.eclipse.swt.gtk.linux.loongarch64/build.properties, binaries/org.eclipse.swt.gtk.linux.ppc64le/build.properties, binaries/org.eclipse.swt.gtk.linux.x86_64/build.properties, binaries/org.eclipse.swt.win32.win32.x86_64/build.properties, binaries/pom.xml, bundles/org.eclipse.swt/Eclipse SWT PI/win32/library/build.bat, bundles/org.eclipse.swt/Eclipse SWT PI/win32/library/make_win32.mak
Part of https://github.com/eclipse-platform/eclipse.platform.swt/issues/513
=> [Build] Unify make targets for native binaries build

bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/CTabFolder.java, bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/CTabFolderRenderer.java
This is follow-up to #785, which introduced an iconless tab folder design that allows to disable tab item images and uses centered text a large padding within tab items as a separator instead. This visualization option for tab folders currently works as follows: A large padding is applied to the tab item as a separator with the text being centered within this padding. For tabs showing a close icon (which in particular is the currently selected on), this icon is added right at the right end of the tab item, such that the text is centered in between the left end of the tab item and the close button.
As discussed downstream in eclipse-platform/eclipse.platform.ui#1071, this does not look perfect and while the padding is necessary as a separator for tabs only containing a text, having close …
=> Fix size of tab items when large text padding is used

tests/org.eclipse.swt.tests.cocoa/META-INF/MANIFEST.MF, tests/org.eclipse.swt.tests.cocoa/build.properties, tests/org.eclipse.swt.tests.gtk/META-INF/MANIFEST.MF, tests/org.eclipse.swt.tests.gtk/build.properties, tests/org.eclipse.swt.tests.win32/META-INF/MANIFEST.MF, tests/org.eclipse.swt.tests.win32/build.properties
As discussed in https://github.com/eclipse-platform/eclipse.platform.swt/pull/1010#discussion_r1470690947:
In the build.properties we can add a proper comment to explain the purpose of these difficult to understand dependencies.
=> Move concurrent execution preventing test dependencies to build.props

bundles/org.eclipse.swt/Eclipse SWT Browser/win32/org/eclipse/swt/browser/Edge.java, bundles/org.eclipse.swt/Eclipse SWT PI/win32/org/eclipse/swt/internal/ole/win32/COM.java
Instead of always showing a "no more handles" error, with this change an error due to invalid thread access is explicitly logged as such.
Contributes to https://github.com/eclipse-platform/eclipse.platform.swt/issues/1013
=> Distinguish Edge instantiation error due to invalid thread access #1013

bundles/org.eclipse.swt/Eclipse SWT Browser/win32/org/eclipse/swt/browser/Edge.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_browser_Browser.java
The handle to a newly instantiated Edge browser is provided via a callback. This callback may be either be invoked synchronously when creating a WebView2 controller (happens on first creation of an Edge browser instance in an application) or asynchronously via a processed OS event (from second creation of an Edge browser instance onwards). The callback is currently released before the OS events are processed, which may cause issues when instantiating more than one Edge browser in a single application.
With this change, the callback is only released when it is not required and may not be called anymore. A test instantiating multiple (Edge) browsers in a single application is added to ensure that the asynchronous callback invocation is executed in a test.
Contributes to …
=> Avoid callback release before its usage during Edge instantiation #1013

tests/org.eclipse.swt.tests/pom.xml
to get same warnings on jenkins as in workspace
=> pom.xml: remove code.ignoredWarnings

bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/CTabFolder.java
Minimize and Maximize button images needs to be created afresh when foreground color change is done in CTabFolder.
Fixes #832
@niraj-modi
@sravanlakkimsetti
@HeikoKlare
@merks 
Can anyone of you review the changes and let me know your comments please.
=> Minimize and Maximize button images needs to be created afresh when foreground color change is done in CTabFolder #832

bundles/org.eclipse.swt/META-INF/MANIFEST.MF
Some projects, like BND tools, will avoid using require-bundle at great lengths. This becomes problematic when the APIs they want to use do not version there `Export-Package` properly.
Many Eclipse projects, including SWT, do not version their API packages.  They only version their individual bundles with respect to semantic versioning.
For BND they resorted to using `Import-Package` with the `bundle-version` and `bundle-symbolic-name` of the host. This "worked" because the SWT API packages were defined in the `Export-Package` header of the host bundle. But now with PR #1008 this changed and the host bundle no longer defines the exported packages. The end result is BND tools is now broken and has many unresolvable bundles.
Until this is sorted out, this PR simply adds back the …
=> Add back exports to the org.eclipse.swt host

binaries/.classpath_cocoa, binaries/.classpath_gtk, binaries/.classpath_win32
Without that launching standalone Java SWT application from the development workspace fails to load the native binaries of the platform, as it was discovered in https://github.com/eclipse-platform/eclipse.platform.swt/pull/1008#discussion_r1478458586.
Unfortunately it looks like variable resolving does not work (at least it didn't work for me locally), altough this old forum post says it should work to resolve variables in `org.eclipse.jdt.launching.CLASSPATH_ATTR_LIBRARY_PATH_ENTRY`'s value:
https://www.eclipse.org/forums/index.php/t/152868/
Does anybody now if there is something else that needs to be done?
=> Restore CLASSPATH_ATTR_LIBRARY_PATH_ENTRYs in native .classpath files

bundles/org.eclipse.swt/META-INF/MANIFEST.MF
Fixes few API errors reported after 2ca0b37ecbeff105797d5fce72675bf306ad5282
=> Mark exported org.eclipse.swt.internal package as internal

binaries/org.eclipse.swt.cocoa.macosx.aarch64/build.properties, binaries/org.eclipse.swt.cocoa.macosx.x86_64/build.properties, binaries/org.eclipse.swt.gtk.linux.aarch64/build.properties, binaries/org.eclipse.swt.gtk.linux.loongarch64/build.properties, binaries/org.eclipse.swt.gtk.linux.ppc64le/build.properties, binaries/org.eclipse.swt.gtk.linux.x86_64/build.properties, binaries/org.eclipse.swt.win32.win32.x86_64/build.properties, binaries/pom.xml, bundles/org.eclipse.swt/build-scripts/CollectSources.java
Lets see how this works out...
=> Link the sources in the build properties instead of copy by ant

bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/StyledText.java, bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/StyledTextRenderer.java, bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/graphics/FontMetrics.java, bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/graphics/TextLayout.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/graphics/TextLayout.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/TextLayout.java, tests/org.eclipse.swt.tests/ManualTests/org/eclipse/swt/tests/manual/Issue0932_StyledText_FixedLineHeight.java
Please see #932 and included testing snippet. In it, create two StyledText: basic and with `Use fixed line height` option.
=> Issue 932: implement fixed line height for StyledText

bundles/org.eclipse.swt/Eclipse SWT PI/win32/library/os_custom.c
This is required for https://github.com/eclipse-platform/eclipse.platform.swt/pull/1045 to continue.
For reference, here are the disassemblies:
`AllowDarkModeForWindow()`:
```
00007FFB16C32450 D503237F             pacibsp  
00007FFB16C32454 A9BE53F3             stp         x19,x20,[sp,#-0x20]!  
00007FFB16C32458 F9000BF5             str         x21,[sp,#0x10]  
00007FFB16C3245C A9BF7BFD             stp         fp,lr,[sp,#-0x10]!  
00007FFB16C32460 910003FD             mov         fp,sp  
00007FFB16C32464 53001C33             uxtb        w19,w1  
00007FFB16C32468 D29523C1             mov         x1,#0xA91E  
00007FFB16C3246C AA0003F5             mov         x21,x0  
00007FFB16C32470 9400F226             bl          #GetPropW (07FFB16C6ED08h)
...
``` …
=> Handle validation of uxtheme.dll undocumented exported functions in ARM64 builds

binaries/org.eclipse.swt.cocoa.macosx.aarch64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.cocoa.macosx.x86_64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.gtk.linux.aarch64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.gtk.linux.loongarch64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.gtk.linux.ppc64le/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.gtk.linux.x86_64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.win32.win32.x86_64/META-INF/MANIFEST.MF, bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/StyledText.java, bundles/org.eclipse.swt/META-INF/MANIFEST.MF, bundles/org.eclipse.swt/pom.xml
Copied HTML is much bigger then plain text. Fall back to copy at least the plain text.
https://github.com/eclipse-platform/eclipse.platform.swt/issues/1059
=> Catch OOME during copy HTML to Clipboard #1059

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Scrollable.java
Horizontal mouse wheel event needs to be triggered when horizontal mouse wheel events are generated.
Fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/994
Can one of you review please
@merks
@niraj-modi
@sravanlakkimsetti
=> Always vertical mouse wheel events are getting triggered even when horizontal mouse wheel events are generated.

binaries/org.eclipse.swt.cocoa.macosx.aarch64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.cocoa.macosx.x86_64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.gtk.linux.aarch64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.gtk.linux.loongarch64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.gtk.linux.ppc64le/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.gtk.linux.x86_64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.win32.win32.x86_64/META-INF/MANIFEST.MF, bundles/org.eclipse.swt/Eclipse SWT PI/cocoa/org/eclipse/swt/internal/cocoa/OS.java, bundles/org.eclipse.swt/Eclipse SWT PI/win32/org/eclipse/swt/internal/win32/OS.java, bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/DirectoryDialog.java, bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/FileDialog.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/DirectoryDialog.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/FileDialog.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/DirectoryDialog.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/FileDialog.java, bundles/org.eclipse.swt/META-INF/MANIFEST.MF, bundles/org.eclipse.swt/pom.xml
The `FileDialog` and `DirectoryDialog` implementations do currently not provide any way to identify that the dialog was canceled. The dialogs return a null string in case no file or folder was selected, but is not possible to identify whether this was intended (via a cancel action) or if there was some unexpected error while the dialog was open (such as too long file paths on Windows).
This change introduces the `openDialog()` method as an alternative to the existing `open()` method. This new method returns an optional String, which is only present if a file or directory was successfully selected. An empty Optional indicates a cancellation by the user and an actual error is realized as an SWTException. The dialogs evaluate the operating system's response code for the system's dialog …
=> Expose cancel state of FileDialog and DirectoryDialog

bundles/org.eclipse.swt.tools.base/META-INF/MANIFEST.MF, features/org.eclipse.swt.tools.feature/feature.xml
Force a new version so that publishing to Maven Central can update the version without specialized remapping rules.
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1882
=> Increment the version of org.eclipse.swt.tools.base

binaries/pom.xml, bundles/org.eclipse.swt/pom.xml, pom.xml
Currently there are some  special configuration in the poms using ant scripts that want to ensure that swt host and fragements use the same build qualifier.
This now uses the new fragment-host timestamp provider to ensure this instead so we are able to get rid of this.
=> Use the new fragment-host timestamp provider

bundles/org.eclipse.swt/Eclipse SWT PI/cocoa/org/eclipse/swt/internal/cocoa/OS.java, bundles/org.eclipse.swt/Eclipse SWT PI/cocoa/org/eclipse/swt/internal/cocoa/Selector.java, bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Widget.java
- Add a new selector setClipsToBounds
- Set this selector to true in Widget#drawRect
- See https://github.com/eclipse-platform/eclipse.platform.swt/issues/1012
=> Fix for Mac drawing bug

.github/workflows/maven.yml
Optional performance tests rely on prebuilt SWT components to be available. `mvn install` phase is essential for this. This phase was removed in #1010.
Performance tests had started to [fail](https://github.com/eclipse-platform/eclipse.platform.swt/actions/runs/8203164002/job/22435425736?pr=918) with:
```
Error:  Cannot resolve project dependencies:
Error:    You requested to install 'osgi.bundle; org.eclipse.swt.fragments.localbuild 0.0.0' but it could not be found
```
Broken performance tests are blocking work in #918.
@laeubi could you please add [performance](https://github.com/eclipse-platform/eclipse.platform.swt/pulls?q=is%3Apr+is%3Aopen+label%3Aperformance) label to this MR?
@HannesWell please review
=> Fix Performance tests #882 #1010 #918

Jenkinsfile
If make_common.mak changes, code in 'Check if SWT-binaries build is needed' stage, that is supposed to delete native libraries, simply doesn't delete anything as it relies on getSWTVersions() that reads (changed) versions.
Instead, try to delete *every* library file stored in git before copying freshly compiled ones during 'Collect and sign binaries' stage.
Fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/1095
=> Remove all existing native libraries before copying new compiled

tests/org.eclipse.swt.tests/META-INF/MANIFEST.MF, tests/org.eclipse.swt.tests/pom.xml
This is needed to fix builds in #918
The builds were failing with message:
```
Only qualifier changed for
(org.eclipse.swt.tests/3.107.300.v20240313-1307). Expected to have bigger x.y.z than what is available in baseline (3.107.300.v20240227-1638)
```
=> Increment the version of org.eclipse.swt.tests

binaries/org.eclipse.swt.cocoa.macosx.aarch64/.settings/.api_filters, binaries/org.eclipse.swt.cocoa.macosx.x86_64/.settings/.api_filters, bundles/org.eclipse.swt/Eclipse SWT Accessibility/cocoa/org/eclipse/swt/accessibility/Accessible.java, bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/graphics/GCData.java
For cocoa specific implementations of
- o.e.swt.accessibility.Accessible tag methods already tagged as @noreference also with @nooverride so that API tools considers them as internal and does not complain about non-API types being referenced in their signature.
- o.e.swt.graphics.GCData tag all fields as @noreference so that API tools does not complain about non-API types being used in public fields of this actually internal class (tagged as @noreference).
Suppress issue about forbidden extension of Scrollable by Composite.
=> Fix API warnings in macosx fragments

Jenkinsfile
This reduces the prerequisites for a Jenkins executor to run that part of the build pipeline.
Listing the just build binaries again does not help much but requires more setup and more software installed at the executing node.
Also required for https://github.com/eclipse-platform/eclipse.platform.swt/pull/1045.
=> [Build] Simplify build-script in pipeline for windows native binaries

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Display.java, bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/List.java, bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Table.java, bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Tree.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_List.java
cocoa: Enforce native item height for Table, Tree, List if necessary
Newer versions of macOS introduced a new style of table rows with a
padding that is larger than previously seen. This broke item height
computations (#677). An attempt to fix this had the unexpected side
effect that now some UI elements in Eclipse IDE (and other apps with
"-Dorg.eclipse.swt.internal.carbon.smallFonts" enabled),
eclise.platform.ui #1674, and it also broke compatibility with older
versions of macOS that did not have the additional padding.
This change, reverts the previous fix and adds logic to enforce
the native item height by default, but only when smallFonts is not
enabled.
The setting can also be controlled by a new System property,
org.eclipse.swt.internal.cocoa.enforceNativeItemHeightMinimum, that, …
=> Fix for [macOS] some UI elements (e.g. list, tree views) seem to have more space between lines now #1674

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_graphics_Image.java
The cached image width/height must be reset when the zoom factor is changed, otherwise call to `getBounds` will return wrong values
=> Reset the cached image width/height when the currentZoom of an image has changed

bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/os.c, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/org/eclipse/swt/internal/gtk/GTK.java
These are available since Gtk 3.14 and are used unconditionally thus don't have to be dynamic.
That would give a bit better backtraces when crashing during DnD.
=> Make gtk_gesture* bindings non-dynamic

Jenkinsfile, binaries/org.eclipse.swt.win32.win32.aarch64/.project, binaries/org.eclipse.swt.win32.win32.aarch64/.settings/.api_filters, binaries/org.eclipse.swt.win32.win32.aarch64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.win32.win32.aarch64/WebView2Loader.dll, binaries/org.eclipse.swt.win32.win32.aarch64/build.properties, binaries/org.eclipse.swt.win32.win32.aarch64/fragment.properties, binaries/pom.xml, bundles/org.eclipse.swt/Eclipse SWT PI/win32/library/build.bat, local-build/org.eclipse.swt.fragments.localbuild/META-INF/p2.inf, pom.xml
This PR contains changes to the `build.bat` file, to support compiling the SWT natives for the WoA platform, and associated files to produce the SWT binaries module's jar/zip files for WoA.
On a WoA box, run the following commands to produce the SWT natives (`swt*.dll`) for WoA:
```batch
cd binaries\org.eclipse.swt.win32.win32.aarch64
mvn clean process-resources -Dnative=win32.win32.aarch64
```
and the `swt*.dll` files for WoA will be created in the current directory.
Cross-compiling between the x64 and Arm64 platforms, where either of them can be host or target, is also possible, after setting up the `TARGET_ARCH` environment variable with correct "target architecture" value, and with the `SWT_JAVA_HOME` property pointing to an available JDK of the target architecture.
For example, to …
=> Compile SWT natives for Windows on Arm64 (WoA).

bundles/org.eclipse.swt/META-INF/p2.inf, examples/org.eclipse.swt.examples.ole.win32/META-INF/MANIFEST.MF, examples/org.eclipse.swt.examples.ole.win32/META-INF/p2.inf, examples/org.eclipse.swt.examples.ole.win32/pom.xml
Especially for the `org.eclipse.swt` fragment host, the `win32.aarch64` fragment entry in its `p2.inf` file would help in resolving the SWT classes required during compile of other modules (like `eclipse.platform`, `eclipse.platform.ui`, etc.) for the Windows on Arm64 platform.
=> fix missing win32.aarch64 fragment in various p2.inf

bundles/org.eclipse.swt/META-INF/p2.inf, examples/org.eclipse.swt.examples.ole.win32/META-INF/p2.inf
As long org.eclipse.swt.win32.aarch64 is not included in the 'eclipse' repository it cannot be mandatory.
See https://github.com/eclipse-platform/eclipse.platform.ui/pull/1789#issuecomment-2031249051.
=> Make requirement of o.e.swt for swt.win32.aarch64 temporarily optional

bundles/org.eclipse.swt/Eclipse SWT Program/win32/org/eclipse/swt/program/Program.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java
This replaces the fix for black icon background because of faulty alpha values contributed via #999 with the solution proposed in #998. As documented in #1130, #999 produced a regression as some program icons (such as for `.exe` files) are not loaded anymore.
Under certain conditions, program icons loaded on Windows via GDI+ have empty mask data, even though the original icon has proper mask data. As a result, these icons are printed with a black instead of a transparent background. Still these icons can contain valid alpha data in their usual 32-bit data.
With this change, alpha data is extracted for icons which are loaded
without proper mask data to ensure that they have proper transparency
information.
Fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/715
Fixes …
=> [Win32] Extract alpha values from icons if available #715 #1130 

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Table.java, bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Tree.java
SelectionEvent.item in callback method widgetSelected now contains the current selected item
Fixes: https://github.com/eclipse-platform/eclipse.platform.swt/issues/1052
=> fix SWT table/tree control SelectionListener on Mac

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/graphics/GC.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/graphics/GC.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/GC.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_graphics_GC.java
The offset calculation in the GC when having an odd line width is erroneous in case rotation transformations have been applied to the GC. With a rotation of 45°, the calculation even suffers from singularities that result in effectively nothing being drawn. With other transformation properties, off-by-one error occur.
This change inverts the offset calculation: Instead of performing a forward transformation of a dummy point whose result is applied to the expected offset, the inverse transformation is applied to the expected offset. This avoids singularities and imprecision in the calculation and ensures that when applying rotations to the GC, the drawing figures are as expected.
The behavior can be evaluated with [Snippet 381](https://github.com/eclipse-platform/eclipse.platform.swt/blob/c …
=> Correct GC offset calculation #788

bundles/org.eclipse.swt/Eclipse SWT Drag and Drop/cocoa/org/eclipse/swt/dnd/DropTarget.java, bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Label.java
Bringing the required changes to `DropTarget.java`
In the method  `static long dropTargetProc(long id, long sel, long arg0`), the label widget that doesn't actaully have a drop target key was being checked to see if it has a drop target key or not instead of the widget that actually has the drop Target key. So the code eventually failed to recognise label as an area where drop is possible. As soon as we get a label as a widget, the modified code checks for the label's parent to see if drop target key is present or not. If present the area is recognised for drop.
Also a new function called `private void handleLabels(Control c)` is also added to bring the feature of dropping on to the top of a label that has an image view. This functions takes a control as a parameter to go up the hierarchy …
=> Drag and Drop made available for a label that has an Image view.

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Display.java, bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/List.java, bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Table.java, bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Tree.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_List.java
This is to backport Fix , cocoa: Enforce native item height for Table, Tree, List if necessary to 4.31
Refs: https://github.com/eclipse-platform/eclipse.platform.swt/pull/1117
@MohananRahul
=> Backport Fix, cocoa: Enforce native item height for Table, Tree, List  to 4.31

bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Shell.java, tests/org.eclipse.swt.tests.gtk/ManualTests/org/eclipse/swt/tests/gtk/snippets/Issue1161_InitialWrongShellSizeDialogTrim.java
For GDK.gdk_window_get_frame_extents (window, rect) to return correct values shell should be open. Once SWT asks GTK to show the shell via Native calls it takes sometime to open the shell.
On high performance machines adjustTrip is asking GTK to give it width and height before it has completely opened the shell. This results in returning default size.(which is {0,0,1,1})
So We can use the height and width which we already know when opening the shell.
Fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/1161
=> Use known width and height of the shell instead of asking GDK.gdk_window_get_frame_extents (window, rect).

bundles/org.eclipse.swt/Build-SWT-native-binaries-for-running-platform.launch
The path was broken since the projects got moved:
But now the path can found:
Also refresh the workspace after running:
Adapt the documentation accordingly.
=> Fix Maven launch config to build SWT binaries

bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/DefaultContent.java, bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/StyledText.java, bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/StyledTextRenderer.java
If text is deleted while the IME assistent is open the start of the open IME has to be adjusted accordingly
https://github.com/eclipse-platform/eclipse.platform.swt/issues/1162
=> fix IllegalArgumentException when deleting text while IME open #1162

bundles/org.eclipse.swt/Readme.Linux.md, bundles/org.eclipse.swt/Readme.Win32.md, bundles/org.eclipse.swt/Readme.macOS.md, bundles/org.eclipse.swt/Readme.md
Contributes to #1171 
See https://github.com/eclipse-platform/eclipse.platform.swt/pull/1167#issuecomment-2052499527
Move some sections of the documentation to the general `Readme.md` file and change some outdated/unclear documentation in Windows.
FYI I provided 2 commits for clarity but I will squash them before merging.
=> [Documentation] Update instructions to build SWT binaries locally

bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/os.c, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/os_stats.h, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/org/eclipse/swt/internal/gtk/GTK.java, bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Scrollable.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Scrollable.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Scrollable.java
eclipse-platform#1184
Add Scrollable.setScrollbarsMode(int) method to provide the possibility to disable/enable overlay scrollbars.
Fixes: eclipse-platform#1184
=> Add Scrollable.setScrollbarsMode for changing overlay mode

.github/workflows/maven.yml
<s>GitHub Actions changed their latest images for MacOS to use the AArch64 instead of the x86_64 architecture. The SWT tests are currently failing because they still assume `macos-latest` to be an x86_64 architecture and therefore use the according SWT binaries.
With this change, the proper SWT binaries (AArch64) are used for the MacOS image.
As an alternative, we could use the `macos-latest-large` image, which uses latest x86_64, but since for Mac devices AArch64 is becoming kind of the new normal, I would propose to stick to `macos-latest` and use the according binaries instead. Feel free to share your opinion on this.</s>
GitHub Actions changed their latest images for MacOS to use the aarch64 instead of the x86_64 architecture. The SWT tests are currently failing because they still …
=> Adapt GitHub Actions configuration to execute MacOS on x86_64 image

bundles/org.eclipse.swt/Eclipse SWT Browser/win32/org/eclipse/swt/browser/Edge.java
Currently when the ICoreWebView2Controller gets the focus this is not reflected on the browser widget.
This adds a GotFocus handler and forces the focus on the browser widget.
Fixes #1139
=> [win][edge] add focus delegate to browser

bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/DPIUtil.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/AllNonBrowserTests.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/DPIUtilTests.java
For our ongoing work to improve the HiDPI support in the Windows implementation, we are currently working on #131. We need adaptions on DPIUtil to be able to directly pass the target zoom for the up and down scaling utility methods. To provide small PRs for different components, I'd like to contribute our changes on DPIUtil seperately and in advance because they will be needed in all following PRs.
In summary, this contribution adds additional methods to scale different datatypes up or down by passing the target zoom level as parameter. All existing methods will delegate to the added methods and pass DPIUtil::deviceZoom as zoom.
=> Extend DPIUtil to provide scale up and down methods with target zoom as parameter

.github/workflows/maven.yml, pom.xml
GitHub provides aarch64 runners for MacOS and has recently made them even the default runners for MacOS. In order to also validate on aarch64 in addition to x86_64, this change extends the build configuration matrix to also be executed on a MacOS aarch64 runner.
=> Extend GitHub actions configuration matrix for MacOS AArch64 build

bundles/org.eclipse.swt/Eclipse SWT PI/win32/library/build.bat
and remove elements specific to old build-clusters that are unused now.
The win32.aarch64 binaries are already build with MSVC 2022 and I have already requested to update MSVC on the x86_64 windows build machine to 2022 as well:
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4444
Once that is completed I think we should simply require require MSVC 2022 to build the SWT native binaries for Windows for all architectures.
=> [Build|Win32] Simplify build.bat for SWT's windows native binaries

.gitignore, binaries/.classpath_win32, binaries/org.eclipse.swt.win32.win32.aarch64/.project, binaries/org.eclipse.swt.win32.win32.x86_64/.project, binaries/pom.xml, bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/internal/DefaultSWTFontRegistryTests.java, bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/internal/PlatformSpecificExecution.java, bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/internal/ScalingSWTFontRegistryTests.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/internal/DefaultSWTFontRegistry.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/internal/ScalingSWTFontRegistry.java, tests/org.eclipse.swt.tests.win32/JUnit Tests/org/eclipse/swt/tests/win32/AllWin32Tests.java
The classes DefaultSWTFontRegistry and ScalingSWTFontRegistry are currently public only to make them testable from a test bundle. There is currently no pre-configured way to implement unit tests for classes that are not directly accessible via public API.
With this change, the SWT Win32 fragments are extended by a configuration for providing fragment-internal unit tests executed with plain Maven surefire, which can access the classes under test even with reduced visibility. Due to current limitations in Tycho (see https://github.com/eclipse-tycho/tycho/issues/3803), an according temporary extension to the Maven configuration for the binaries projects is made. This configuration is applied to the tests for the DefaultSWTFontRegistry and ScalingSWTFontRegistry, such that their visibilities …
=> Reduce Win32 FontRegistries visibility and move tests inside fragment

bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/DirectoryDialog.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/FileDialog.java, tests/org.eclipse.swt.tests.gtk/ManualTests/org/eclipse/swt/tests/gtk/snippets/Issue1062_FileChooserNativeDialog.java
`gtk_file_chooser_native_new handle()` should be dereferenced after use as proposed in https://docs.gtk.org/gtk3/class.FileChooserNative.html.
Otherwise `gtk_native_dialog_run()` seem to continue to run (probably because the opened menu still references the dialog), with the effect that: `the recursive main loop gives the effect of a modal dialog (it prevents the user from interacting with other windows in the same window group while the dialog is run)`.
See https://docs.gtk.org/gtk3/method.NativeDialog.run.html
Fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/1062
=> FileDialog & DirectoryDialog hang after closing them with opened menu

bundles/org.eclipse.swt/META-INF/p2.inf, examples/org.eclipse.swt.examples.ole.win32/META-INF/p2.inf
Now that an Equinox launcher is  available for Windows on ARM and the win32.aarch64 environment is activated in the Eclipse Maven build (see https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1917), the requirement don't need to be optional anymore.
This reverts commit 5a79f9f370c4b378f46ef58b9e09e82f8729f7d9.
Part of https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/577
@chirontt FYI
=> Revert "Make requirement of o.e.swt for swt.win32.aarch64 temporarily optional"

.github/workflows/maven.yml
GH Actions transitioned to Node 20 in Septmber 2023 and all projects should transition too (see:
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/)
This gets rid of the warnings in the runs of GH Actions.
=> Update coactions to use NodeJS v20

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Widget.java
- OS.objc_msgSend(id, OS.sel_setClipsToBounds_, true) needs to be applied in two more cases
- See https://github.com/eclipse-platform/eclipse.platform.swt/issues/1012
=> Fix for Mac drawing bug issue 1012 part 2

bundles/org.eclipse.swt/Eclipse SWT PI/cocoa/org/eclipse/swt/internal/cocoa/OS.java, bundles/org.eclipse.swt/Eclipse SWT PI/cocoa/org/eclipse/swt/internal/cocoa/Selector.java, bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Display.java
- See https://github.com/eclipse-platform/eclipse.platform.swt/issues/1228
- On macOS 14 and later a warning message is written to console:
"WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES."
- As recommended by Apple, this change adds a new selector for applicationSupportsSecureRestorableState and returns a 1 value (YES) in the callback in the Display class
- However, this only takes care of the NSApplicationDelegate created in the Display class. The warning message will still appear when a splash screen is created in Equinox JNI code so a fix there is also required. See https://github.com/eclipse-equinox/equinox/issues/630
- This implementation for SWT can be …
=> Fix warning message on Mac about secure coding not enabled

bundles/org.eclipse.swt/Eclipse SWT PI/cocoa/org/eclipse/swt/internal/cocoa/OS.java, bundles/org.eclipse.swt/Eclipse SWT PI/cocoa/org/eclipse/swt/internal/cocoa/Selector.java, bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Display.java
- This can cause a crash to desktop
=> Revert "Fix warning message on Mac about secure coding not enabled"

bundles/org.eclipse.swt/Eclipse SWT PI/win32/library/os_custom.c
Continues #1048 #1045
Here's the disassembly:
```
00007FFA2A1D3E10 D503237F             pacibsp  
00007FFA2A1D3E14 F81F0FF3             str         x19,[sp,#-0x10]!  
00007FFA2A1D3E18 A9BF7BFD             stp         fp,lr,[sp,#-0x10]!  
00007FFA2A1D3E1C 910003FD             mov         fp,sp  
00007FFA2A1D3E20 B00007E8             adrp        x8,wil::details::g_enabledStateManager+40h (07FFA2A2D0000h)  
00007FFA2A1D3E24 B94BB913             ldr         w19,[x8,#0xBB8]  
00007FFA2A1D3E28 2A0003E1             mov         w1,w0  
00007FFA2A1D3E2C 912EE100             add         x0,x8,#0xBB8  
00007FFA2A1D3E30 97FF7910             bl          _InterlockedExchange (07FFA2A1B2270h)  
00007FFA2A1D3E34 2A1303E0             mov         w0,w19  
00007FFA2A1D3E38 A8C17BFD             ldp …
```
=> [win32][arm64] Support Dark Theme on newer Windows builds

.github/ISSUE_TEMPLATE/bug_report.md
Added note for Linux users about crash reporting/webkit
See https://github.com/eclipse-platform/eclipse.platform.swt/issues/843
=> Update bug_report.md for Linux users

binaries/org.eclipse.swt.cocoa.macosx.aarch64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.cocoa.macosx.x86_64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.gtk.linux.aarch64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.gtk.linux.loongarch64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.gtk.linux.ppc64le/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.gtk.linux.x86_64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.win32.win32.aarch64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.win32.win32.x86_64/META-INF/MANIFEST.MF, bundles/org.eclipse.swt/META-INF/MANIFEST.MF, bundles/org.eclipse.swt/pom.xml
See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2085
=> Bump SWT bundle versions for 4.33

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/GC.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Caret.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Control.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Shell.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/TableItem.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/TreeItem.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Widget.java
* https://github.com/eclipse-platform/eclipse.platform.swt/issues/127
* https://github.com/eclipse-platform/eclipse.platform.swt/pull/1214
This contribution is to provide the nativeDeviceZoom to all the widgets so that it can be used later on for e.g. font scaling and more. Currently, the nativeDeviceZoom is only available via the shell, which is not sufficient later when there is no shell available, e.g. GC.
In this following PR https://github.com/eclipse-platform/eclipse.platform.swt/pull/1214 , we had discussed that instead of storing zoom for widgets, we should store nativeDeviceZoom, to make it more accessible where shell is not present. Because in some cases, there was no nativeDeviceZoom present because of the …
=> Store nativeDeviceZoom in widgets instead of zoom for win32

bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/graphics/GlyphMetrics.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/TextLayout.java
In this contribution the DPIUtil dependency from org.eclipse.swt.graphics.GlyphMetrics is removed including all package protected pixel producing methods. As (at least) Windows receivces HiDPI support for multiple zoom levels, this is a prerequisite to contribute this feature. As a consequence all callers inside SWT that still used the pixel dependent methods are adapt to only use the public API.
Contributes to #62 and #131
=> Remove methods producing pixel values in GlyphMetrics

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Tree.java
With the current implementation of the handler on DPI zoom changes, not all rescaling cases are covered correctly. If the item height was set at least once programmatically (currently done in Tree::setItemHeight), it will never be done by the OS anymore. With the current implementation a double scale up can happen (once scaled up from the OS and once from the handler), see:
To make it failsafe a new internal flag is used to evaluate whether the item height was set programmatically or not.
1. Adapt the VM argument of e.g. the Eclipse IDE by adding
```
```
2. Have two monitors with different zoom, e.g. 100% and 150%
3. Start the IDE on 100%
4. Open the Outline view
5. Move it to the monitor with 150%  -> The item height will be …
=> Update tree item height correctly on DPI change

bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/DPIUtil.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/GC.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/GCData.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Button.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Composite.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Control.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Display.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/ExpandBar.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Label.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/MenuItem.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Table.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Tree.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Widget.java, tests/org.eclipse.swt.tests.win32/JUnit Tests/org/eclipse/swt/graphics/GCWin32Tests.java, tests/org.eclipse.swt.tests.win32/JUnit Tests/org/eclipse/swt/internal/DPITestUtil.java
* https://github.com/eclipse-platform/eclipse.platform.swt/pull/1236
* https://github.com/eclipse-platform/eclipse.platform.swt/pull/1247
* https://github.com/eclipse-platform/eclipse.platform.swt/pull/1243
This pull request is a base pull request for several following PRs which implement multi zoom level support for different components (resources, widgets, etc). 
In this PR, the focus is on GC to enable it to use the zoom level information which is added to widget. Also, it provides zoom level information in GCData which can later be used …
=> Implementation of GC to enable multi zoom level support for win32

bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/graphics/GCWin32Tests.java, bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/internal/DPITestUtil.java, bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/internal/Win32AutoscaleTestBase.java, bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/widgets/ControlWin32Tests.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Control.java
In Control::setFont the passed font and not the font from the SWTFontProvider is used. This has only an effect when the ScaledFontRegistry is used and a font is passed, that does not match the current zoom of the control.
Contributes to https://github.com/eclipse-platform/eclipse.platform.swt/issues/62 and https://github.com/eclipse-platform/eclipse.platform.swt/issues/127
=> Fix usage of re-scaled fonts in Control:setFont for windows

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/FontMetrics.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/GC.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Composite.java
* https://github.com/eclipse-platform/eclipse.platform.swt/pull/1244
This pull request is based on the implementations of PR #1214. It provides the native zoom to the font metrics which can further be utilized by GC and Text Layout using Public APIs, since fonts are scaled to native zoom. (based on PR #1214 ).
=> Implementation of FontMetrics to enable multi zoom level support for win32

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/TableItem.java
In TableItem::setFont with the index specified, the passed font and not the font from the SWTFontProvider is used. This has only an effect when the ScaledFontRegistry is used and a font is passed, that does not match the current zoom of the table item.
1. Adapt the VM argument of the ControlExample
```
```
2. Have two monitors with different zoom, e.g. 100% and 150%
3. Start the ControlExample on 100%
4. Move it to the monitor with 150%
5.  Change column font 
6.  -> The font will have the wrong size: 
top after -> bottom before
=> Fix usage of re-scaled fonts in TableItem::setFont for Windows

examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet123.java, examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet186.java, examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet337.java, examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet81.java, examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet83.java
* The static method should be accessed directly
* The static field should be accessed directly
* discouraged access
=> Snippets: reduce warnings

bundles/org.eclipse.swt/Eclipse SWT Drag and Drop/win32/org/eclipse/swt/dnd/DragSource.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Cursor.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/GC.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/internal/CommonWidgetsDPIChangeHandlers.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/internal/ImageList.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Button.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Caret.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Control.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Decorations.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Display.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Label.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Menu.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/MenuItem.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/TabFolder.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Table.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/TableColumn.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/TableItem.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/TaskItem.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/ToolBar.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/ToolItem.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/TrayItem.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Tree.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/TreeColumn.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/TreeItem.java, tests/org.eclipse.swt.tests.win32/JUnit Tests/org/eclipse/swt/graphics/ImageWin32Tests.java
This pull request is based on the implementations of PR #1214. It extends to the native zoom which is provided within widget and propagated to GC. In this PR, we provide a map of different handles to Image for different device zoom levels as required by different monitors. The method win32_getHandle provides the appropriate handle for the scaled image as per requested by the client. The clients avail the zoom level information from the GCData and Widget (based on PR #1214 ).
=> Implementation of Image to enable Multi Zoom Level Support for Win32

bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/graphics/TextLayoutWin32Tests.java, bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/internal/Win32AutoscaleTestBase.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Font.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/FontMetrics.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/TextLayout.java
This pull request is based on the implementations of PR #1243. This commit adds the support of scaling of text layout based on the zoom level of the monitor it is drawn on. It uses the native zoom which is provided by the GCData if available otherwise the zoom level set in the font (since the right font for a zoom level is computed already at the control level, so we always have the consistent zoom information).
=> Implementation of Text Layout to enable multi zoom level support for win32

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Button.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Combo.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Composite.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Control.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/DateTime.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Decorations.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Label.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/List.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Menu.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/ProgressBar.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Scale.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/ScrollBar.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Scrollable.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Shell.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Slider.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Spinner.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Table.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Text.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Tree.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/TreeColumn.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Widget.java
**NOTE: these changes affect only _Windows_**
Writing GetSystemMetrics method in Widget class so that the child controls can use it to get System Metrics to be DPI dependent. There are some visible affected areas (before and after zooming to 200 from 100) for which screenshots are attached. 
The OS.getSystemMetrics call had a slight issue in some of the controls i.e. Combo, List and Table. The values returned for scroll i.e. `OS.SM_CXVSCROLL` were independent of DPI. So moving the shell from smaller zoom level to higher zoom level we can see the visible difference in the scroll bar which is not visible in the latter part. 
If a scrollbar is shown or not could perhaps be a side effect in some scenarios, but the main reason for that change is that the correct value for scroolbar sizes are …
=> Adapt GetSystemMetrics call to be DPI dependent

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/GC.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Pattern.java, tests/org.eclipse.swt.tests.win32/ManualTests/org/eclipse/swt/widgets/PatternWin32ManualTest.java
This PR introduces multi zoom level support of pattern using a map which maintains patterns at different zoom level. The map is used by a package protected method which is used in GC in the place where the handle of patterns are needed. Since, testing patterns automatically for how they look visually is a bit difficult, so there's a snippet created for manual testing of the same pattern at different zoom levels.
=> Implementation of Pattern to enable multi zoom level support for win32

bundles/org.eclipse.swt.tools/JNI Generation/org/eclipse/swt/tools/internal/EmbedMetaData.java, bundles/org.eclipse.swt.tools/META-INF/MANIFEST.MF, features/org.eclipse.swt.tools.feature/feature.xml, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_Control.java
When https://github.com/eclipse-jdt/eclipse.jdt.core/pull/2471 is merged, ecj will signal more casts as unnecessary.
With this PR I suggest to remove affected casts before new warnings will show up in the build.
=> remove unnecessary casts

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_graphics_GC.java
This commit fixes an issue when creating a GC from an Image using a device bound to another thread as the GC is currently created in.
=> Fix for #1288: No exception when creating GC with image from another thread

bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/graphics/TransformWin32Tests.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/GC.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Transform.java
This pull request is based on the implementations of PR #1214. It extends to the native zoom which is provided within widget and propagated to GC. In this PR, we provide a map of different handles to Transform for different zoom levels as required by different monitors. The method win32_getHandle provides the appropriate handle for the scaled transform as per requested by the client. So far, Transform is only used by GC in the project, so all the calls from GC has been adapted to use the new method to obtasin the right handle.
=> Implementation of transform to enable Multi Zoom Level Support for Win32

bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/graphics/PathWin32Tests.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/GC.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Path.java
This pull request is based on the implementations of PR #1214. It extends to the native zoom which is provided within widget and propagated to GC. In this PR, the multiple zoom level functionality is attained by using a map to maintain the handle of the path scaled as per the zoom level. The handle can then be obtained by the method win32_getHandle by passing the zoom information from the client.
=> Multi zoom level path

bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/widgets/Event.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Composite.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Control.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/CoolBar.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Display.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/ExpandBar.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/IME.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/List.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Sash.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Table.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/TableColumn.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Text.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/ToolBar.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Tracker.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Tree.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/TreeColumn.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Widget.java
In this contribution the DPIUtil dependency from org.eclipse.swt.widgets.Event is removed including all package protected pixel consuming or returning methods. As (at least) Windows receivces HiDPI support for multiple zoom levels, this is a prerequisite to contribute to this feature. As a consequence all callers inside SWT that still used the pixel dependent methods are adapted to only use the public API.
Contributes to #62 and #131
=> Remove package protected methods consuming or producing pixel values in Event

binaries/org.eclipse.swt.cocoa.macosx.aarch64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.cocoa.macosx.x86_64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.gtk.linux.aarch64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.gtk.linux.loongarch64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.gtk.linux.ppc64le/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.gtk.linux.x86_64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.win32.win32.aarch64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.win32.win32.x86_64/META-INF/MANIFEST.MF, bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/BusyIndicator.java, examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet130.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/AllWidgetTests.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_custom_BusyIndicator.java
While the methods to perform an operation with busy indication are already a great help to write responsive UI there is one case missing where a (Completable)Future is already present, this can for example be used to cache some heavy work.
This now adds a new BusyIndicator.showWhile(Future) method that covers the use case of an externally provided future computation so the caller can be sure that while it takes place the UI shows an indicator.
Beside that the Snippet30 was enhanced to demonstrate the new function.
=> Add support to display the busy indicator while a Future is running

binaries/org.eclipse.swt.cocoa.macosx.aarch64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.cocoa.macosx.x86_64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.gtk.linux.aarch64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.gtk.linux.loongarch64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.gtk.linux.ppc64le/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.gtk.linux.x86_64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.win32.win32.aarch64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.win32.win32.x86_64/META-INF/MANIFEST.MF, bundles/org.eclipse.swt/META-INF/MANIFEST.MF, bundles/org.eclipse.swt/pom.xml
This was forgotten in https://github.com/eclipse-platform/eclipse.platform.swt/pull/1266
Also require the bumped minor version of the o.e.swt host in the fragments.
Because it was forgotten the [I-build 4.33#31](https://ci.eclipse.org/releng/job/Builds/job/I-build-4.33/31/) broke because the o.e.swt host requires a fragment for that platform with the exact same version.
```
[ERROR] Cannot resolve dependencies of project org.eclipse.platform:org.eclipse.jface:eclipse-plugin:3.35.0-SNAPSHOT
[ERROR]  with context {osgi.os=linux, org.eclipse.update.install.features=true, osgi.arch=x86_64, org.eclipse.update.install.sources=true, osgi.ws=gtk, org.eclipse.jdt.buildtime=true}
[ERROR]   Software being installed: org.eclipse.jface 3.35.0.qualifier
[ERROR]   Missing requirement for filter …
```
=> Bump minor version of o.e.swt bundle to align it with its fragments

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/TreeItem.java
Incorrect scaling for TreeItem font when moving through different zoom levels.
Contributes to https://github.com/eclipse-platform/eclipse.platform.swt/issues/62 and https://github.com/eclipse-platform/eclipse.platform.swt/issues/127
```
```
- Switch to the tab "Tree"
- Set any font from the side bar window
- Move the window from 100 to 200 zoom level monitor
- See if scales properly
The list font should be scaled properly
=> Incorrect scaling for TreeItem font

bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/graphics/GCWin32Tests.java, bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/graphics/PathWin32Tests.java, bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/graphics/TextLayoutWin32Tests.java, bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/graphics/TransformWin32Tests.java, bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/internal/DefaultSWTFontRegistryTests.java, bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/internal/ScalingSWTFontRegistryTests.java, bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/internal/Win32AutoscaleTestBase.java, bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/widgets/ControlWin32Tests.java, bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/widgets/WidgetWin32Tests.java
This migrates the unit tests placed in the SWT win32 production fragments to JUnit 5. The visibility of the test classes is reduced to `packaged protected` as allowed by JUnit 5.
This resolves the API errors as reported in #1298.
Fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/1298
=> Migrate win32 unit tests to JUnit 5 and reduce test visibility #1298

bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/internal/DPITestUtil.java, bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/internal/PlatformSpecificExecution.java, bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/widgets/WidgetWin32Tests.java
Some recently added files miss copyright headers. This adds proper headers according to the contributors.
=> Add missing copyright headers to win32 test classes

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/GC.java
This PR fixes the image scaling bug in GC data. The image was scaled with the native zoom of the GC Data instead of the zoom. This leads to the the problem of no image drawn but just a white background. The image is only visible when the zoom and nativeZoom are the same. This behavior can be seen if the IDE is started at i.e. 125% zoom level on the default monitor. Hence, in this case the zoom is set to 100 and nativeZoom is 125. And due to wrong scaling, the lineNumberRulerColumn and minimize and maximize button images are not visible but rather just a white background is visible. 
This fix provides the right scaling to the image in the GC Data using the zoom but not the nativeZoom level as per the standard.
=> GC Data image scaling Bugfix

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Region.java
This commit removes the constructor and the following method win32_new and hereby confirm that none of the clients consume them.
=> Removal of region constructor with handle param

bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/DPIUtil.java
The swt.autoScale.updateOnRuntime has currently only effect in the win32 implementation. Therefor parsing of the flag will only be done on win32. This does not fix any open issue currently, but will make sure, **IF** this flag is used in common code, relying on it will result in a unintended execution on GTK or cocoa.
This PR is a prerequisite to get rid of the "Restart on DPI Change" dialog in WorkbenchWindow with the flag being true on win32
=> Parse swt.autoScale.updateOnRuntime only in win32

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/internal/DPIZoomChangeRegistry.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Decorations.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Menu.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/MenuItem.java
**Note:** issue can only occur in windows with flag swt.autoScale.updateOnRuntime set to true
This commit applies dpi changes to all menus in this menus attribute in Decorations as well in windows, so pop-up menus are no longer opened on the wrong location.
1. Have two monitors with different zoom settings
2. Start IDE
3. Move Java Editors on both of the monitors
4. Right-click on multiple positions in the editor on the non-primary monitor -> in some places they are opened at the mouse location in some places not
=> [win32][fix] apply dpi change to menus attribute for Decorations in windows

bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/StyledText.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/internal/CommonWidgetsDPIChangeHandlers.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Caret.java
This PR allows the caret to scale on a DPI change event on styled text. It uses the line height of the styled text to set on caret. The height and width field in the caret are storing data in points now and not in pixels. We do so to avail the scaling refernece. Also we use SWT.DEFAULT to ignore setting of width. It is useful when we set the new height on DPI change since the preferred width of the caret is loadeed from preferences on the Caret creation.
=> Multi zoom level support for caret

bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/CCombo.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/internal/CommonWidgetsDPIChangeHandlers.java
Registering the comboDpiChange handler and applying change manually to
text, image and arrow
Contributes to https://github.com/eclipse-platform/eclipse.platform.swt/issues/62 and https://github.com/eclipse-platform/eclipse.platform.swt/issues/127
- Run the `CustomControlExample` with the following **VM Arguments**
```
```
- Switch to the tab "CCombo"
- Move the window from 100 to 200 zoom level monitor
- See if scales properly
Combo list, text and arrow should be properly scaled.
=> Scaling combo text according to zoom level

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Display.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Text.java
This contribution provides the ability to scaling the special icons of Text in win 32, i.e., Search and Cancel icon. The scaled icon is obtained at the draw time in the method Text.WM_DRAWITEM. We get rid of the fields hIconSearch and hIconCancel and we maintain a hashmap of size to icon for both the icons. We use the size as the key since the size of the icon is based on the rectangle it is drawn in. And since the size of the rectangle is determined from the OS directly, the size can be non-uniform sometimes. So we maintain the hashmap for size to handle instead of the zoom.
* Start an eclipse workspace with the arguments metioned below and open the error log view.
```
-Xms256m
-Xmx2048m
```
* There's a text bar in the view containing a search icon to …
=> Scaling of Text Icon for multi zoom level (win 32)

bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/graphics/RegionWin32Tests.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/GC.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Region.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Control.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_Shell.java
This pull request is based on the implementations of PR #1214. It extends to the native zoom which is provided within widget and propagated to GC. In this PR, the multiple zoom level functionality is attained by using a map to maintain the handle of the region scale as per zoom level. The handle can then be obtained by the method win32_getHandle by passing the zoom information from the client.
=> Multi Zoom Support for region for win32

examples/org.eclipse.swt.examples/src/examples_control.properties, examples/org.eclipse.swt.examples/src/org/eclipse/swt/examples/controlexample/TableTab.java, examples/org.eclipse.swt.examples/src/org/eclipse/swt/examples/controlexample/TreeTab.java
Updating the example by adding option to make Table and Tree Widgets editable
This commit is part of testing the custom controls for multi-monitor support.
**HOW TO TEST**
* Run the _Runtime Workspace_ launch configuration
* Open the _SWT Controls_ view
* Switch to the tab "Tree"/"Table"
* Check the "Editable" option under "Other"
* Edit the content of the tree/table
=> Updating the control example by adding option to make Table and Tree Widgets editable

bundles/org.eclipse.swt/Eclipse SWT WebKit/gtk/org/eclipse/swt/browser/WebKit.java
Asking to report bugs at eclipse bugzilla which no one will look at is plain wrong and forgotten during migration.
=> Switch Linux Webkit timeout to github from bugzilla

bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/StyledText.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_custom_StyledText.java
StyledText#getTextBounds returns 0x7fffffff as x value if input parameters start and end have the same value and line at the given offset is empty. This looks not correct from my point of view. 
This has the effect that code minings in org.eclipse.jface.text.examples.codemining.CodeMiningDemo are not drawn correctly. Two LineHeaderCodeMinings to be drawn on the same line are then drawn on top of each other (see screenshot at https://github.com/eclipse-platform/eclipse.platform.ui/pull/2024).
=> fix boundary condition in StyledText#getTextBounds

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/FileDialog.java
For Cocoa if `NSSavePanel` or `NSOpenPanel` can't be created, return an empty Optional instead of `null` to prevent a `NullPointerException` in `FileDialog.open()`.
Fixes an issue with #588.
=> Return empty instead of null if FileDialog fails to open

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Button.java
The modification of the magic number allows for scaling up or down through DPIUtil. This only affects Radio or Check Buttons. There is no visual difference between using the magic number and DPIUtil.
These Screenshots are from the genral preferences. 
Without the change on 100% zoom 
With the change on 100% zoom 
Without the change on 200% zoom 
With the change on 200% zoom 
Without the change on 100% zoom, move it to 200%.
With the change on 100% zoom, move it to 200%.
Contributes to https://github.com/vi-eclipse/Eclipse-Platform/issues/72
=> Scale up magic number

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/graphics/Image.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/DPIUtil.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/graphics/Image.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java
This PR renames the method autoScaleImageData to scaleImageData in DPIUtil for the variants of the method which accept a target zoom since it sounds more relevant to the action.
=> Rename auto scale image data

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Tree.java
The method calculateAndApplyIndentSize in `Tree ` class is called again and scaled according to the zoom level when moving the shell across different zoom level screens. 
Before the fix: (100 -> 200)
After the fix:  (100 -> 200)
```
```
- Switch to the tab "Tree"
- Move the window from 100 to 200 zoom level monitor
- See if the indentation looks normal
The list should be indented properly.
Note: There is a visible issue with other zoom level changes as well. i.e. 200 -> 100
=> Re-calculating the indent size for Tree on zoom change

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Display.java
The runtime auto-scaling for multi-monitor HiDPI support on Windows requires the system's DPI awareness to be set to PerMonitorV2. This change makes the Display class initialize its UI thread with the according DPI awareness.
Contributes to https://github.com/eclipse-platform/eclipse.platform.swt/issues/62
Contributes to https://github.com/eclipse-platform/eclipse.platform.swt/issues/131
<s>⚠️  Depends on and has to be merged after #1355</s>
You need to start an application with a different DPI awareness mode than "Per Monitor V2", e.g., by changing the JVMs manifest, with the runtime autoscaling activated (VM argument `-Dswt.autoScale.updateOnRuntime=true`).
I have added a manifest with DPI awareness set to "System" to my JVM and started SWT Snippet 106 on a 100% monitor and moved to a …
=> Initialize Win32 Display thread with correct OS DPI awareness 

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Device.java
The property "enableAutoScaling" has been introduced the Device class in the Windows implementation for HiDPI support year ago, but it has never been used. This removes the unused property.
=> Remove unused enableAutoScaling property of Device on Windows

bundles/org.eclipse.swt/Eclipse SWT AWT/win32/org/eclipse/swt/awt/SWT_AWT.java, bundles/org.eclipse.swt/Eclipse SWT Drag and Drop/win32/org/eclipse/swt/dnd/DragSource.java, bundles/org.eclipse.swt/Eclipse SWT Drag and Drop/win32/org/eclipse/swt/dnd/DropTarget.java, bundles/org.eclipse.swt/Eclipse SWT Drag and Drop/win32/org/eclipse/swt/dnd/TableDropTargetEffect.java, bundles/org.eclipse.swt/Eclipse SWT Drag and Drop/win32/org/eclipse/swt/dnd/TreeDropTargetEffect.java, bundles/org.eclipse.swt/Eclipse SWT OLE Win32/win32/org/eclipse/swt/ole/win32/OleClientSite.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Device.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Widget.java
=> Replace dpiutil scale calls by scale with zoom calls

bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/CTabFolder.java
This commit changes the createButtonImage method in CTabFolder. Until now the requested image data were created once and are scaled to other zoom settings with an AutoScaleImageDataProvider, which is a destructive operation when scaling it to a smaller zoom. With this change the whole logic is moved into an ImageDataProvider, so each time ImageData for a specific zoom value is requested, it will be created from scratch for this zoom value.
If you have the rescaling enabled in win32 switching from 200% to 100% would shrink the image to something like
With the change it looks like 
This is affected a common widget, so it must be tested on all OS. As I currently don't have a working Linux or MacOS available, I cannot do it myself.
=> Create CTabFolder images with ImageDataProvider

bundles/org.eclipse.swt/Eclipse SWT Drag and Drop/win32/org/eclipse/swt/dnd/DragSource.java, bundles/org.eclipse.swt/Eclipse SWT PI/win32/org/eclipse/swt/internal/win32/OS.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/internal/ImageList.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Button.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/TabFolder.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Table.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/ToolBar.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/ToolItem.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Tree.java
This PR mainly is targeted on refactoring the existing callback for ToolBar and ToolItem after a DPI change in the win32 implementation. 
To achieve that a method to scale an ImageList was added. Scaled variants of an image list are saved and reused similar to the other Resources.
The refactoring uses the scalable ImageLists to reuse the existing toolbar items and only resets the ImageList with a correctly scaled one. Due to the limitations of the win32 implementation all items must be removed and re-added via the win32-API to make shrinking of toolbars possible. Additionally, the commit removes the now unused callback in ToolItem.
All calls to the ImageList handle are replaced to use the added method.
=> [win32] Refactor toolbar dpi callback

bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/graphics/GCWin32Tests.java, bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/internal/Win32AutoscaleTestBase.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/internal/DPIZoomChangeRegistry.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Control.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Shell.java
This PR adapt how the DPI change is propagated into the DPI update mechanism. In comes down to the following:
It is exactly as in the beginning -> A ZoomChanged event is send for the affected control, wenn the zoom is changed
The update is no longer propagation via a ZoomChanged event that was used by a listener in a Shell to propagate this change into the DPIZoomChangeRegistry, but it is directly propagated into DPIZoomChangeRegistry in the WM_DPICHANGED callback.
Additionally, for each widget, that is handled in DPIZoomChangeRegistry for a dpi change a ZoomChanged event is created and sent to the widget. That enables creators of custom widget to hook into the update and refresh the state of the affected widget, e.g. refresh a widget, when it is rendering its content without a layout …
=> [win32] Forward ZoomChanged to all child widgets

bundles/org.eclipse.swt/Eclipse SWT PI/win32/org/eclipse/swt/internal/win32/OS.java, bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/widgets/DisplayWin32Test.java, bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Display.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Display.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Display.java
Activating rescaling at runtime requires a proper DPI awareness mode to be set. Currently, if setting the DPI awareness mode fails, rescaling may still be activated if the user requested to. With this change, setting the rescaling mode of a Display ensures that the correct DPI awareness for the UI thread is set and, in case an error occurs, the rescaling mode is not changed. It also adapts some faulty constants and provides according test cases for setting the rescaling behavior.
=> Only consider rescaling at runtime enabled when DPI awareness mode fits

bundles/org.eclipse.swt/Eclipse SWT Drag and Drop/win32/org/eclipse/swt/dnd/TableDragSourceEffect.java, bundles/org.eclipse.swt/Eclipse SWT Drag and Drop/win32/org/eclipse/swt/dnd/TreeDragSourceEffect.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java
Now that we have the zoom level information avaialble for the element, we can use the right zoom information instead of DPIUtil.get(Native)DeviceZoom method calls since this information might not always be right.
=> Replace DPIUtil.get(Native)DeviceZoom for win32

bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/graphics/TextLayoutWin32Tests.java, bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/internal/Win32AutoscaleTestBase.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/TextLayout.java
This commit fixes too high lines when vertical indent was set for one TextLayout. There was a usage of vertical indent in pixels where vertical indent in points should have been used.
With PR
Without PR
=> [win32] Fix TextLayout::getBounds vertical indent

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/ToolBar.java
If the toolbar has no items then the method still executes and sends 2 unnecessary `OS` calls:
* `OS.SendMessage(toolBar.handle, OS.TB_BUTTONSTRUCTSIZE, TBBUTTON.sizeof, 0);`
* `OS.SendMessage(toolBar.handle, OS.TB_AUTOSIZE, 0, 0);`
* Modify the `Snippet18` and remove all items in the toolbar
* Run the modified `Snippet18` with the vm arguments: `-Dswt.autoScale.updateOnRuntime=true`
* Same visual result as the code in `master`
* The OS calls should not happen.
=> Add early return to ToolBar::handleDPIChange in case it has no items

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/TableColumn.java
This PR prevents the creation of a SWT.Resize event when table columns are resized after a zoom change. Therefore, the ignoreColumnResize attribute is utilized during the resizing to disable the creation of the resize event.
This will prevent JFace TableColumnLayouts to break when using ColumnWeighData to configure column sizes. They would be invalidated when a SWT.Resize occurs.
As the resizing of the column after a zoom change is not really a resizing but just an adjusting to the new environment, preventing a SWT.Resize event seems like the way to go.
You can test the different behaviour of the PR with Snippet016TableLayout
=> [win32] Prevent event on table column resize

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Tree.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/TreeColumn.java
This PR prevents the creation of a SWT.Resize event when tree columns are resized after a zoom change. Therefore, the ignoreColumnResize attribute is added to Tree to copy the behavior of Table in the same scenario. This attribute is used during the resizing because of the zoom change to disable the creation of the resize event.
This will prevent JFace TreeColumnLayouts to break when using ColumnWeighData to configure column sizes. They would be invalidated when a SWT.Resize occurs.
As the resizing of the column after a zoom change is not really a resizing but just an adjusting to the new environment, preventing a SWT.Resize event seems like the way to go.
You can test the different behaviour of the PR with Snippet027TreeLayout
=> [win32] Prevent event on tree column resize

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Widget.java
Scrollbars are missing on non default screen scaling [Blocker for 4.33 M3 build]. Regression occurred due to https://github.com/eclipse-platform/eclipse.platform.swt/pull/1209
Contributes to: https://github.com/eclipse-platform/eclipse.platform/issues/1489
=> Missing scrollbars in compare editor

Jenkinsfile
Openjdk one is stuck at 17.0.2 while temurin one is updated to newer builds.
=> Switch to temurin JVM

bundles/org.eclipse.swt/Eclipse SWT Browser/win32/org/eclipse/swt/browser/Edge.java, bundles/org.eclipse.swt/Eclipse SWT PI/win32/org/eclipse/swt/internal/ole/win32/ICoreWebView2AcceleratorKeyPressedEventArgs.java
The ICoreWebView2AcceleratorKeyPressedEvent does not give us all key events and is therefore much less complete than the IE.handleDOMEvent() equivalent.
But at least this allows us to react on VK_ESCAPE and similar things, allowing e.g. element info popups to be closed via ESC.
Resolves #1403
=> Edge: Implement ICoreWebView2Controller#add_AcceleratorKeyPressed()

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/graphics/TextLayout.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/graphics/TextLayout.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/TextLayout.java
Line selection background is drawn without the line spacing value in the StyledText control. For a multiline selection, a zebra effect occurs which looks questionable from my point of view. In this change, the line spacing height is included when drawing the selection background. 
Before with line spacing value 60%:
After with line spacing value 60%:
=> selection background drawn with the line spacing for multiline selection

bundles/org.eclipse.swt/Eclipse SWT OLE Win32/win32/org/eclipse/swt/ole/win32/OleClientSite.java
- This commit fixes an issue where a call to DPIUtil was scaling down from points to pixels instead of scaling up
https://github.com/eclipse-platform/eclipse.platform.swt/issues/1434
=> Use correct DPIUtil call for pixel conversion in OleClientSite.setBounds

bundles/org.eclipse.swt/Eclipse SWT OLE Win32/win32/org/eclipse/swt/ole/win32/OleClientSite.java
This commit fixes an issue, where a call to DPIUtil was scaling down from points to pixels instead of scaling down
Fixes #1434
=> [fix]Use correct DPIUtil call for pixel conversion

bundles/org.eclipse.swt/Eclipse SWT PI/gtk/org/eclipse/swt/internal/gtk/OS.java
If running on a system that does not have the required glibc version then important information is lost to tell the user what is wrong. For example:
version 'GLIBC_2.34' not found (required by .../libswt-pi3-gtk-4966r6.so)
=> Need to print the exception message to give more information

binaries/org.eclipse.swt.cocoa.macosx.aarch64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.cocoa.macosx.x86_64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.gtk.linux.aarch64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.gtk.linux.loongarch64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.gtk.linux.ppc64le/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.gtk.linux.x86_64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.win32.win32.aarch64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.win32.win32.x86_64/META-INF/MANIFEST.MF, bundles/org.eclipse.swt/Eclipse SWT Browser/common/org/eclipse/swt/browser/Browser.java, bundles/org.eclipse.swt/Eclipse SWT Browser/common/org/eclipse/swt/browser/WebBrowser.java, bundles/org.eclipse.swt/META-INF/MANIFEST.MF, bundles/org.eclipse.swt/pom.xml, examples/org.eclipse.swt.examples/META-INF/MANIFEST.MF, examples/org.eclipse.swt.examples/src/org/eclipse/swt/examples/controlexample/BrowserTab.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_browser_Browser.java, tests/org.eclipse.swt.tests/META-INF/MANIFEST.MF, tests/org.eclipse.swt.tests/pom.xml
The contribution provides an API to check if the location is the location where custom texts are loaded in a browser. By construct, "about:blank" is used for that purpose. This API can be adapted by the clients instead of explicitly defining the string and checking.
Contributes to #213
=> Extend Browser API to check for custom text location

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Widget.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Widget.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Widget.java
Widget#addListener(int, Listener) currently states that event constants are defined in the SWTError class, but these constants are defined in the SWT class. This change fixes the faulty reference.
The faulty reference was introduced with:
- #1112
@HannesWell, I guess this was just by accident and not intended, right?
=> Correct faulty reference to listener constants for Widget

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_browser_Browser.java
The browser test case test_isLocationForCustomText_isSetUrlNotCustomTextUrlAfterSetText validates that after setting a browser URL this same URL is then returned by Browser#getURL(). However, the Browser API does not guarantee this behavior and the assertion is even unnecessary for the scenario to be tested, which is already covered by other assertions at the proper level of abstraction.
This change removes the unnecessary assertion.
Contributes to https://github.com/eclipse-platform/eclipse.platform.swt/issues/1455
=> Remove erroneous assertion from browser test #1455

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_browser_Browser.java
Browser tests try to create a valid URL to set in the browser. The mechanism to determine this URL depends on whether the test is executed in an Ant build. This mechanism uses an unnecessary conversion to a URI, which can fail in case the URL string is an OS-specific absolute file system path.
This change removes the unnecessary conversion and a code duplication.
Fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/1455
<s>⚠️ Depends on #1456</s>
=> Correct valid browser URL calculation in browser tests #1455

examples/org.eclipse.swt.examples/src/org/eclipse/swt/examples/controlexample/BrowserTab.java
The SWT ControlExample does currently not provide a configuration option to use Edge browser on Windows (i.e., to activate the SWT.EDGE flag, like is provided for SWT.WEBKIT) already.
This change adds an according configuration option.
=> Make Edge browser available in ControlExample

bundles/org.eclipse.swt/Eclipse SWT Browser/win32/org/eclipse/swt/browser/Edge.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_browser_Browser.java
This contribution fixes Edge browser for win32 to allow serving webpages using setText method where the source code may refer to local resources.
The problem with setText in the modern browser is that webView2 navigates to a page "about:blank" (which is not the part of the intranet) [[reference](https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.winforms.webview2.navigatetostring?view=webview2-dotnet-1.0.2535.41#remarks)] and sets the html to the DOM. In case the html contains reference to local resource, the browsers throws error "can't load local resource" because of security reasons. This contribution fixes it by navigating edge to a temporary file created in the temporary folder of the OS and hence allowing it to load the local resources, and then sets the html to the …
=> Handle local resource references in Edge#setText()

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/TextLayout.java
LineContentCodeMinings are not properly rendered on windows with odd text scale factors like 125%, 150%, 250%, ... 
Here a screenshot of the CodeMiningDemo application located in eclipse.platform.ui\examples\org.eclipse.jface.text.examples.
The gap after the echoed code mining "echo" does not appear for text scale factor 100% and 200%.
The gap disappears by applying the changes in this pull request as shown in the next screenshot:
All `DPIUtil.scaleUp()` calls in class `org.eclipse.swt.graphics.TextLayout` use the result of `getZoom` as zoom level; but not the ones for `GlyphMetrics.width` which use the value `nativeZoom`. Is this intended? This pull request now uses also `getZoom` for `GlyphMetrics.width`.
=> GlyphMetrics.width not properly scaled up

bundles/org.eclipse.swt/Eclipse SWT Browser/win32/org/eclipse/swt/browser/Edge.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_browser_Browser.java
Previously, the changed() method was not called consistently.
Move the firing of 'changed' LocationEvents in Edge from handleSourceChanged() to handleNavigationCompleted().
Fixes #1464.
=> Edge: Improve handling of LocationListener#changed()

binaries/org.eclipse.swt.gtk.linux.riscv64/META-INF/MANIFEST.MF
A blank after a header field is essential.
Fixes https://github.com/eclipse-platform/eclipse.platform.swt/pull/1445
=> Fix riscv64 MANIFEST.MF header field

bundles/org.eclipse.swt.tools.spies/META-INF/MANIFEST.MF, bundles/org.eclipse.swt.tools/META-INF/MANIFEST.MF
- Both need to be bumped because neither is signed by the latest available signing certificate.
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2335
=> Bump version to match jar signatures

.github/workflows/maven.yml
GitHub actions builds are currently failing because of invalid fragments in the classpath when compiling the SWT fragments after updating to Tycho 4.0.8. This change temporarily reverts the used Tycho verison in the GitHub Actions workflow to 4.0.8.
We are approaching M1 and several PRs that are intended to be merged for M1 are blocked by failing builds (see discussion in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2360). In order to unblock them, I would like to apply this temporary revert. I will provide a follow-up PR rolling back this temporary revert and also propose to merge that soon to move back to the current Tycho version and try to properly address the issue.
=> Temporarily revert to Tycho 4.0.8 for GitHub Actions builds

bundles/org.eclipse.swt/Eclipse SWT Browser/win32/org/eclipse/swt/browser/Edge.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_browser_Browser.java
This contribution fixes Edge browser for win32 to handle the deadlock issue during the instantiation of a new edge browser object amidst a webview callback.
The problem with webview is that it can't execute tasks simultaneously and all the requests are serialized. Hence, a new request to the webview inside its callback leads to a deadlock since, both the tasks wait for each other to execute. The solution is to schedule the Webview calls during the callback asynchronously and let the control in the callback move on.
contributes to #669 
* This implementation doesn't fix the evaluate calls during the webview callback and would be addressed in a separate issue.
- #1395 
- Change the method `org.eclipse.swt.browser.BrowserFactory.createWebBrowser` to: 
```java
WebBrowser createWebBrowser (int …
```
=> Fix Edge Browser Deadlock issue for instantiation during a WebView Callback

Jenkinsfile, binaries/org.eclipse.swt.gtk.linux.riscv64/META-INF/MANIFEST.MF, binaries/pom.xml
With command
```shell
mvn verify -DskipTests=true -Dnative=gtk.linux.riscv64
```
riscv64 artifact can be generated at `binaries/org.eclipse.swt.gtk.linux.riscv64/target/`
=> Build gtk.linux.riscv64 native SWT fragment

bundles/org.eclipse.swt/Build-SWT-native-binaries-for-running-platform.launch
This simplifies maintenance since the list of refreshed projects does not have to be kept in sync with the list of available native fragments.
It's already out-of-sync it wasn't updated when the Windows on ARM and Linux on RISC-V fragment were added recently.
=> Refresh entire workspace after Maven launch to build SWT binaries

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Control.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Display.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Shell.java
This contribution enforces displays to store x,y coordinates in point as the absolute pixels in the display coordinate system. while scaling the width and height to the points, following this the map methods are reimplemented to do the right conversion between the new display coordinate system and the coordinates within a control.
The top left coordinates of monitors (x, y) are stored in the absolurte pixels coordinate of the display to avoid any overlap of any monitor bounds on scaling down as per their zoom level, i.e., to locate the monitor for a point, we can easily skim and find which monitor it belongs to, hence confirming the zoom needed for scaling.
e.g.  Monitor A: 100 x 100 (zoom: 100%, x-coordinates: 0 - 100) - On scaling down: 0 - 100
Monitor B: 100 x 100 (zoom: 100%, …
=> Positioning shells correctly for multi zoom level

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_custom_StyledText.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_custom_StyledText_multiCaretsSelections.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_Tree.java
needs https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2368
=> use ScreenshotOnFailure TestWatcher

bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/layout/TabFolderLayout.java
Moving TabFolderLayout into SWT.
Fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/1317
This pr needs to be merged first and later https://github.com/eclipse-platform/eclipse.platform.ui/pull/2186
=> Moving TabFolderLayout into SWT.

README.md
Follow-up on https://github.com/eclipse-platform/eclipse.platform.swt/pull/1509, where the link was anticipated incorrectly.
=> [Oomph-Setup] Fix link to SWT setup badge

bundles/org.eclipse.swt/Eclipse SWT WebKit/gtk/library/webkitgtk.h
Adjust dlopened webkitgtk lib to the stable one as libwebkit2gtk-5.0.so.0 used till now is obsolete now.
=> [GTK4] Fix Webkit loading

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Widget.java
fix java.lang.NullPointerException: Cannot read the array length because "table" is null
As Widget.setData(Object) can be called with null argument even if KEYED_DATA is set.
=> Widget.getData: fix NPE

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Display.java
This commit moves the initialization of the thread DPI awareness into the creation method. It was done too late before which resulted in all calls do Display::messageProc being executed with the wrong DPI awarness if the thread dpi awareness differs from the process DPI awareness.
##How to test
1. Configure your execution javaw.exe to be started with system DPI awareness (https://www.eclipse.org/swt/faq.php#winexternalmanifestfile) :
<dpi1:dpiAware>true</dpi1:dpiAware>
<dpi2:dpiAwareness>system</dpi2:dpiAwareness>
3. Prepare a two monitor setup, e.g primary 100% and secondary 200%
4. Start the ControlExample with
5. Move the example to the **secondary** monitor
6. Change the zoom of the **primary** monitor
The shell will be …
=> [win32] Fix initialization of thread dpi awareness

bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/gtk4.c, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/gtk4.h, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/org/eclipse/swt/internal/gtk4/GTK4.java
This is a draft to make the GTK4.10 dialog compile with older GTK versions
FYI @ptziegler @akurtakov 
this is not complete but in case someone wants to pick it up I wanted to share my progress here, with this changes it actually compiles again now.
=> Make new GTK4 Dialog dynamic loaded for pre GTK 4.10

bundles/org.eclipse.swt/Eclipse SWT Browser/common/org/eclipse/swt/browser/Browser.java, bundles/org.eclipse.swt/Eclipse SWT Browser/common/org/eclipse/swt/browser/WebBrowser.java, examples/org.eclipse.swt.examples/src/org/eclipse/swt/examples/controlexample/BrowserTab.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_browser_Browser.java
This reverts commit 51b8d8f655c34c9a536a1694c2f8e6273c3c6d76. The API isLocationForCustomText is not needed for Browsers.
contributes to #213
=> Revert "Extend Browser API to check for custom text location"

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Display.java
This contribution protects the unintended usage of different zoom levels of different monitors in trasnlating the points and rectangles from control to display coordinate system when the isRescalingAtRuntime flag is disabled.
* Set your monitor setup like this: 
> Left Monitor: 200% Zoom, Right Monitor : 100% Zoom (Primary Monitor)
* Create this Snippet:
```java
public class TestSnippet {
shell.setText("Snippet Lol");
Text text = new Text(shell, SWT.BORDER);
text.setBounds(20, 20, 500, 30);
Button button = new Button(shell, SWT.PUSH);
button.setBounds(100, 80, 100, 30);
button.setText("Relocate");
button.addSelectionListener(new SelectionAdapter() { …
```
=> Guard monitor.zoom with isRescalingAtRuntime flag

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Menu.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Widget.java
This PR contributes to the following regression:
In a multi zoom setup (mine was left (primary 200%), right (secondary 175%) there is a regression (both with and without update on autoscale) in menus.
We need to treat Menus similar to Shells -> they are always positioned with an absolute value. Currently they are set with two different ways:
1. Old zoomed down location, e.g. in Widget::showMenu -> this still works
2. New zoomed location, e.g. Push menus like the Run configurations -> this will result in
however, the locations supplied to these methods are in display coordinate system and hence must be scaled with the right methods as reflected in the PR.
=> set Location of menu wrt Display coordinate system

bundles/org.eclipse.swt/Eclipse SWT Browser/win32/org/eclipse/swt/browser/Edge.java, bundles/org.eclipse.swt/Eclipse SWT PI/win32/org/eclipse/swt/internal/ole/win32/COM.java, bundles/org.eclipse.swt/Eclipse SWT PI/win32/org/eclipse/swt/internal/ole/win32/ICoreWebView2Profile.java, bundles/org.eclipse.swt/Eclipse SWT PI/win32/org/eclipse/swt/internal/ole/win32/ICoreWebView2_13.java, bundles/org.eclipse.swt/Eclipse SWT PI/win32/org/eclipse/swt/internal/win32/OS.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Display.java
Set ICoreWebView2Profile#put_PreferredColorScheme() based on the Eclipse theme, if this is dark.
The same way it is done in
Display.setData(USE_DARKMODE_EXPLORER_THEME_KEY, ...)
via
OS.SetPreferredAppMode(PreferredAppMode_...);
Fixes #1529
=> Edge: Inherit dark theme from Eclipse

bundles/org.eclipse.swt/Eclipse SWT PI/win32/org/eclipse/swt/internal/win32/OS.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Menu.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/MenuItem.java
Using gc to draw menu item, moving the responsibility from OS due to wrong scaling of menu bar horizontally in **Dark** Theme. Snippet 373 can be used to test menuItems with images. 
Additional points covered in this PR: 
- Changing the text color from a grayish tone to white.
- When ALT key is pressed mnemonics are underlined and work as a toggle, the behavior which was missing from dark theme previously.
Screenshot of the fix: 
- Run the `RunTimeWorkspace` with the following **VM Arguments**
```
```
- Go to "Windows" -> "Preferences" -> "General" -> "Appearance" 
- Change theme to "Dark" 
- Click "Apply and Close" 
- Move the window from 100 -> 175 (or anything 100+) zoom level
- See if menu bar is properly aligned. …
=> Drawing custom menu items for Menu Bar **Dark Theme Only**

bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/graphics/Resource.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Device.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Path.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Pattern.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Region.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Transform.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Control.java
This PR contributes to the cleanup of those handles of Resources which were created for the zoom levels which are not applicable for the existing zoom levels of all the monitor. i.e., if there were 2 monitors with 100% and 200% zoom levels and the seconds monitor is switched to 100% as well. On the DPI_CHANGED event, we trigger a cleanup of handles of the resources using the resource tracker to remove the handles which were created for 200% zoom level since there doesn't exist any monitor with a zoom level of 100% anymore.
With this PR, we also refactor the resource tracker to allow it to track all the resources for win32 all the time but rather using the tracking flag to report errors, since that is the only use case of the tracking flag as of now. By allowing the Resource Tracker to …
=> Destroy unused handles

.github/workflows/maven.yml
This is the first commit of https://github.com/eclipse-platform/eclipse.platform.swt/pull/1492.
It is extracted in order to reduce the number of changes simplify the search for problems.
=> [Build] Improve elements order in maven.yml and build with Maven 3.9.9

.github/workflows/maven.yml
Similar to https://github.com/eclipse-equinox/equinox/pull/677.
=> [Build] Replace use of coactions/setup-xvfb

bundles/org.eclipse.swt/Eclipse SWT PI/win32/library/os_custom.c
=> Win32: Update search for AllowDarkModeForWindowWithTelemetryId for 24H2

bundles/org.eclipse.swt/Eclipse SWT Browser/win32/org/eclipse/swt/browser/Edge.java
In the scenario
- System: Dark
- Eclipse: Light
we need to explicitly set
- Edge: Light
as well, as with the previous
- Edge: Auto
it would inherit 'Dark' from the system, which is not desired.
Follow-up on 4d61d1dfcc879911bcb361e1af25b08ef19ed88e / #1530.
=> Edge: Dark mode support: Use LIGHT instead of AUTO

bundles/org.eclipse.swt/Eclipse SWT Browser/win32/org/eclipse/swt/browser/Edge.java
With this contribution, Edge browser uses the workspace directory for the userdata directory for the separation of the usage of userdata directory per workspace by the webview2Environment.
Depends on https://github.com/eclipse-platform/eclipse.platform.ui/pull/2434
contributes to https://github.com/eclipse-platform/eclipse.platform.swt/issues/1013
=> Allow to configure Edge userdata directory via Display data

bundles/org.eclipse.swt/Eclipse SWT Browser/win32/org/eclipse/swt/browser/Edge.java
This contribution captures the hover over edge browser and sends a mouse move event to its listener.
contributes to https://github.com/eclipse-platform/eclipse.platform.swt/issues/1540
- Make sure your IDE is **not** using Edge as the default browser (at least until other issues have been solved)
- Start the _Runtime Workspace_ application with the start parameter `-Dorg.eclipse.swt.browser.DefaultType=Edge`
- Hover over some element (class name, method, etc) so that a JavaDoc pops up
- Move the cursor inside the JavaDoc pop-up --> The scrollbars and the navigation buttons should appear in the JavaDoc pop-up:
=> Add processing of mouse movements in Edge browser

bundles/org.eclipse.swt/Eclipse SWT PI/gtk/org/eclipse/swt/internal/gtk/OS.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Display.java
The static initializer in OS is calling "gdk_display_get_default()" via "isX11()" and therefore violates the requirement that "gtk_init()"/"gtk_init_check()" must be invoked before any other GTK+ function. While doing so works in GTK3, it is by no means a documented behavior, but rather something that works by pure chance [1].
With this change, the system property is moved from the initializer to the Display constructor, where the init function is explicity called. The change itself was made in an error being thrown while executing the JUnit tests on Wayland [2]. But because the display is created before those are executed, it shouldn't matter where this property is set.
[1] https://bugs.eclipse.org/bugs/show_bug.cgi?id=465863
[2] https://bugs.eclipse.org/bugs/show_bug.cgi?id=528968
=> [GTK4] SIGSEGV in OS.gdk_display_get_default() during splash screen

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Device.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Path.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Pattern.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Region.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Transform.java
Resources with zoom support are registered at their device so that handles for zoom levels that are not necessary anymore can be disposed. When these resources are destroyed, they are currently not de-registered form their device, potentially leading to resource leaks. This change makes the resources de-register themselves form their device when being destroyed.
Fixes regression from:
- #1477
Fixes https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/1752
=> [win] De-register resources with zoom support from device

bundles/org.eclipse.swt/Eclipse SWT PI/win32/library/os.c, bundles/org.eclipse.swt/Eclipse SWT PI/win32/library/os_custom.h, bundles/org.eclipse.swt/Eclipse SWT PI/win32/org/eclipse/swt/internal/win32/OS.java
This PR marks the following Win32 functions as _dynamic_:
- `OpenThemeDataForDpi`<sup>1</sup>
- `GetSystemMetricsForDpi`
- `GetThreadDpiAwarenessContext`
- `SetThreadDpiAwarenessContext`
- `SystemParametersInfoForDpi`
It's enough to make SWT run on Windows Server 2016, Windows Server 2012, and Windows 8.1.
The Java code that uses these functions **already checks** if the OS version is above the minimum required, so no actions should be taken there.
<sup>1</sup>Although the `OpenThemeDataForDpi` is [documented](https://learn.microsoft.com/en-us/windows/win32/api/uxtheme/nf-uxtheme-openthemedatafordpi) to be available since Windows Server 2016, it's not available there, or at least not in the LTS version.
Addresses and fixes #1252 and possibly many other issues related to running SWT apps …
=> Win32: Fix compatibility with Windows Server 2012, Windows Server 2016, and Windows 8.1

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/internal/ScalingSWTFontRegistry.java
This PR adapts the initialization of a new base system font in the ScalingSWTFontRegistry to ensure the correct zoom is set at initialization.
I am not aware of any real issue caused by a wrong zoom value, but not using the targetZoom here is a possible source of errors.
=> [win32] possible wrong zoom set for system font

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java
This commit adds a workaround for ImageDataProvider implementations that instantiate new Images inside the getImageData(zoom) implementation. This image can be instantiated with the wrong zoom in a multi zoom setting as Images still relay on the static zoom value in DPIUtil. This workaround should be replaced by a proper solution.
You can reproduce the behavior as follows:
1. Set up at least two monitors with different zoom values (e.g., 100% and 125%)
2. Start an Eclipse application with rescaling on runtime activated (and auto scale mode quarter).
3. Place the workbench window on the 100% monitor. Note: if you move it between both monitors now, the minimize/maximize icons will be rescaled correctly.
4. Move the workbench window from the 100% to the 125% monitor.
5. Change focus to …
=> [win32] workaround for ImageDataProvider implementation

bundles/org.eclipse.swt/Eclipse SWT Browser/win32/org/eclipse/swt/browser/Edge.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_browser_Browser.java
Browser tests were only executed for the default configuration of a system's browser using the SWT.NONE flag. Other configurations, such as using the Edge browser in Windows, were not tested.
This change parameterizes the browser tests to also allow executing them for Edge browser on Windows. Due to current issues with the tests in the CI, this change only adds the parameterization but does not add Edge as a parameter yet.
This prepares for finally activating automated tests for Edge browser and thus contributes to https://github.com/eclipse-platform/eclipse.platform.swt/issues/671
This is extracted from:
- #672
=> Parameterize browser tests to allow executing them for Edge browser #671

bundles/org.eclipse.swt/Eclipse SWT Browser/win32/org/eclipse/swt/browser/Edge.java, bundles/org.eclipse.swt/Eclipse SWT PI/win32/org/eclipse/swt/internal/ole/win32/COM.java, bundles/org.eclipse.swt/Eclipse SWT PI/win32/org/eclipse/swt/internal/ole/win32/ICoreWebView2BasicAuthenticationRequestedEventArgs.java, bundles/org.eclipse.swt/Eclipse SWT PI/win32/org/eclipse/swt/internal/ole/win32/ICoreWebView2BasicAuthenticationResponse.java, bundles/org.eclipse.swt/Eclipse SWT PI/win32/org/eclipse/swt/internal/ole/win32/ICoreWebView2_10.java
Differences to IE engine:
- Location attribute:
- IE does not provide the 'location' for the callback, so this has to be guessed from lastNavigateURL which does not work consistently, e.g. after an immediate Browser.setUrl();
- Edge does provide the 'location' information consistently
- When returning invalid credentials
- IE does not call the authentication handler again for further attempts
- Edge calls the authentication handler again and again. Keeping track of this is out-of-scope for SWT. There is no retryCount field or similar in the event. AuthenticationHandler implementations need to account for unbounded repetitive calls in case the server does not bail out.
Resolves #730.
=> Edge: Implement AuthenticationListener handling for BasicAuth

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/ExpandItem.java
When adding image larger than the header size in expand bar, it was drawn outside of the bar on the top. This was due to wrong calculation and mixing of points and pixels. 
- Go to ExpandBarTab class and set any larger image on item
```
```
- Switch to the tab "Expand Items"
- See if the image is within the bounds of the bar/header
**Before Fix:**
**After Fix:**
=> Images not aligned properly in Expand Bar

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Button.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Composite.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/ExpandBar.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/TabFolder.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Table.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Text.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Tree.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Widget.java
This commit changes all DPI dependent OS theme calls to use the native zoom instead of using the zoom adjusted by the swt.autoScale setting. This is neccessary, because theme dependent elements like the checkbox for a button will be drawn by the OS and must be calculated with the native zoom.
Fixes #1573
=> [win32] Always use native zoom for OS theme calls

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/ExpandBar.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/ExpandItem.java
When moving from one zoom level monitor to another zoom level (no matter what %), The expanded items and texts are not drawn at correct coordinates.
```
```
- Switch to the tab "Expand Items"
- Move the window from 200 to 100 zoom level monitor (Producible in any combination of zoom levels)
- See if the "expanded" items are aligned to correct coordinates
**Before Fix:**
**After Fix:**
Contributes to https://github.com/eclipse-platform/eclipse.platform.swt/issues/62 and https://github.com/eclipse-platform/eclipse.platform.swt/issues/127
=> Expand Bar is not scaled during DPI change

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Menu.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/MenuItem.java
- Remove MenuItem.index which is now unused.
- Remove unused MenuItem.MenuItem(Menu, Menu, int, int)
https://github.com/eclipse-platform/eclipse.platform.ui/issues/2483
=> For Menu.wmTimer use Menu.indexOf instead of MenuItem.index

.github/workflows/maven.yml, binaries/org.eclipse.swt.cocoa.macosx.aarch64/.settings/.api_filters, binaries/org.eclipse.swt.cocoa.macosx.x86_64/.settings/.api_filters
The Tycho version used in GitHub Actions workflow has been temporarily reverted to 4.0.8. This change switched back the Tycho version defined in the Tycho build itself.
Since recent PDE and Tycho changes that apply with this change of the Tycho version, the API filters for GCData and Display on MacOS are not necessary anymore and produce warnings due to being obsolete. Thus, this change also removes the according filters. The commit has been taken from as it semantically belongs to the Tycho version change (and is required to make the CI builds run successfully):
- #1478
<s>⚠️ This PR is supposed to be merged once the issue discussed in https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2360 and reproduced via https://github.com/eclipse-tycho/tycho/pull/4293 has …
=> Switch back GitHub Actions workflow to use current Tycho version

.github/workflows/maven.yml
As all build-maschines are now have libgtk-4-dev we should do the same for the github verification.
=> Install libgtk-4-dev

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Control.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Display.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Shell.java
While testing we noticed some **regressions**, that were introduced with the commits https://github.com/eclipse-platform/eclipse.platform.swt/commit/4f60cb68dbf10c060b323c360a939d7ecf879440 and https://github.com/eclipse-platform/eclipse.platform.swt/commit/7a04f7a6cf7eccda8681f6c59d8f5d4064004e24. These commits were focused on providing a proper point coordinate system when multiple zoom values are involved and _rescaling at runtime_ is active, **but** they also introduced behavioral changes when the _rescaling at runtime_ is **not** active.
There are mainly three possible approaches to handle this regression:
1. Properly rework the coordinate system to support multi zoom environments. This is not doable for the upcoming release, but should be done for the next release
2. Only revert …
=> [win32] Revert and adapt fix for coordinate system for rescaling scenario

bundles/org.eclipse.swt/Eclipse SWT Browser/win32/org/eclipse/swt/browser/Edge.java
This PR contributes to storing the edge instance on creation in the webenvironment record synchronously for the sake of the consistency of the record. Since the record can be read by the cookie manager for several purposes on client calls, we need to make sure the record is in a consistent state, i.e. Linking the Edge instances (completely initialized or not) to their webview environment in the create method (synchronously).
In the bug #1592 the error occurs because we wait for the browser to initialize before it can be added to the record. It is safe to add it synchronously in the record since, all the further API calls of Edge browser is guarded by waitForFutureToFinish method.
contributes to https://github.com/eclipse-platform/eclipse.platform.swt/issues/1592
=> Store Edge instance in Environemnt record sync-ly

bundles/org.eclipse.swt/Eclipse SWT Browser/win32/org/eclipse/swt/browser/Edge.java
=> Edge: Send out LocationEvents for #fragment navigation

README.md
This enhances the readme in the following ways:
- Use consistent markdown formatting throughout the document and change all headlines to title case
- Add a section on prototyping work for a single, OS-agnostic SWT implementation with links to the according prototype repositories (Initiative 31)
Fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/1580
=> Improve readme formatting and add information on Initiative 31 #1580

binaries/org.eclipse.swt.gtk.linux.aarch64/forceQualifierUpdate.txt, binaries/org.eclipse.swt.gtk.linux.ppc64le/forceQualifierUpdate.txt, binaries/org.eclipse.swt.gtk.linux.riscv64/forceQualifierUpdate.txt, binaries/org.eclipse.swt.gtk.linux.x86_64/forceQualifierUpdate.txt, binaries/org.eclipse.swt.win32.win32.aarch64/forceQualifierUpdate.txt, binaries/org.eclipse.swt.win32.win32.x86_64/forceQualifierUpdate.txt, bundles/org.eclipse.swt/forceQualifierUpdate.txt
Changes to ecj are for handling of switch on String.
See: https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2595
=> Updated bundles with comparator errors

Jenkinsfile, binaries/pom.xml, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/build.sh
Currently the GTK4 binaries are not build as part of the build, this has several drawbacks:
1) If anything is adjusted for GTK4 part it might break without notice 2) We have no GTK4 binaries by default
This enables *compilation* of the gtk4 parts to see at least everything can be compiled.
The following has to be checked:
=> Build GTK 4 binaries

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Decorations.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Display.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/TaskBar.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/TaskItem.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/TrayItem.java
This PR contributes to the refactoring of `Image` class for **win32**. 
The goal is to store more than just the `handle` of the image for each zoom level. To do that, a new private class is created (it's called `ImageHandle`) and an image contains one instance of this new class for each zoom level. The class contains the following fields:
- `handle` 
- `height`
- `width`
=> Refactor Image for storing ImageMetadata

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Cursor.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Control.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Shell.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Tracker.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Tree.java
Creating a map to provide different handle w.r.t the current zoom of the display. The method win32_getHandle provides the appropriate handle for the scaled image as per requested by the client.
- Run the `Snippet92` (Image) or `Snippet119` (Icon) with the following **VM Arguments**
```
```
- Run the example
- Move the mouse pointer to the window
- See if the mouse pointer is scaled to the current monitor zoom level. 
- Now move the window to another monitor with different zoom level (i.e. 200%)
- Move the mouse pointer to the window again
- See if the pointer still scaled correctly according to 200% zoom level
=> Non system cursors adaption to DPI scale changes

bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/internal/AsyncReadyCallback.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/internal/SyncDialogUtil.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/DirectoryDialog.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/FileDialog.java
This adds a new AsyncReadyCallback class which is used to handle the asynchronous execution of dialogs. The goal is provide a cleaner and more readable interface than what is currently available by SyncDialogUtil.
Note that this class currently simply wraps the call to SyncDialogUtil. But once all of the remaining dialogs (Color/Font/MessageDialog) have been migrated, it might make sense to remove this class entirely to avoid this additional indirection.
Follow-up to 2e61b4be73c51afe0264028534306fff874e2ea9
=> [GTK4] Cleanup execution of non-blocking dialog calls

Jenkinsfile
The image is just specified to inherit basic configuration from it and higher level images are not necessary.
Image description:
https://github.com/eclipse-cbi/jiro-agents/blob/b816db0ea7b1c4f574be1e8d28bd31dafa47f8d4/basic/README.md
=> [Build] Inherit basic config from 'basic' image for linux.x86_64 builder

bundles/org.eclipse.swt/Eclipse SWT PI/win32/org/eclipse/swt/internal/win32/OS.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/ColorDialog.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/FontDialog.java
Creating a separate UI thread to set the DPI Awareness context to use UNAWARE GDI scale before opening the either dialogs since windows has issues with dialog scaling in AWARE context
```
```
- Run the Runtimeworkspace
- Go to Window -> Preferences -> General -> Appearance -> Colors and Fonts
- Collapse **Basic** in the main window
- Double click on any option (to open either color or font dialog) 
- Move the dialog across multiple monitor 
- See if the dialog is scaling correctly on multiple zoom level monitors
**Case: Primary monitor 200%, Secondary monitor 100%**
100%: 
200%:
100%:
200%:
=> Scaling of Color/Font Dialog not working properly after DPI change

bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/DefaultContent.java, bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/StyledTextListener.java, bundles/org.eclipse.swt/Eclipse SWT Drag and Drop/common/org/eclipse/swt/dnd/DNDListener.java, bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Widget.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/widgets/EventTable.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/widgets/TypedListener.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Widget.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Widget.java
The class `TypedListener` is intended to be internal even if it's in a public package and because there were cases where it has to be used for custom widges it happened that it was still used. With the APIs introduced in https://github.com/eclipse-platform/eclipse.platform.swt/pull/1112 there are better solutions using only public APIs for the cases it was still used.
Together with https://github.com/eclipse-platform/eclipse.platform.swt/pull/1615 this is the continuation of https://github.com/eclipse-platform/eclipse.platform.swt/pull/1101#issuecomment-1995483340 to deprecate `TypedListener` for removal so that it can later be moved into an internal package to strengthen the statement that it's internal.
Eclipse Nebula also does not use 
- https://github.com/eclipse/nebula/pull/582
- …
=> Deprecate TypedListener for removal to make it strongly internal later

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Composite.java
This should cover the case that BeginBufferedPaint might fail.
=> #924 [Win32] Possible ERROR_GRAPHIC_DISPOSED error during painting

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Control.java
---
Drastically reduces the flickering when resizing embedded components by ignoring calls to `Control::setRedraw(boolean)` for controls with embedded children.
---
This PR contributes to fixing the flicker issue in SashLayout whenever an embedded app is present inside it. The fix disallows the setredraw on controls if they contain any embedded application as their descendant. There's an issue open https://bugs.eclipse.org/bugs/show_bug.cgi?id=558392 for a long time for the resizing of the sashlayout. The current way of performing layout on mouse move works fine for eclipse widgets by calling setRedraw to false which freezes the state of UI and performing a re-layout and then setting redraw to true leading to a smooth transition of the Sashlayout when its borders are dragged by mouse but …
=> Fix for Flickering in Embedded Apps

README.md
The FAQ has been migrated to .md and we should make it easier for users to find the SWT related entries.
=> Adding a link to the SWT FAQ in the "official" FAQ document

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java
This commit adapts the bounds calculation in Image to not create any handle, but use and scale the bounds of an existing handle if no handle for the desired zoom is available
Fixes #1639
=> [win32] No handle creation on Image::getBounds

bundles/org.eclipse.swt/Eclipse SWT Browser/win32/org/eclipse/swt/browser/Edge.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_browser_Browser.java, tests/org.eclipse.swt.tests/META-INF/MANIFEST.MF, tests/org.eclipse.swt.tests/pom.xml
=> Edge: Set focus after WebView2 initialization of runtime if necessary

binaries/org.eclipse.swt.cocoa.macosx.aarch64/.settings/.api_filters, binaries/org.eclipse.swt.cocoa.macosx.x86_64/.settings/.api_filters, binaries/org.eclipse.swt.gtk.linux.aarch64/.settings/.api_filters, binaries/org.eclipse.swt.gtk.linux.loongarch64/.settings/.api_filters, binaries/org.eclipse.swt.gtk.linux.ppc64le/.settings/.api_filters, binaries/org.eclipse.swt.gtk.linux.riscv64/.settings/.api_filters, binaries/org.eclipse.swt.gtk.linux.x86_64/.settings/.api_filters, binaries/org.eclipse.swt.win32.win32.aarch64/.settings/.api_filters, binaries/org.eclipse.swt.win32.win32.x86_64/.settings/.api_filters, bundles/org.eclipse.swt/Eclipse SWT Browser/common/org/eclipse/swt/browser/Browser.java, bundles/org.eclipse.swt/Eclipse SWT Browser/win32/org/eclipse/swt/browser/BrowserFactory.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/SWT.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Control.java, examples/org.eclipse.swt.examples/src/org/eclipse/swt/examples/controlexample/BrowserTab.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_browser_Browser.java
This change replaces Internet Explorer as the default browser used on Windows with Edge/WebView2.
Internet Explorer is progressively taken out of support while Edge/WebView2 and replace by Edge/WebView2. It provides a more future-proof browser integration capability for SWT on Windows, with better capabilities, performance, and development tooling support.
This change consists of the following:
- Introduce SWT flag SWT.IE to be used for Browser to create an Internet Explorer instance
- Adapt mapping of existing VM argument for default browser to map "ie" to new Internet Explorer flag and use Edge as default
- Make SWT Browser instantiate Edge on Windows by default, i.e., unless the flag SWT.IE is specified
- Adapt the SWT ControlExample to represent the SWT.IE flag and properly switch …
=> Use Edge/WebView2 as the default browser on Windows #1466

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Control.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Display.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Menu.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Shell.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Widget.java
This contributes extracts two different strategies to provide a consistent coordinate system in the win32 implemenentation for a single-zoom and a multi-zoom environment. The existing logic remains unchanged in this commit. It is only moved and consolidated in the new inner classes in Display. 
This PR fixes https://github.com/eclipse-platform/eclipse.platform.ui/issues/2595 as well
=> [win32] different coordinate system strategies

Jenkinsfile
"only issues that have been introduced in the current build are marked as new"
see https://www.jenkins.io/doc/pipeline/steps/warnings-ng/
fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/1648
=> Jenkinsfile: ignoreQualityGate:true #1648

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_browser_Browser.java
In `class Test_org_eclipse_swt_browser_Browser`.
=> Disable test_TabTraversalOutOfBrowser for IE

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_browser_Browser.java
It's really cumbersome to edit them while experimenting thus converting.
=> Convert Browser test strings to test blocks

bundles/org.eclipse.swt/Eclipse SWT Browser/win32/org/eclipse/swt/browser/Edge.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_browser_Browser.java
Browser tests were only executed for the default configuration of a system's browser using the `SWT.NONE` flag. Other configurations, such as using the Edge browser in Windows, were not tested.
This change parameterizes the browser tests to also execute them for the Edge browser on Windows. It also deactivates those tests for the Edge browser for which the implementation does (currently) not work. This allows to detect regressions when performing future changes to the Edge browser.
Fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/671
=> Execute browser tests for Edge #671

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_browser_Browser.java
=> Browser Tests: Try to stabilize test_TabTraversalOutOfBrowser

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java
This contribution adds a check for imageMetadata for handle in case there already exists an entry in the zoomLeveltoImageHandle map for a zoom level and it must throw an exception in that case.
=> Add exception to setImageMetadataForHandle

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java
This commit fixes an issue in the win32 implementation that returned invalid bounds for an icon in some scenarios. This was introduced with #1496 
- Install the XML editors from WTP 
- Update site: http://download.eclipse.org/webtools/repository/latest/
- Open any XML file with the **XML Editor**
It is not 100% reproducible, but should lead to an exception most of the times without this PR
=> [win32] fix invalid icon bounds

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_browser_Browser.java
=> Disable test_TabTraversalOutOfBrowser

bundles/org.eclipse.swt/Eclipse SWT PI/win32/org/eclipse/swt/internal/win32/OS.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Control.java
Add display change event triggered by display zoom changes, regardless of window presence on the monitor. 
When the zoom level is changed for a monitor where the window is not present, we still need to trigger the event to clear resources for the old zoom level on the non-active monitor.  
For example, if there are two monitors with zoom levels 100% and 200%, and the window is on the 200% zoom monitor, changing the zoom level of the 100% monitor to 150% should destroy the handles for the old 100% zoom level, as they are no longer needed.
=> Destroying unnecessary zoom level handles

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Display.java
This contribution adds a null check before assigning the coordinate mapper in the Device::init since it might already be assigned in coordinateMapper.
As of the current implementation, the MultiZoomCoordinateMapper is assigned to coordinateMapper (if rescalingAtRuntime is active) in setRescalingAtRuntime and then it is overwritten in Device:init and always reset to SingleZoomCoordinateSystemMapper which is not the intended behaviour.
Fixes #1686 
=> Add Null check before assigning coordinateMapper

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java
This contribution refactors the Image class to improve readability. The following refactoring have been done:
1. Encapsulating Image metadata, i.e. Handle, width, height and zoom information per zoom level.
2. Abstracting ImageProviders, i.e. ImageDataProvider, ImageFileNameProvider.
=> Refactor Image for Readability

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java
See https://github.com/eclipse-platform/eclipse.platform.swt/pull/1667#issuecomment-2556458475
=> Add check for provider

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_custom_StyledText.java
This commit adds a test for StyledText with fixed font metrics that led to a regression with #1610
=> Add test for StyledText with fixed font metrics

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_browser_Browser.java
Fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/1676
=> Increase max time to create Edge browser in tests.

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_browser_Browser.java
Contributes to
https://github.com/eclipse-platform/eclipse.platform.swt/issues/1564
=> Disable failing browser tests for Linux

bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/StyledText.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_custom_StyledText.java
fix split screen issue https://github.com/eclipse-platform/eclipse.platform.ui/issues/2142 by not setting StyledText#topIndex if the control has not the focus.
=> don't modify topIndex in handleTextChanged if control has not the focus

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_browser_Browser.java
The URL used for the `test_setUrl_Local()` browser test case currently only consists of a file path when provided via the `PLUGIN_PATH` environment variable, e.g., during I-Build test execution. Edge does, however, require a valid URL with an according protocol prefix. Currently, the drive prefix of the file path is erroneously treated as the protocol.
This change properly converts the path to a URL.
Fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/1670
Note that this change will not have any effect in the PR validation, but only in the I-Build test execution (or if locally executed with the `PLUGIN_PATH` variable specified. I locally executed the tests with that variable specified to validate that it works as expected.
=> Edge: correct URL to local resource in tests #1670

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/TextLayout.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_graphics_TextLayout.java, tests/org.eclipse.swt.tests/ManualTests/org/eclipse/swt/tests/manual/Issue184_CarriageReturnHandled.java
Corrected TextLayout to produce right number of lines when '\r\n' sequence comes.
Fixes #184
@sravanlakkimsetti 
@niraj-modi 
@merks 
Can one of you review this fix please.
=> Corrected TextLayout to produce right number of lines when '\r\n' sequence comes.

bundles/org.eclipse.swt/Eclipse SWT Browser/win32/org/eclipse/swt/browser/Edge.java, bundles/org.eclipse.swt/Eclipse SWT PI/win32/org/eclipse/swt/internal/ole/win32/COM.java, bundles/org.eclipse.swt/Eclipse SWT PI/win32/org/eclipse/swt/internal/win32/OS.java
There is currently only few handling for failures during initialization of an Edge browser / WebView instance. The Microsoft documentation provides further information on this, in particular:
- ERROR_INVALID_STATE indicates that multiple Edge instances with the same data folder but different environment options exist
- E_ABORT indicates an active abortion of the initialization process
- On any other non-OK return value than the above ones, the app should retry initialization of the instance
This change adds appropriate handling for these scenarios, consisting of uniform rollback logic when the initialization fails or is aborted and retry logic to make repeated creation attempts.
Contributes to https://github.com/eclipse-platform/eclipse.platform.swt/issues/1664
=> Edge: properly handle initialization failures and abortion

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Display.java, tests/org.eclipse.swt.tests.win32/JUnit Tests/org/eclipse/swt/tests/win32/widgets/Test_org_eclipse_swt_widgets_Display.java
Replacing all line breaks on windows with CrLf using regex, which is much safer.
Fixes #1557
=> Display.withCrLf() is producing wrong line breaks on Windows

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java, tests/org.eclipse.swt.tests.win32/JUnit Tests/org/eclipse/swt/graphics/ImageWin32Tests.java
This contribution helps retrieve the imageData for the requested zoom by searching for the zoom in the zoomToHandleMap followed by (if not available) scaling the handle at the zoom nearest to it while getting rid of only searching among the autoscaled zoom values.
=> Obtain ImageData for any requested zoom value, not only autoscaled values

bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/DPIUtil.java
The Windows-specific system property for activating monitor-specific scaling (or "rescaling at runtime") is currently only evaluated at application startup. With this change the property will be evaluated on every access, thus allowing to change the property at runtime.
=> Consider changes to system property for rescaling at runtime

bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/DPIUtil.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Display.java
The default auto-scale value is "integer"/"integer200", which makes everything in the UI except fonts not scale according to the actual native zoom value but according to a value rounded to 100 or 200. While most code performing adaptations to zoom considers this for a static zoom value applied to the whole application, it leads to hard-to-resolve issues when scaling every shell according to the current monitor's zoom.
Since that autoscale mode is complex and should be replaced by uniform scaling of everything (in particular when images are based on vector graphics that can sharply be rendered for every zoom factor) anyway, this is not to be supported by the monitor-specific scaling feature currently being introduced for Windows. With this change, that mode will thus be limited to …
=> [Win] Disallow autoscale mode "integer" for monitor-specific scaling

binaries/org.eclipse.swt.cocoa.macosx.aarch64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.cocoa.macosx.x86_64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.gtk.linux.aarch64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.gtk.linux.loongarch64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.gtk.linux.ppc64le/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.gtk.linux.x86_64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.win32.win32.x86_64/META-INF/MANIFEST.MF
Version bump for Backport fix : https://github.com/eclipse-platform/eclipse.platform.swt/issues/1546 to R4_31 maintenance branch done via PR https://github.com/eclipse-platform/eclipse.platform.swt/pull/1725
=> Version bump for backport fix to R4_31 maintenance branch

bundles/org.eclipse.swt/Eclipse SWT Drag and Drop/win32/org/eclipse/swt/dnd/ImageTransfer.java, bundles/org.eclipse.swt/Eclipse SWT PI/win32/org/eclipse/swt/internal/win32/OS.java, bundles/org.eclipse.swt/Eclipse SWT Program/win32/org/eclipse/swt/program/Program.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Display.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/TaskBar.java
In the previous implementation, according to the documentation, SHGetFileInfo retrieves a system icon at the primary monitor native zoom. It means if the primary monitor is 175%, the dimension of the icon will be 56 x 56 (considering the standard dimension of 16 x 16 at 100%). Previously, the Image::win32_new was used to create an image object by passing the handle. Since the support of multi zoom, we know that now an image can have multiple handles, each for a zoom level. Image::win32_new used to assign the handle to the image at DPIUtil::getDeviceZoom regarless of what zoom level the handle was created for (in our case primary monitor native zoom, e.g. 175%). And it used to do some calcultation what proportion of primary monitor zoom would be this assigned zoom of the image. In other …
=> Fixed Program Icon Scaling for Multi Zoom

bundles/org.eclipse.swt/Eclipse SWT PI/win32/library/os.c, bundles/org.eclipse.swt/Eclipse SWT PI/win32/library/os_custom.h, bundles/org.eclipse.swt/Eclipse SWT PI/win32/library/os_stats.h, bundles/org.eclipse.swt/Eclipse SWT PI/win32/org/eclipse/swt/internal/win32/OS.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Decorations.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Scrollable.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Shell.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Spinner.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Widget.java
AdjustWindowRectEx does not take DPI into account. So using AdjustWindowRectExForDpi and passing the zoom level to retrieve correct coordinates and scaling accordingly.
- Run the Runtime Workspace with the following VM Arguments on 200% monitor
```
```
- Add a class and create a **conditional breakpoint**
- Double click on Breakpoint to remove it
- Maximize the main IDE window
- The dialog will appear with the text cutoff
Replacing AdjustWindowRectEx in Decoration fixes the issue for dialogs but replacing all the non-dpi calls for AdjustWindowRectEx even though there is no visible difference (but slight difference in returned coordinates) right now but having it DPI dependent makes it consistent.
=> Text in Dialog was cutoff due to invalid use of AdjustWindowRectEx

bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/graphics/GCWin32Tests.java, bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/graphics/PathWin32Tests.java, bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/graphics/RegionWin32Tests.java, bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/graphics/TextLayoutWin32Tests.java, bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/graphics/TransformWin32Tests.java, bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/internal/DPITestUtil.java, bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/internal/DefaultSWTFontRegistryTests.java, bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/internal/PlatformSpecificExecutionExtension.java, bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/internal/ResetMonitorSpecificScalingExtension.java, bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/internal/ScalingSWTFontRegistryTests.java, bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/internal/WithMonitorSpecificScalingExtension.java, bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/widgets/ControlWin32Tests.java, bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/widgets/DisplayWin32Test.java, bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/widgets/WidgetWin32Tests.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/DPIUtil.java
Auto-scale related, Windows-specific tests are currently organized in a class hierarchy based on Win32AutoscaleTestBase. This leads to unnecessarily initialized objects (e.g., shells or displays without any need for a test) and the strict necessity to use activated monitor-specific scaling in actual tests or to revert the setup logic affecting that value by hand.
This change removes the Win32AutoscaleTestBase and moves the common test functionality into extensions (PlatformSpecificExecution, ResetMonitorSpecificScaling and WithMonitorSpecificScaling) as well as the utility class DPITestUtil.
This serves as a preparation for #1720.
=> Remove type hierarchy of Win32AutoscaleTestBase

bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/widgets/DisplayWin32Test.java, bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Display.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Display.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Display.java
The method Display#setRescalingAtRuntime() allows to activate the monitor-specific scaling mechanism on Windows. This must, however, actually be activated before the Display is instantiated, like it is done during the Display constructor execution if the system property for global activation of monitor-specific scaling is specified. In consequence, calling #setRescalingAtRuntime() does not take the full intended effect.
This change deprecates the method so that the system property needs to be set for proper initialization of the monitor-specific scaling functionality. It also adapts the according tests to the deprecation of
the API and alternatives to be used.
⚠️ #1728 has been added as a preparation for this
=> Deprecate insufficient Display#setRescalingAtRuntime() method

bundles/org.eclipse.swt/Eclipse SWT PI/win32/library/os_custom.c, bundles/org.eclipse.swt/META-INF/MANIFEST.MF, bundles/org.eclipse.swt/pom.xml
Back port fix : https://github.com/eclipse-platform/eclipse.platform.swt/issues/1546 to R4_23 maintenance branch
Eclipse is displaying errors indicating "Not properly disposed SWT resource" and encountering issues with CSS. As a result, the dark theme is not functioning correctly on the latest version of Windows.
Fix : https://github.com/eclipse-platform/eclipse.platform.swt/pull/1547Win32
Update search for AllowDarkModeForWindowWithTelemetryId for 24H2
=> Backport Fix AllowDarkModeForWindowWithTelemetryId to 4.23 maintenance branch 

bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/CTabFolder.java, bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/graphics/Image.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/graphics/ImageGcDrawer.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/TransparencyColorImageGcDrawer.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/graphics/Image.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java, examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet367.java, examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet382.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_graphics_Image.java
This PR adds a new interface to be used to provide dynamic drawing on GCs created with Images. It is mostly targeted at solving the following use cases:
```
Image image = new Image (display, width, height);
GC gc = new GC (image);
// draw on the gc
otherGc.drawImage(image, ...);
```
or in combination with a ImageDataProvider
```
return new Image(display, (ImageDataProvider) zoom -> {
Image image = new Image (display, width, height);
GC gc = new GC (image);
// draw on the gc
gc.dispose ();
final ImageData imageData = image.getImageData (zoom);
image.dispose();
return imageData;
});
```
Both use cases have the problem, that they do not work properly in a multi-zoom setting. Not properly working means that there will be a destructive up- or downscaling on the created image data in the …
=> Callback for dynamic drawing with a GC on images

examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet367.java, examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet382.java
Two snippets refer to an old signature of the ImageGcDrawer interface, leading to compilation issues. This change change adapts them accordingly.
=> Adapt Snippet367 and Snippet382 to ImageGcDrawer

bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/widgets/CoordinateSystemMapperTests.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/graphics/MonitorAwarePoint.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/graphics/MonitorAwareRectangle.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/graphics/Point.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/graphics/Rectangle.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/MultiZoomCoordinateSystemMapper.java
This PR contributes to the use of MonitorAware Points and Rectangles for the translation between points and pixels coordinates in the Display Coordinate System. Since the Display Coordinate System can have different scales (zoom) in different area, it is designed to be not continuous in the points coordinates. Hence when we manipulate the coordinates of a Point or a Rectangle object, it might end up in a region which is between the 2 monitors in the point coordinate system, which we consider a gap. So, we need the context of the monitor on which those points and rectangles were created in the first place to evaluate the scaling factor. If the context is not available or the coordinates were updated to an irrelevant value, a fallback method tries to evaluate the right monitor for the …
=> Use monitor-aware coordinates in multi-zoom coordinate system

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/TaskBar.java
This commit initializes the nativeZoom attribute of the taskbar. As TaskBar is not calling a super constructor setting this attribute will be zero and can lead to issues with Images created with a zero zoom factor.
This PR is providing a subset of the already open PR #1269 
contributes to #1742
@HeikoKlare have a look
=> [win32] Init nativeZoom for taskbar

bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/DPIUtil.java
Currently, AutoScaleMethod "nearest" is used by default, leading to jagged image scaling results. The method "smooth" is only used on GTK with a fractional scaling value not being a multiple of 100. The reason for not using "smooth" scaling on all platform was a bug regarding icon transparency that has long been resolved.
With this change, AutoScaleMethod "smooth" is used by default in fractional scaling scenarios (i.e., with deviceZoom not being an integer multiple of 100) and when using monitor-specific scaling on Windows. To still use "nearest" in these scenarios, it can be activated via system property.
The change has also been tested for GIFs that are only rarely used nowadays. In the screenshots below, the "JobFactory" view uses a GIF as its icon.
A better interpolation method was …
=> Use AutoScaleMethod "smooth" by default for fractional scaling

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/graphics/Image.java
The current implementation of the Image constructor accepting an ImageGcDrawer does initialize the image with the given width and height but extracts them from the image data being initialized with the ImageGcDrawer. This does not take the current device zoom into account properly, leading to images unexpectedly being rendered for 100% scaling while they are supposed to be used at 200% scaling.
With this change, images are properly initialized with the given width and height and using the according device zoom for the image data generation, leading to a sharp initialization also on 200% monitors.
Serves as a fix for the MacOS part of issue https://github.com/eclipse-platform/eclipse.platform.ui/issues/2740
https://github.com/user-attachments/assets/6014d1e6-dff9-40a6-b1c4-58bc14d58f21 …
=> [MacOS] Fix width/height of Images created via ImageGcDrawer

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Display.java, tests/org.eclipse.swt.tests.win32/JUnit Tests/org/eclipse/swt/tests/win32/widgets/Test_org_eclipse_swt_widgets_Display.java
Changing back to the old withCrLf coding. Regex is causing performance issues.
Furthermore, handling of mixed \n and \r\n is improved.
Fixes: #1718
=> [FIX] Change to old withCrLf for better performance

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Shell.java
The previous scaling with the monitor context in Shell:setBounds would already scale the height and width of the Shell with respect to the monitor on which it is going to be placed. In case there is a monitor change, the monitor will be scaled with respect to the target monitor twice, i.e. in Shell::setBounds and then on the dpi changed message, leading to the effects, such as, shrinking or expanding shells on drag and drop to a different monitor with different zoom.
This PR contributes fixes that by scaling the x,y (top left coordinate) with the context of the whole rectangle but still using the zoom of the Shell for scaling the width and height. In case there's a monitor change the width and height will be scaled with respect to the target monitor on DPI_CHANGED event. Otherwise, the …
=> Fixed Shell::setBounds scaling

bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Display.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Device.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/GC.java, tests/org.eclipse.swt.tests/pom.xml, tests/org.eclipse.swt.tests/test.xml
This contribution renames the internal strict mode flag in GTK from org.eclipse.swt.internal.gtk.enableStrictChecks to org.eclipse.swt.internal.enableStrictChecks and adds it to win32 to be used to check for correctly configured GCs for monitor-specific-scaling. The helps tracing invalid custom Drawables or GCs that are created with an invalid configuration.
=> Unify internal strict mode flag for win32 and gtk

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Canvas.java
This PR addresses render artifacts visible in StyledText with monitor-specific scaling enabled e.g. on 175% with quarter scaling mode. Reason is that scaling up all attributes of bounds separately can lead to rounding errors e.g. between y and height (one being scaled up, the other one not). Scaling them together as a rectangle solves this limitation.
Black lines appear, because for each four lines the y is scaled up (e.g. from 50.5 to 51), but the height was not scaled up (25.25 is always 25) -> one pixel is skipped each four  lines when drawing the background
The effect is usually only visible if multiple connecting background chunks are drawn, but the wrong values would be produced in all scenarios.
The same issue is probably hidden in other places as well, e.g. in GC when something …
=> [win32] Scale up bounds as rectangle in canvas

bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/graphics/GC.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/graphics/Image.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_graphics_GC.java
The GC provides a #copyArea() method that copies an area inside the surface of the GC to another area in the same surface. When using a surface directly created via the Cairo API (or with the GDK API on Wayland), this operation is broken.
When the source and target area are overlapping and the source is above-left of the target area, the source area will appear replicated in the target area, as Cairo does not perform any buffering but does a linewise/chunkwise write from the source area to the target area.
This change fixes the behavior of GC#copyArea() by explicitly making Cairo first pipe the copied area into an intermediate surface to be painted into the actual target area afterwards. It also removes the existing workaround in images that avoids the instantiation of a surface via the …
=> [GTK] Fix GC#copyArea() for overlapping source and target areas #1756

bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/CTabFolder.java, bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/CTabFolderRenderer.java
getDPI always returns the points for primary monitor and can produce faulty behavior. Replacing the logic to calculate the chevron font size. Visibly 70% size of the font used for CTabItem is now used. Also adjusting the indent and adding the ZoomChange event to trigger redraw during DPI change.
**NOTE: Needs to be tested on linux and macOS**
- Run the CustomControlExample with following arguments in 150% primary monitor
> -Dswt.autoScale.updateOnRuntime=true
> -Dswt.autoScale=quarter
- Change the tab to "**CTabFolder**"
- Change the Size to **100x100**
- Move the shell to other monitor with (100 or 200%) 
- The number along with chevron image should look fine.
- **Additional**: The tabs should be aligned correctly as well. 
Scenarios Tested yet:
Case 	    Quarter   no args
150 -> 100 	OK …
=> Calculate chevron size in CTabFolderRenderer without Device#getDPI()

bundles/org.eclipse.swt/Eclipse SWT PI/win32/library/os_custom.c
=> Win32: Update Validate_SetPreferredAppMode for Arm64 24H2

bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/graphics/RegionWin32Tests.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Region.java
This commit adresses possibly invalid result when using Region::intersects on a zoom not dividable by 100. Reason is that scaling up all attributes of the rectangle separately can lead to rounding errors. Scaling them together as a rectangle solves this limitation.
=> [win32] Fix scaling inside Region::intersect

bundles/org.eclipse.swt/Eclipse SWT Browser/win32/org/eclipse/swt/browser/Edge.java
This PR contributes to refactoring of all the webView* instances into a wrapper class WebViewWrapper for better encapsulation and fault proof initialization using a single future.
Contributes to https://github.com/eclipse-platform/eclipse.platform.swt/issues/669
=> [Win32] Summarize ICoreWebView2* instances in WebViewWrapper

bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/widgets/ControlWin32Tests.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Control.java
This commit unifies scale up results in Control::setBounds. With zoom values not dividable by 100 different result depending on using setBounds(Rectangle) or setBounds(int, int, int, int) were possible. Scaling the bounds always as rectangle solves this limitation.
=> [win32] Unify scaling inside Control::setBounds

bundles/org.eclipse.swt/Eclipse SWT Browser/win32/org/eclipse/swt/browser/Edge.java
For some recently added WebView interface retrievals, the according release operations on disposal are missing. This change adds them.
=> [Win32] Add missing releases of queried WebView interfaces

bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/gtk4.c, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/gtk4_stats.h, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/org/eclipse/swt/internal/gtk4/GTK4.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Shell.java
It might be possible that no (custom) titlebar is set for the newly created shell. In such a case, gtk_widget_measure() must not be called with the NULL handle, in order to avoid the following error:
> gtk_widget_measure: assertion 'GTK_IS_WIDGET (widget)' failed
Furthermore, the header is now retrieved via gtk_window_get_titlebar(), rather than assuming that it's the second child of the shell handle.
=> [GTK4] Fix GtkWidget warning when calculating initial shell bounds

bundles/org.eclipse.swt/Eclipse SWT Browser/win32/org/eclipse/swt/browser/Edge.java
The Edge implementation contains retry functionality according to the ICoreWebView2Environment documentation. After five retries, the initialization is aborted with an error.
In order to ease debugging of potential causes, this change adds the OS result of the last retry attempt to the error logged by the initialization abortion.
=> [Win32] Add OS result to failing Edge initialization after retries

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_browser_Browser.java
When executing tests for Edge, UI events are processed on teardown of the test (or more precisely on widget disposal) as there may still be resources related to the OS WebView component being cleaned up. The current implementation was only supposed to be used for testing purposes as an attempt to address non-deterministic timeouts in tests. However, the timeouts still occur and the current implementation is prone to break as it may never terminate when new events to be process arrive frequently.
This change simplifies the cleanup functionality to process UI events only once instead of looping it. This mitigates the risk of a long-running loop and reduces unnecessary complexity.
=> [Win32] Simplify cleanup after Edge test execution

bundles/org.eclipse.swt/Eclipse SWT Browser/win32/org/eclipse/swt/browser/Edge.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_browser_Browser.java
The Edge browser implementation currently spins the event queue without any possibility to escape in case no OS message or not the expected OS message to proceed occurs and is processed.
In order to avoid that operations called on Edge deadlock, this change introduces timeouts for OS event processing inside Edge:
- The existing processNextOSMessage() method is replaced with processOSMessagesUntil(condition) that spins the event queue until the condition is met or a timeout occurred
- CompletableFutures used for the queuing events on the WebView instance are extended to wake the display in order to avoid that the OS message processing is unnecessary sleeping until a timeout wakes it up
=> [Win32] Avoid blocking operations on Edge due to OS message processing

bundles/org.eclipse.swt/Eclipse SWT PI/win32/library/os.c
Whenever the os.c file is auto-updated (e.g., due to changes in the OS class), a change is generated that fixes an inconsistent formatting. This change updates the os.c file to incorporate that formatting fix.
=> [Win32] Correct wrong formatting in os.c

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java
This commit unifies the getBounds calculation for ImageDataProvider and ImageFileNameProvider by always scaling the bounds of an existing handle of an image, if the bounds for a different zoom are requested.
fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/1639
=> [win32] do not call getImageData on getBounds call

bundles/org.eclipse.swt/Eclipse SWT Browser/win32/org/eclipse/swt/browser/Edge.java
Edge compares the result of WebView initialization with an HRESULT created from a Windows error code via the HRESULT_FROM_WIN32 macro. The actual result in that initialization callback is a long while the HRESULT returned from the macro is represented as integer in SWT. The current comparison of long and integer does not take into account that the values are signed. In this specific case, the actual HRESULT to compare against is 2147947423 while the HRESULT_FROM_WIN32 macro returns the signed value -2147019873. The actual result needs to be converted into a signed integer as well, as otherwise it will be considered as 2147947423, thus never matching the expected HRESULT value.
This change converts the processed result into an integer to correct the comparison.
=> [Win32] Fix faulty HRESULT_FROM_WIN32 comparison in Edge

bundles/org.eclipse.swt/Eclipse SWT Browser/win32/org/eclipse/swt/browser/Edge.java
The WebView environment used for Edge manages a list of all currently used Edge instances inside an application. This data structure is modified at different places, which may be executed by different threads, such introducing a risk of race conditions on the unsynchronized data structure. In addition, when disposing a Display (such as at application shutdown), Edge instances are disposed in an according dispose listener. This can cause ConcurrentModificationExceptions as the listener iterates through the list of Edge instances and calls their disposal, which in turn removes the Edge instance from that list.
This change makes the data structure thread-safe and copy-on-write to avoid that ConcurrentModificationException occur when iterating over it while removing elements from it.
=> [Win32] Thread-safe modification of Edge instances

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Canvas.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Composite.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Control.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Scrollable.java
This commit unifies scale up results in different places. With zoom values not dividable by 100 scaling up via rectangle or scaling up all values separately can give different result. Scaling always as rectangle solves this limitation.
=> [win32] Unify up-scaling bounds using Rectangle

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_browser_Browser.java
The browser tests contain a setup method that, on Windows, creates an Edge browser before any test is executed in order to set up the WebView environment. Since the first Edge browser instantiation takes rather long at least in the GitHub actions test environment, the initialization is extended to wait for the browser being initialized.
=> [Win32] Correct WebView environment initialization in Edge browser tests

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_browser_Browser.java
Browser tests randomly fail during Jenkins execution because of too many opened file descriptors. The reason seems to be that the build uses parallel execution and Maven plugins executed for other bundles may have opened and closed file descriptors in parallel, which are erroneously taken into account by the browser tests evaluating the number of file descriptors left open after a test execution.
This change excludes open file descriptors for Maven artifacts used in parallel by other Maven plugins by not considering file descriptors with their path containing ".m2" or "target/classes".
Fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/1523
In previous logs, you find lists of analyzed file descriptor deltas like this:
```
11:06:00 …
```
=> [Linux] Fix random test failures of browser tests #1523

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_browser_Browser.java
2 tests for Edge were running for IE. This PR corrects that.
The GH Actions shouldn't show these tests running for IE. If you see something like this in the output then it's wrong:
```
Running Test_org_eclipse_swt_browser_Browser#test_Constructor_multipleInstantiationsInDifferentShells[browser flags: 524,288]
```
```
Running Test_org_eclipse_swt_browser_Browser#test_Constructor_multipleInstantiationsInDifferentThreads[browser flags: 524,288]
```
=> Skip some Edge test when testing IE

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_browser_Browser.java
Test case was executed for every browser on every OS and was unnecessarily restricted to Edge.
Revises https://github.com/eclipse-platform/eclipse.platform.swt/pull/1792
See https://github.com/eclipse-platform/eclipse.platform.swt/pull/1792#pullrequestreview-2590944929
=> Remove restriction of browser test to Edge

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_browser_Browser.java
This change replaces the "expected" parameter for specifying an exception to be thrown by a test method with the more fine-grained and JUnit-5-compatible usage of assertThrows.
=> Replace "expected" parameter in browser tests with assertThrows

bundles/org.eclipse.swt/Eclipse SWT Browser/win32/org/eclipse/swt/browser/Edge.java
This Pull Request introduces following behaviour in Edge browser:
- Encapsulates the ICoreWebView*::Release for all the different webView* instances in the WebViewWrapper in a method WebViewWrapper::releaseWebViews
- The futures complete exceptionally if there occurs a timeout at processOSMessagesUntil
- If the webViewWrapperFuture finishes exceptionally (during the initialization of webViews), there's a streamlined rollback of all the resources.
contributes to #1466 and [#2734](https://github.com/eclipse-platform/eclipse.platform.ui/issues/2734)
=> WebViewWrapperFuture handling on job termination timeout

Jenkinsfile
All other jar and html files are usually not of interest and just complicate the build archive and significantly increase its size.
=> [Build] Only archive the built native-fragment jars

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/GC.java
This commit adds a check to identify long running or misconfigured GCs that render in a different zoom as its creating drawable intended to. Only executes if strict checking is enabled.
=> [win32] strict check to identify long running GC

bundles/org.eclipse.swt/Eclipse SWT Program/win32/org/eclipse/swt/program/Program.java
This PR contributes to proper scaling of Program icon. Since, these icons are retrieved by OS.SHGetFileInfo which is System DPI-Aware, it returns the icon with zoom level of the primary monitor at application startup. Hence, for initialNativeZoom of the Image object to be created for the icon, the zoom retrieved from the DPI is considered.
fixes #1759
=> Program icon scaling using DPI

bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/graphics/ImagesWin32Tests.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java
Image initialized as SWT.ICON in `org.eclipse.swt.graphics.Image.Image(Device, ImageData, ImageData)` loses its "Icon" properties, i.e. type, mask etc., when handle for different zoom level is requested. This change adapts the initialization of the image when the handle is requested for image type SWT.ICON to preserve the properties. The unit test is added that was failing before the fix. You can also see it in action in the snippet provided below: 
```java
InputStream stream = ShellImageExample.class.getResourceAsStream("yourImage.png");
ImageData imageData = new ImageData(stream);
ImageData mask = imageData.getTransparencyMask();
Image icon = new Image(display, imageData, mask);
System.out.println("Icon Type = " + …
```
=> Image type SWT.ICON loses its type during re-scale

bundles/org.eclipse.swt/Eclipse SWT Browser/win32/org/eclipse/swt/browser/Edge.java
When waiting for initialization of the WebView2 component in the Edge implementation, OS messages are processed by peeking the queue and performing a display.readAndDispatch() in case a message is present. The call to OS.PeekMessage() does, however, already perform some processing of the messages. In fact, Edge is not supposed to process all kinds of OS messages at all (like paint or input events) but should rather only process the WebView2 initialization callback message, arriving as a posted OS message. This change thus limits the message peeking inside Edge to only process the message type PM_QS_POSTMESSAGE.
Fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/1789
=> [Win32] Make Edge only process relevant OS messages #1789

Jenkinsfile, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/build.sh, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/check_dependencies.sh, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/make_linux.mak
Build GTK3 support for linux x86-64 to maximize compatibility
Recently all SWT builds for Linux x86-64 have been done on a new Debian image. This leads to requiring such a new distro to be able to run SWT successfully.
This change builds GTK3 and common code on an older debian container to increase the range of versions we support. Only GTK4's key library, libswt-pi4-gtk*.so is shipped from a build on the new debian container.
We continue to build all of the natives on latest debian so we benefit from compiler warnings/errors and other such tooling.
As part of the build all .so files are checked to ensure their dependencies are as expected. In particular glibc version is checked for all symbols and all libraries are checked.
The version of glibc 2.14 was chosen as that is what the …
=> Build GTK3 support for linux x86-64 to maximize compatibility

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/internal/DPIZoomChangeRegistry.java
Issue: #62 and #127 
This PR changes the type of `DPIZoomChangeRegistry::dpiZoomChangeHandlers` from `TreeMap` to `ConcurrentSkipListMap` as at times there can be classes which can register their handlers amidst a DPI change event leading to concurrent read and write which can lead to a `ConcurrentModificationException`
1. A `ConcurrentModificationException` happens because while we are processing the DPI change and going over the loop:
```java
for (Entry<Class<? extends Widget>, DPIZoomChangeHandler> entry : dpiZoomChangeHandlers.entrySet()) {
Class<? extends Widget> clazz = entry.getKey();
DPIZoomChangeHandler handler = entry.getValue();
if (clazz.isInstance(widget)) {
handler.handleDPIChange(widget, newZoom, scalingFactor);
}
}
``` 
Some Classes which are getting loaded concurrently …
=> Make DPIZoomChangeHandlers concurrent R/W able #62

bundles/org.eclipse.swt/Eclipse SWT WebKit/gtk/org/eclipse/swt/browser/WebKit.java
hardware-acceleration-policy has always 2 values "always"(0) and "never"(1) as per https://webkitgtk.org/reference/webkitgtk/stable/enum.HardwareAccelerationPolicy.html thus value of 2 is no longer supported.
Fixes "(SWT:330330): GLib-GObject-CRITICAL **: 10:47:39.032: value "((WebKitHardwareAccelerationPolicy) 2)" of type
'WebKitHardwareAccelerationPolicy' is invalid or out of range for property 'hardware-acceleration-policy' of type
'WebKitHardwareAccelerationPolicy'" when running on GTK4. As GTK 4 is fairly different from GTK 3 where it was disabled in an effort to fix crash let's keep the default setting unless there is a problem that is fixed by disabling hardware acceleration.
=> [GTK4] Stop disabling Webkit hardware acceleration

bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Display.java
All GTK 4.x versions are supposed to be supported (for now) and printing a warning that version is too new when comparing with gtk 3.22.0.
=> [GTK4] Don't print version warning

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Table.java
This PR resets the Table::itemHeight to -1 on DPI change to make sure that TableItem's height is still managed by the OS as it can be changed by CDDS_SUBITEMPREPAINT callback and once it is changed to some value, it will always remain the same and not recalculated by the OS leading to inconsistent behaviour on different zooms.
- Start the OpenType Dialog on 100% monitor.
- Move to 150% monitor on the right side.
- A CDDS_SUBITEMPREPAINT callback is executed, changing table.itemHeight to some value from -1.
- Move it back to 100% monitor
- The Items have more height
- Move it to 250% monitor on the left.
- The items are too small.
Initially at 100%: 
After moving to 150% and back to 100%:
After moving to 250%:
With this PR, the shown behaviour is fixed.
contributes to …
=> Reset Table::itemHeight on DPI change #62

bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/StyledText.java, bundles/org.eclipse.swt/Eclipse SWT Printing/win32/org/eclipse/swt/printing/Printer.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Device.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Font.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/internal/ScalingSWTFontRegistry.java
getDPI always returns points for primary monitor and can produce faulty behavior. Printing the code is broken because Printer DPI (400) is different from the Monitor DPI (100). Now we compute points from the zoom level instead of currentFontDPI.
1.  Run the runtime Workspace
2.  Move the shell from 100% primary monitor to 200% secondary monitor
3. Press Ctrl + P 
4. Save the preview as pdf
5. See if the code is printed with correct formatting.
=> Calculate Scaling for Font without Device#getDPI() 

bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Display.java
The handling of expose events has been internalized with GTK4 making it impossible to e.g. invalidate an area of a surface. Furthermore, the native method that are called no longer exist in GTK4, leading to an UnsatisfiedLinkError.
From the documentation:
Application and widget code should not handle expose events directly; invalidation should use the GtkWidget API, and drawing should only happen inside GtkWidget::draw implementations.
Closes https://github.com/eclipse-platform/eclipse.platform.swt/issues/1794
=> [GTK4] Stop handling expose events directly

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Device.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Font.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/internal/ScalingSWTFontRegistry.java
With commit cd8bb13 we adapted the calculation how to scale up fonts to fix the calculation for fonts used by the Printer. This introduced an issue if monitor-specific scaling is active and the primary monitor zoom is changed, because two different calculation were mixed now. This commit fixes this inconsistency.
- Activate the experimental monitor-specific scaling flag
- Open a text editor
- change the primary zoom
Some fonts will be scaled by the wrong factor
@HeikoKlare Can you have a look
=> [win32] fix to use zoom dpi for fonts via display

bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/DPIUtil.java
Smooth scaling is used if:
- (in Windows) Monitor-specific scaling is active
- (in Linux) if the zoom level of the monitor is not divisible by 100
- (in Mac) never
In Linux, once the mode changes to smooth, it stays in smooth.
- One 100% monitor and another in a "fractional" zoom _e.g._ 150%
- Start the `ControlExample` with the following VM parameters:
```
```
- (Linux) Drag the application back and forth between monitors
The `autoScaleMethod` should **always** be set to `SMOOTH` (in `org.eclipse.swt.internal.DPIUtil.setDeviceZoom(int)`)
- If the application starts in the monitor with the "non fractional" zoom level (_e.g._ 100% or 200%) then the mode should be `NEAREST`
- The `autoScaleMethod` should be set to `SMOOTH` when starting at/switching to a …
=> Allow smooth scaling for 100% monitors too

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Display.java
This commit resets the DPI awareness for the WH_MSGFILTER hook, if called. For performance reasons that is only done, when runAsyncMessages will be triggered, as this can cause UI updates, which would be executed with the wrong DPI awareness context and cause UI glitches.
Have monitor specific scaling active and at least two monitors.
1. Open an IDE opened on a primary monitor with a low zoom (e.g. 100%)
2. Open a Java File in the Editor
3. Move the IDE to a secondary monitor with a higher zoom (e.g. 200%)
4. Use the vertical scrollbar to scroll up and down and you should see an effect, e.g. on the LineNumberRuler
https://github.com/user-attachments/assets/13a8e84a-5edf-4eaa-9b92-e9684b6e5a03
=> [win32] Refresh thread dpi awareness on hooks

bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/CTabFolder.java
This commit addresses rendering fragments that can occur when the background images of CTabFolder will be scaled with the monitor-specific scaling active in win32. Using the ImageGcDrawer to redraw the images on demand for the correct zoom removed the fragments.
Activate monitor-specific scaling
Open the IDE on a monitor with 125%
Move the IDE to a monitor with 150%
You will see some fragments in the CTabFolders
=> Use ImageGcDrawer for bgimages in CTabFolder

bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/gtk4.c, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/gtk4_stats.h, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/org/eclipse/swt/internal/gtk4/GTK4.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Composite.java
Regardless of which control are given as input parameters, the controls are currently always added as last child to their parents. Underlying issue seems to be that the swt_fixed_restack() method does not handle the GTK4 widgets correctly. As a solution, perform the movement using the proper API.
To understand the combination in which GTK methods need to be called, consider the expected behavior based on the GTK and SWT documentation:
[GTK4 Documentation]
- gtk_widget_insert_after(widget, parent, previous_sibling)
It will be placed after previous_sibling, or at the beginning if previous_sibling is NULL.
- gtk_widget_insert_before(widget, parent, next_sibling)
It will be placed before next_sibling, or at the end if next_sibling is NULL.
[SWT Documentation]
- moveAbove(control)
Moves the …
=> [GTK4] Implement correct moveAbove()/moveBelow() control behavior

bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/DPIUtil.java
Enabling the smooth scaling for icon produce erroneous result. Resulting in icon losing its transparency.
Use the snippet to see the difference in behavior of the Image and Icon during the DPI change. 
```
shell.setText("Image and Icon Example");
shell.setLayout(new RowLayout());
Image icon = display.getSystemImage(SWT.ICON_WORKING);
InputStream is = ImageExample.class.getResourceAsStream("eclipse.png");
Image image = new Image(display, is);
new Label(shell, SWT.NONE).setImage(icon);
new Label(shell, SWT.NONE).setImage(image);
shell.pack();
shell.open();
while (!shell.isDisposed()) {
if (!display.readAndDispatch()) {
display.sleep();
}
}
display.dispose();
```
- Run the snippet with -Dswt.autoScale.updateOnRuntime=true
- …
=> Guard Image Type Icon from Smooth Scaling

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Decorations.java
Setting an image for a shell on top left disappears on monitor change in monitor specific scaling mode. The reason behind it was that the image was being disposed by setImages method called after setImage in handleDPIChanged. The setImages method should not have been called if there are no images present in the array. The solution is to check whether we have any images in the in the array with the null check.
- Run the following snippet with the following arguments
```
```
```
Image image1 = display.getSystemImage(SWT.ICON_WORKING);
shell.setText("My Snippet");
shell.setImage(image1);
shell.open();
while (!shell.isDisposed()) {
if (!display.readAndDispatch()) { …
```
=> Shell Icon disappears on zoom change

.github/workflows/maven.yml
This is a different approach to
- https://github.com/eclipse-platform/eclipse.platform.swt/pull/1663
this should reuse the usual workflow, but set the `GTK4=1` when the PR is created with the gtk4 label ... as Jenkins is still running with gtk3 we still check both ways.
=> Run the Github verification with GTK4 enabled if it has GTK4 label

bundles/org.eclipse.swt/Eclipse SWT Browser/win32/org/eclipse/swt/browser/Edge.java
With Edge, just as IE did, supports opening new windows on its own, unlike the WebKit implementation on Linux/macOS.
Therefore, to maximize compatibility with IE as the previous default, also let WebView2 handle opening new windows by default.
Fixes #1845.
=> Edge: Let WebView2 handle opening new windows by default

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Control.java
This PR fixes the check for enabling and disabling the redraw of controls in a sashlayout which leads to a shaky sashlayout on resizing it.
contributes to
=> Fix Sash Layout Shaking in win32 #62

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Caret.java
This PR fixes caret rescaling by making sure the the field height is updated for every caret and Caret::resize is called for those carets where applicable.
contributes to
This is my configuration and how I reproduce the error in my current Eclipse IDE.
- Activate _Monitor-specific UI scaling_ either via the preferences (`General > Appearance`) or by using the flag `-Dswt.autoScale.updateOnRuntime=true`
- 125% monitor on the left (primary)
- 175% monitor on the right
- Open editor, click somewhere -> caret appears
- Move to the other monitor -> caret broken: it's in the wrong position and has the wrong size
In this …
=> Fix Caret Rescaling for win32 #62

binaries/org.eclipse.swt.cocoa.macosx.aarch64/.settings/.api_filters, binaries/org.eclipse.swt.cocoa.macosx.aarch64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.cocoa.macosx.x86_64/.settings/.api_filters, binaries/org.eclipse.swt.cocoa.macosx.x86_64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.gtk.linux.aarch64/.settings/.api_filters, binaries/org.eclipse.swt.gtk.linux.aarch64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.gtk.linux.loongarch64/.settings/.api_filters, binaries/org.eclipse.swt.gtk.linux.loongarch64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.gtk.linux.ppc64le/.settings/.api_filters, binaries/org.eclipse.swt.gtk.linux.ppc64le/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.gtk.linux.riscv64/.settings/.api_filters, binaries/org.eclipse.swt.gtk.linux.riscv64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.gtk.linux.x86_64/.settings/.api_filters, binaries/org.eclipse.swt.gtk.linux.x86_64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.win32.win32.aarch64/.settings/.api_filters, binaries/org.eclipse.swt.win32.win32.aarch64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.win32.win32.x86_64/.settings/.api_filters, binaries/org.eclipse.swt.win32.win32.x86_64/META-INF/MANIFEST.MF, bundles/org.eclipse.swt/META-INF/MANIFEST.MF, bundles/org.eclipse.swt/pom.xml
Also removes obsolete API filters for previous version
=> Version bump for 4.36 stream

bundles/org.eclipse.swt/Eclipse SWT Accessibility/gtk/org/eclipse/swt/accessibility/AccessibleObject.java
GTK 4 port crashes on start up if worspace chooser has to be shown as AccessibleObject is totally disfunctional on GTK 4.x version but later on it tries to send events.
Disable it for now.
=> Stop crash of AccessibleObject on GTK 4

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Display.java
This fixes wrong formatting introduced to the Win32 display class in https://github.com/eclipse-platform/eclipse.platform.swt/pull/1722
=> Correct formatting of Win32 Display class

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/GC.java
This commit adresses render artifacts visible when drawing on a GC with monitor-specific scaling enabled e.g. on 175%. Reason is that scaling up all attributes of bounds separately can lead to rounding errors e.g. between y and height (one being scaled up, the other one not). Scaling them together as a rectangle solves this limitation.
<s>This PR is not yet meant to be merged, it should be used to test different scenarios where the GC is involved on uneven zoom settings like 125% or 175%.</s>
=> [win32] Scale up bounds as rectangle in GC

bundles/org.eclipse.swt/Eclipse SWT PI/win32/org/eclipse/swt/internal/win32/OS.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Control.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Group.java
Resolves #373.
I came up with this solution with some google research. It seems to work well, but I'm quite clueless about those Win32 APIs, so would be great if a Win32 expert could help out here.
=> [Win32] Use PrintWindow() with PW_RENDERFULLCONTENT flag

bundles/org.eclipse.swt/Eclipse SWT PI/common/org/eclipse/swt/internal/Library.java
After this pr change :
From now on swt-win32-4969r0 followed by swt-win32-4969r1 and so on should come.
Before this pr
It was swt-win32-4969 followed by swt-win32-4969r1 and so on.
@HeikoKlare 
This is done. Thank you for your opinion(as i was also on the same) to do this change in a different pr.
=> Independent of initial version, revision version needs to be appended.

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_Combo.java
Checks existing behavior which seems to be a de-facto API _i.e._ that calling `getSelectionIndex()` during a modification event returns the up-to-date selection index.
=> Add test to Combo

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Decorations.java
Windows only: wse the original width and height of the images set to the shell when searching for the best fit instead of adapting them to the zoom, otherwise the smallest image will always be picked and it will result in a blurry shell icon when scaling up for monitors with a higher zoom levels.
contributes to
- Start the _Runtime Application_ with **Monitor-specific UI scaling** active
- Move it to a 200% monitor: the shell (window) icon should look sharper
**Before this PR**
**After this PR**
~**Yes**~ Sort of (one needs to activate the experimental feature _Monitor-specific UI scaling_ in order to experience this behavior), introduced when we …
=> Fix blurry shell icon #62

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Transform.java
This adapts Transform in the win32 implementation to create handles only on demand. If a non-handle specific operation like isIdentity() is called, a temporary handle will be created and disposed afterwards if no handle exists already.
It contains the branch used for #1858 and is a second refactoring on transform, there it must be merged after #1858
=> [win32] Dynamic handle creation for transform

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/graphics/Region.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/graphics/Region.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Region.java
This PR removes the obsolete equals and hashCode methods for Region. For the upcoming changes for win32 the current implementation cannot be used anymore because all handles will be created on demand. As the current implementation is equal in their behavior to the base behavior for these methods inherited from Object they will be removed.
=> Remove obsolete hashCode/equals for Region

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/graphics/Image.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_graphics_Image.java
When running with a device zoom of 200, the bounds of images created with an ImageGcDrawer have double the expected size. The reason is that the image is initialized with image data at zoom 200, from which also the width and height are retrieved. The used initialization logic does, however, always expect image data at zoom 100 to be passed.
This change fixes the initialization of images based on ImageGcDrawer to create both the 100 and 200 image data version and correctly initialize the image metadata with the former. The according test case is extended to validate the bounds in pixels of images not only against the bounds if the image but also against the expected/initial bounds.
This API was introduced with the previous release and is yet only used for minimize/maximize icons of part …
=> [MacOS] Fix getBounds for Image based on ImageGcDrawer

bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/DPIUtil.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java
In some image constructors, image data are currently auto-scaled. This works by accident, as the device zoom used for auto scaling conforms to the zoom of the image to be initialized.
However, to make this explicit, with this change the proper zoom is passed to scale method. It also makes the autoScaleUp method in DPIUtil obsolete and removes it.
This supcedes
- #1867
which migrated to a different but likely inaccurate autoScale operation.
Required to keep changes in https://github.com/eclipse-platform/eclipse.platform.swt/pull/1828 simple.
=> [Win32] Replace autoScaleUp of ImageData with proper scaleImageData

bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/gtk4.c, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/gtk4_stats.h, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/org/eclipse/swt/internal/gtk4/GTK4.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Combo.java
Method getCaretPosition is implemented with Gtk 4. The other method getCaredLocation is simply bypassed on Gtk 4 with TODO to prevent the crash for now.
=> Fix Combo crash with Bug379271_ComboCaretLocationOffset on Gtk 4

bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/graphics/RegionWin32Tests.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Region.java
This PR refactors Region in the win32 implementation to better support multiple handles for different zoom settings by creating all handles only on demand. It applies the same patterns as #1856 and #1858
=> [win32] Adapt Region to support creation of handles with operations with disposed resources

bundles/org.eclipse.swt/Eclipse SWT PI/win32/library/os.c, bundles/org.eclipse.swt/Eclipse SWT PI/win32/library/os_custom.h, bundles/org.eclipse.swt/Eclipse SWT PI/win32/library/os_stats.h, bundles/org.eclipse.swt/Eclipse SWT PI/win32/org/eclipse/swt/internal/win32/OS.java
This PR adds the OS call for GetDpiForWindow.
=> [win32] add GetDpiForWindow OS call

bundles/org.eclipse.swt/Eclipse SWT PI/win32/library/os.c, bundles/org.eclipse.swt/Eclipse SWT PI/win32/library/os_stats.h, bundles/org.eclipse.swt/Eclipse SWT PI/win32/org/eclipse/swt/internal/win32/OS.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Display.java
This PR contributes to better scaling of Images obtained from Display::getSystemImage using better windows API LoadIconWithScaleDown for scaling. The new API also changes the old system icons to the modern Windows System Icons.
The idea is to have an ImageDataProvider for such Images which retrieve the image from the OS for the specified dimensions relevant to the zoom level and obtain its imageData instead of scaling the ImageData obtained from the handle of initialNativeZoom.
Standard Icons loaded using LoadImage (using user32.dll): 
Standard Icons loaded using LoadIconWithScaleDown (using imageres.dll):
Contributes to
=> Improve scaling of SystemImage #62

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java
Images based on ImageFileNameProvider and ImageDataProvider are initialized with data based on the default zoom and can later on be reinitialized with data for others zooms when `getImageData()` is called. At both places, the same functionality is implemented twice.
This change makes the initial creation of image data use the already existing implementation for reinitializing it for another zoom. It also unifies the previous two implementations and removes obsolete calls to init() which are just required once for starting resource tracking.
Required to keep changes in https://github.com/eclipse-platform/eclipse.platform.swt/pull/1828 simple.
=> [Win32] Combine duplicate initialization logic for image from providers

bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/graphics/GCWin32Tests.java, bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/widgets/ControlWin32Tests.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Control.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Shell.java
This commit adds a fallback mechanism if the OS doesn't send a DPI change as expected. When the process is started with System DPI awareness and only the thread is PerMonitorV2 aware, there are some scenarios, when the OS does not send a DPI change event when a child Shell is positioned and opened on another monitor as its parent Shell. To work around that limitation a check is added to Shell::WM_WINDOWPOSCHANGED to trigger a dpi change event if an unexpected DPI value is detected.
This PR needs #1862 to be merged before
**Important for testing:** You will **not** run into the handleMonitorSpecificDpiChange in Shell::WM_WINDOWPOSCHANGED when testing this PR on runtime. To me this scenario only appears, when starting the RCP from the Explorer (e.g. **not** a command prompt!)
=> [win32] fallback for missing DPI change event

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/graphics/InternalImageLoader.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/graphics/ImageLoader.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/image/FileFormat.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/image/GIFFileFormat.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/image/JPEGFileFormat.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/image/OS2BMPFileFormat.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/image/PNGFileFormat.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/image/TIFFFileFormat.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/image/WinBMPFileFormat.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/image/WinICOFileFormat.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/graphics/InternalImageLoader.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/InternalImageLoader.java
Required for
- https://github.com/eclipse-platform/eclipse.platform.swt/pull/1638
This is a purely internal change that also reduces the number of places where `IOExceptions` are handled (all int the same way) in `FileFormat.isFileFormat()` implementations.
@HeikoKlare do you want to review this? Should we aim to land this for this release?
CC @Michael5601
=> Prepare the implementation of dynamically sized image file-formats

bundles/org.eclipse.swt.tools/META-INF/MANIFEST.MF, features/org.eclipse.swt.tools.feature/feature.xml
I missed that in
https://github.com/eclipse-platform/eclipse.platform.swt/pull/1894
=> Version bump for new stream

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Path.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/AllGraphicsTests.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_graphics_Path.java
This commit adapts Path in the win32 implementation to create handles only on demand. If a non-handle specific operation like getBounds() is called, a temporary handle will be created and disposed afterwards if no handle exists already.
It contains the branch used for https://github.com/eclipse-platform/eclipse.platform.swt/pull/1856 and is a second refactoring on transform, there it must be merged after https://github.com/eclipse-platform/eclipse.platform.swt/pull/1856
=> [win32] Dynamic handle creation for Path

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/graphics/Image.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/graphics/ImageData.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/graphics/ImageDataLoader.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/graphics/Image.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java
This was originally part of and has been extracted out of https://github.com/eclipse-platform/eclipse.platform.swt/pull/1828 in order to separate preparatory work in the `FileFormat` and `ImageLoader` implementations for their adoption in the OS-specific image classes.
This adopts the zoom-aware `ImageLoader` methods added in https://github.com/eclipse-platform/eclipse.platform.swt/pull/1828 in the `Image` implementations.
<s>⚠️ This currently contains the commit of https://github.com/eclipse-platform/eclipse.platform.swt/pull/1828 and should thus be merged after that PR.</s>
=> Adopt usage of zoom-aware ImageLoader methods in Image class

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/FontDialog.java
This PR removes the usage of OS.LOGPIXELS* in FontDialog. These values can be obtained using other means as the OS.LOGPIXELS provides the dpi values of the primary monitor at the app-startup time. It's usage has been replaced by passing the zoom directly in FontDialog::open method.
contributes to
=> Extract LOGPIXELS* usage to FontDialog::getDPI

bundles/org.eclipse.swt/Eclipse SWT PI/win32/library/os.c, bundles/org.eclipse.swt/Eclipse SWT PI/win32/library/os_stats.h, bundles/org.eclipse.swt/Eclipse SWT PI/win32/library/os_structs.c, bundles/org.eclipse.swt/Eclipse SWT PI/win32/library/os_structs.h, bundles/org.eclipse.swt/Eclipse SWT PI/win32/org/eclipse/swt/internal/win32/OS.java, bundles/org.eclipse.swt/Eclipse SWT Program/win32/org/eclipse/swt/program/Program.java
This PR contributes to the improvement in the scaling of program icons. The implementation uses a windows API SHGetImageList to obtain imagelists at small, large and extra large sizes. Then the icon nearest to the required size is retrieved and its image data is scaled up returned.
Typically the small, large and extra large icons are supposed to have 16, 32 and 48 px of sizes respectively. But apparently, the API SHGetImageList turns out to be System-DPI aware. It means if the primary monitor zoom at app startup was 100% then those scaled values are valid but for instance if it was 200% then the sizes from small, large and extra large would be 32, 64 and 128 px. Hence, with this approach we do get a room to scale up with better image quality since, the retrieved images are usually, 1x, 2x …
=> Improve Program Icon Scaling

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_browser_Browser.java
Improve assertions in browser test case `test_setTextContainingScript_applicationLayerProgressListenerMustSeeUpToDateDom` to avoid further test execution when expected conditions have not been fulfilled before.
Contributes to:
- https://github.com/eclipse-platform/eclipse.platform.swt/issues/1843
=> Improve assertions for browser test #1843

bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/graphics/Image.java
A previous change unified the Image surface initialization for blank Image instances just based on height and width. Because of the change, screen capturing using a GC on the display does only work properly when executed the first time in an application lifecycle and in specific situation, the initial properties of a GC changed (such as the text anti-aliasing behavior). Due to a lack of a better solution for now, this change reverts the unification of the Image surface initialization to the previous state.
Fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/1891
This partially reverts commit 5c2611d677f45fe2c19cd84d4274ab7ca6dd1350.
Supercedes and thus closes #1835
Supercedes and thus closes #1839
=> [GTK] Revert unification of blank Image initialization #1891

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Display.java
- See https://github.com/eclipse-platform/eclipse.platform.swt/issues/1814
=> [Mac] Fix ClassCastException when selecting a color in FontDialog

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Region.java
This PR refactors Region in the win32 implementation to better support multiple handles for different zoom settings by creating all handles only on demand.
=> [win32] Dynamic handle creation for Region

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java
This PR refactors the Image constructor using width and height to create a bitmap to create the handles always on demand instead of creating its first handle in the constructor.
=> [win32] Create image handles on demand for width/height based constructors

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Cursor.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java
This PR refactors Image#init for ImageData in the win32 implementation. Currently this method serves two purposes: 
1. creating handles for the given ImageData 
2. Doing 1. but additionally initializing an image with those handles
These two use cases are made more explicit refactoring this logic out into concrete methods. This is a necessary refactoring to be able to create all OS handles on demand and create temporary OS handles if neede.
=> [win32] refactor Image::init with ImageData

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java
Initializing image handle only using initNative method for both the cases where zoom is equal to the filezoom and when its not equal to the filezoom. The handle in case of not equal is created temporarily and destroyed later before calling init.
=> Unify instantiation of image handles in ImageFileNameProvider

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Pattern.java
This PR refactors Pattern in the win32 implementation to better support multiple handles for different zoom settings by creating all handles only on demand.
=> [win32] Create Pattern handles on demand

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java
Currently, when an image is instantiated using `ImageDataProvider `or `ImageFileNameProvider`, a handle is created immediately. We aim to optimize this by deferring handle creation until it is explicitly needed. To achieve this, `getBounds()` will return the bounds of a 100% zoomed image when called after instantiation, without requiring a handle to be created upfront. This change improves efficiency by reducing unnecessary resource allocation during image initialization.
Attaching the snippet to test the use cases after this change:
```java
package org.eclipse.swt.snippets;
public class SnippetTestImage {
final static String IMAGES_ROOT = "bin/org/eclipse/swt/snippets/";
public static void …
```
=> Create handles for ImageDataProvider and ImageFilenameProvider on demand

bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Control.java
When calling Control.setParent() during a perspective switch, focus is lost on GTK3. This change restores the focus to the last control that had it, after the reparenting operation.
Fixes: #1915
=> Restore focus that is lost during Control.setParent()

bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Display.java
Subclasses are not created in GTK4, leading to the assignment of NULL pointers when disposing the display. If a second display is created afterwards, this leads to a segmentation fault.
Contributes to
https://github.com/eclipse-platform/eclipse.platform.swt/pull/1663
=> [GTK4] Fix segmentation fault when creating multiple displays

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/AllBrowserTests.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/AllGraphicsTests.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/AllNonBrowserTests.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/AllTests.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/AllWidgetTests.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_Display.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/performance/PerformanceTests.java, tests/org.eclipse.swt.tests/META-INF/MANIFEST.MF, tests/org.eclipse.swt.tests/pom.xml
First towards being able to move unit tests to JUnit 5.
=> Migrate SWT suites to JUnit 5

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java
This PR adapts the win32 implementation of Image, so ensure that the background color of an image is always set to all existing of later created image handles. Currently all handles that are created after the background color was set, would not receive the background color.
- #1909
=> [win32] Set background color on all image handles

bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/DPIUtil.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java
This PR contributes to fixing the implementation of Smooth scaling of the ImageData to get rid of the rounding errors because of multiple scale ups and downs with fractional scale factor. The commit replicates and modifies the DPIUtil::autoScaleImageData method implementation in Image class to adapt the same.
contributes to
=> Smooth Scaling Rounding error fix for win32 #62

bundles/org.eclipse.swt/Eclipse SWT Browser/win32/org/eclipse/swt/browser/Edge.java, bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/browser/EdgeTests.java
We must ensure that we always use the ASCII-String (URL-encoded) everywhere.
Refactor code a bit to make it possible to add a testcase.
Fixes #1912.
=> Edge: Fix URI_FOR_CUSTOM_TEXT_PAGE in case tmpdir contains unicode chars

bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/List.java
Follow up on
https://github.com/eclipse-platform/eclipse.platform.swt/pull/1829 review. Renamed the `search_enabled` method to have same name / visibility as on Tree/Table classes.
=> Renamed search_enabled to searchEnabled to be consistent

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_SWT.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_graphics_RGB.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_graphics_RGBA.java
Shorter tests, better reports of problems, more idiomatic JUnit usage.
=> Convert RGB/RGBA/SWT tests to JUnit 5.

Jenkinsfile
Also make sure the issues are published even in case of a failed build, as otherwise they are not visualized.
See https://github.com/eclipse-tycho/tycho/pull/4897
=> Jenkinsfile: Use Tycho 4.0.13 way to display api tools warnings

bundles/org.eclipse.swt.svg/.classpath, bundles/org.eclipse.swt.svg/.project, bundles/org.eclipse.swt.svg/.settings/org.eclipse.core.resources.prefs, bundles/org.eclipse.swt.svg/.settings/org.eclipse.jdt.core.prefs, bundles/org.eclipse.swt.svg/META-INF/MANIFEST.MF, bundles/org.eclipse.swt.svg/META-INF/services/org.eclipse.swt.internal.image.SVGRasterizer, bundles/org.eclipse.swt.svg/build.properties, bundles/org.eclipse.swt.svg/fragment.properties, bundles/org.eclipse.swt.svg/src/org/eclipse/swt/svg/JSVGRasterizer.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/SWT.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/image/FileFormat.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/image/SVGFileFormat.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/image/SVGRasterizer.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/AllNonBrowserTests.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_internal_SVGRasterizer.java, tests/org.eclipse.swt.tests/META-INF/p2.inf, tests/org.eclipse.swt.tests/data/collapseall.svg, tests/org.eclipse.swt.tests/data/corrupt.svg
Eclipse currently loads icons exclusively as raster graphics (e.g., `.png`), without support for vector formats like `.svg`. A major drawback of raster graphics is their inability to scale without degrading image quality. Additionally, generating icons of different sizes requires manually rasterizing SVGs outside Eclipse, leading to unnecessary effort and many icon files.
This PR introduces support for vector graphics in Eclipse, enabling SVGs to be used for icons. Existing PNG icons will continue to be loaded alongside SVGs, allowing the use of the new functionality without the need to replace all PNG files at once.
---
- **Example Images**:  
Screenshots showcasing the new functionality can be found below. These screenshots were taken with 125% monitor-zoom and scaling enabled with the …
=> Rasterization of SVGs at Runtime for Eclipse Icons 

bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Control.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Shell.java
There is a flood of 
```
(SWT:64178): Gtk-WARNING **: 12:04:34.730: Trying to measure GtkHeaderBar 0x7fb13846ca30 for width of 0, but it needs at least 137
``` 
like messages when developing. The issue is that gtk_widget_measure is being called with for_size=0 param which happens to be below the minimum size for many widgets. The documentation clearly states "If no size is known, -1 can be passed." and so is done now.
=> [GTK4] Fix gtk_widget_measure warning

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java
This PR refactors the Image constructors using plain ImageData to create all handles on demand instead of creating a first handle in the constructor.
=> [win32] Create ImageData based image handles on demand

bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/widgets/CoordinateSystemMapperTests.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/MultiZoomCoordinateSystemMapper.java
The MultiZoomCoordinateSystemMapper currently produces a devide-by-zero error when transforming a rectangle of zero size. This can, for example, happen when a (dummy) shell with width=height=0 is created and its bounds are passed to the mapper.
This change ensures that the problematic calculation is avoided in case width or height are zero. In that case, no reasonable monitor can be identified anyway.
=> [Win32] MultiZoomCoordinateSystemMapper: zero-sized rectangle handling

bundles/org.eclipse.swt.svg/META-INF/MANIFEST.MF, tests/org.eclipse.swt.tests/META-INF/MANIFEST.MF, tests/org.eclipse.swt.tests/META-INF/p2.inf
Currently, requiring an SVG rasterizer needs manual placement of an according fragment on the classpath. With this change, requiring SVG support can be defined explicitly via a required capability that is provided by the according SWT fragment.
Contributes to https://github.com/eclipse-platform/eclipse.platform.swt/issues/1944
=> Consume SVG rasterizer via capability in SWT tests bundle

bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/make_linux.mak
GCC 15 defaults to C23 standard but it's not feasible to use it as even Xlib.h is not compatible yet e.g.
```
/usr/include/X11/Xlib.h:2105:5: note: expected ‘int (*)(Display *,
XEvent *, char *)’ but argument is of type ‘int (*)(void)’
2105 |     Bool (*) (
```
Fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/1865 .
=> Compile as C17 code

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Font.java
This PR ensures Font#extractZoom is device independent. The previous logic didn't provide any advantages anymore after the conversion between points and pixels was changed for Fonts. By using DPIUtil#getNativeZoom the most probable value for the zoom of a new font a chosen.
=> [win32] Make Font#extractZoom device independent

bundles/org.eclipse.swt.tools.spies/META-INF/MANIFEST.MF, bundles/org.eclipse.swt.tools.spies/src/org/eclipse/swt/tools/internal/Sleak.java, bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/StyledText.java
Replacing it with imageGcDrawer
=> Replace usages of new Image(device, width, height)

bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/os.c, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/os_custom.h, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/os_stats.h, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/org/eclipse/swt/internal/gtk/OS.java, bundles/org.eclipse.swt/Eclipse SWT WebKit/gtk/library/webkitgtk.c, bundles/org.eclipse.swt/Eclipse SWT WebKit/gtk/library/webkitgtk_stats.h, bundles/org.eclipse.swt/Eclipse SWT WebKit/gtk/org/eclipse/swt/browser/WebKit.java, bundles/org.eclipse.swt/Eclipse SWT WebKit/gtk/org/eclipse/swt/internal/webkit/WebKitGTK.java
Soup 3.x switched away from its own SoupURI to Glib's GUri (see https://libsoup.gnome.org/libsoup-3.0/migrating-from-libsoup-2.html#uri-type-changed ). Thus g_uri_parse have to be used instead of soup_uri_new.
=> Fix Browser.setCookie on WebkitGtk/Soup3

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_browser_Browser.java
In https://github.com/eclipse-platform/eclipse.platform.swt/commit/50da5ad8523b8c29ef79c494435c71f7e452d025 logic to disable tests was changed in a wrong way. Enable these tests unconditionally now that the prereqs are mandated.
=> Reenable wrongly disabled Browser tests

bundles/org.eclipse.swt/Eclipse SWT PI/win32/org/eclipse/swt/internal/win32/OS.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/MenuItem.java
On Win32, the OS is responsible for painting the Image of a MenuItem and it expects images to be in metrics specific size specified by SM_CYMENUCHECK or SM_CXMENUCHECK. If the images are not provided within these sizes, Windows tries to rescale them, leading to unexpected sizes and masking.
This PR contributes to scaling of the MenuItem::hBitmap with the DPI Aware System Metrics for the size of the SM_CYMENUCHECK since the expected size of the Context menu images can differ from the size specific to the zoom level of the monitor.
This PR also addresses the internal rounding error in the size obtained by the systemMetrics while scaling across different zooms (in case of fractional scaling factor) - The reasoning to that has been added as a comment block in the code.
contributes to …
=> MenuItem Image Scaling with DPI aware metrics #62

bundles/org.eclipse.swt/Readme.Win32.md
Back then, Webkit was provided as an alternative browser backend for SWT on Windows. It has not been part of the build for quite some time and the Webkit binaries for Windows are also not available anymore. This cleans up the readme still containing information that refers to Webkit for Windows,.
Fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/1878
=> Remove reference to Webkit in Win32 readme #1878

Jenkinsfile, bundles/org.eclipse.swt/Eclipse SWT AWT/win32/library/swt_awt.rc, bundles/org.eclipse.swt/Eclipse SWT OpenGL/win32/library/swt_wgl.rc, bundles/org.eclipse.swt/Eclipse SWT PI/cocoa/library/make_macosx.mak, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/make_linux.mak, bundles/org.eclipse.swt/Eclipse SWT PI/win32/library/javaw.exe.manifest, bundles/org.eclipse.swt/Eclipse SWT PI/win32/library/make_win32.mak, bundles/org.eclipse.swt/Eclipse SWT PI/win32/library/os_custom.c, bundles/org.eclipse.swt/Eclipse SWT PI/win32/library/swt.rc, bundles/org.eclipse.swt/Eclipse SWT PI/win32/library/swt_gdip.rc, bundles/org.eclipse.swt/Eclipse SWT/common/library/make_common.mak
This removes all native/library version information that is currently built into the native binaries of SWT.
Consequently the library-version information is only captured in the name of the native binary files and in the 'Library' java class.
The previously built-in information is not used anywhere in SWT.
This allows to just rename the binary files in case just the library version has changed without a change in the native sources. This happens for example if only the native sources for another platform are changed.
=> [Build] Remove SWT library version information built into binaries

bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/DPIUtil.java
The autoscale value may be adapted during runtime, either via explicit methods in DPIUtil or by rewriting the system property. In order to be able to calculate the device zooom for a different autoscale value, such as the initial one, this change adds an according method.
Needed for https://github.com/eclipse-platform/eclipse.platform.ui/pull/2858
=> Add DPIUtil method to get device zoom for original autoscale value

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/DirectoryDialog.java
This is a fixup for ab1d11972aab1c75149f271dca4b58ccfd7710a7.
The contract of `openDialog()` is to throw on error, and return an `Optional` on user action. Null return value is not expected.
This does not fix the issue #1929, but fixes the error reporting per #1026
=> Fix NPE #1929

Jenkinsfile
Build only the SWT binaries whose native sources are really changed and just rename the binaries for all other platforms that are not changed.
Avoiding a rebuild of effectively unchanged binaries has multiple advantages, if only a sub-set of all supported platforms is build:
- reduced build times
- reduced occupation of precious native build-nodes in Jenkins
- increased stability of the build because if the native build-nodes for the skipped platforms are unavailable the build isn't blocked anymore.
- less occupation of the git large-file storage as renaming a binary file has basically zero-cost, while a modified binary (even if just slightly) will add the entire file again.
In order to ensure that native libraries can be renamed without recompilation, we first require:
- …
=> [Build] Rename library files if native sources of platform are unchanged

binaries/pom.xml, bundles/org.eclipse.swt.tools.base/META-INF/MANIFEST.MF, bundles/org.eclipse.swt.tools.base/build.properties, bundles/org.eclipse.swt.tools.spies/build.properties, bundles/org.eclipse.swt.tools/build.properties, bundles/org.eclipse.swt/pom.xml, examples/org.eclipse.swt.examples.browser.demos/META-INF/MANIFEST.MF, examples/org.eclipse.swt.examples.browser.demos/build.properties, examples/org.eclipse.swt.examples.launcher/META-INF/MANIFEST.MF, examples/org.eclipse.swt.examples.launcher/build.properties, examples/org.eclipse.swt.examples.ole.win32/META-INF/MANIFEST.MF, examples/org.eclipse.swt.examples.ole.win32/pom.xml, examples/org.eclipse.swt.examples.views/META-INF/MANIFEST.MF, examples/org.eclipse.swt.examples.views/build.properties, examples/org.eclipse.swt.examples/build.properties, local-build/local-build-parent/pom.xml, local-build/org.eclipse.swt.fragments.localbuild/pom.xml, pom.xml, tests/org.eclipse.swt.tests.cocoa/build.properties, tests/org.eclipse.swt.tests.gtk/build.properties, tests/org.eclipse.swt.tests.win32/build.properties, tests/org.eclipse.swt.tests/pom.xml
Follow-up on
- https://github.com/eclipse-platform/eclipse.platform.swt/pull/1717
@merks any objections?
=> Adjust Maven groupId to match the actual deployment - part 2

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/internal/NativeImageLoader.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/graphics/ImageLoader.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/DPIUtil.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/image/FileFormat.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/internal/NativeImageLoader.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/internal/NativeImageLoader.java
The InternalImageLoader is currently placed in the graphics package and marked as package internal. This change moves it to the internal package improves its name to NativeImageLoader. It also adapts its method's signatures to properly combine element and zoom information if appropriate.
=> Improve signature of methods in InternalImageLoader

bundles/build.properties, tests/build.properties
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2950
=> Ensure unique artifactIds for pomless aggregation modules

bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/DPIUtil.java
Required for https://github.com/eclipse-platform/eclipse.platform.ui/pull/2858
=> Add DPIUtil method for running code in custom auto-scale mode

bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/graphics/MonitorAwarePoint.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/graphics/MonitorAwareRectangle.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/graphics/Point.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/graphics/Rectangle.java
The MonitorAwarePoint and MonitorAwareRectangle classes have been introduced as specializations of the existing Point and Rectangle classes solely to support monitor-specific scaling and only used in the context of that feature. They are not supposed to be used outside of SWT but just an internal construct. However, instances of those classes reach consumers of SWT API, e.g., via the Shell class. This broke equality assumptions for consumers, as, e.g., a comparison between a Point and a MonitorAwarePoint (returned by methods of Shell) are never equal, even though the consumers is not supposed to even know that a MonitorAwarePoint can be returned here.
To restore equality, this change aligns equality of the monitor-aware implementations of point and rectangle with their original …
=> Restore equality for all kinds of Point/Rectangle

bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/graphics/Resource.java
Fixes #1465
* replaced the current implementation  that relies on `finalize()` by using a [Cleaner](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/ref/Cleaner.html) instead
* the `ResourceTracker` no longer holds a reference to the resource, as the Cleaner API mandates that:    
> The cleaning action is invoked only after the associated object becomes phantom reachable, so it is important that the object implementing the cleaning action does not hold references to the object.
*  a flag is now used to detect whether the `nonDisposedReporter` should be invoked.
* the tracker is registered during `init()` to avoid false-negatives for resources throwing an exception in their constructor. e.g `new Cursor(display, -100)`
=> Switch to the Cleaner API

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/internal/DefaultSWTFontRegistry.java
This commit addresses a regression that is caused by DPIUtil#getDeviceZoom not properly initialized yet, when created the first system font. Explicitly passing the target zoom to the Font prevent the issue.
Start a runtime on a zoom > 100 with default configuration (if not visible try a fresh workspace). The CTabFolder fonts will be bigger as expected
=> [win32] use fixed zoom for default system font

binaries/pom.xml
This PR replaces the hardcoded version of surefire-junit-platform with the commonly used ${surefire.version} property. The hardcoded version led to class loading issues with the latest surefire release, 3.5.3.
=> Use consistent versions for surefire plug-ins

.github/workflows/maven.yml
Downgrade to `2.44.0-2` (from `2.48.0-0ubuntu0.24.04.1`). I would have liked to use the previously working version (`2.46.6-0ubuntu0.24.04.1`) but I wasn't able to provide the correct version string for it. If someone knows it, feel free to improve this solution.
This fixes the obscure errors thrown when running the Linux tests. I found this exception in the logs of the most recent GH Actions runs (all of which fail since 2 days ago):
```
2025-04-01T15:46:24.5810004Z Running Test_org_eclipse_swt_browser_Browser#test_OpenWindowListener_openHasValidEventDetails[browser flags: 0]
2025-04-01T15:46:24.5810524Z 
2025-04-01T15:46:24.5810839Z ### Descriptors opened BEFORE test_OpenWindowListener_openHasValidEventDetails[browser flags: 0]: 40
2025-04-01T15:46:24.6438504Z …
```
=> Downgrade WebKit for the Linux GH runner

binaries/org.eclipse.swt.cocoa.macosx.aarch64/.settings/.api_filters, binaries/org.eclipse.swt.cocoa.macosx.x86_64/.settings/.api_filters, binaries/org.eclipse.swt.gtk.linux.aarch64/.settings/.api_filters, binaries/org.eclipse.swt.gtk.linux.loongarch64/.settings/.api_filters, binaries/org.eclipse.swt.gtk.linux.ppc64le/.settings/.api_filters, binaries/org.eclipse.swt.gtk.linux.riscv64/.settings/.api_filters, binaries/org.eclipse.swt.gtk.linux.x86_64/.settings/.api_filters, binaries/org.eclipse.swt.win32.win32.aarch64/.settings/.api_filters, binaries/org.eclipse.swt.win32.win32.x86_64/.settings/.api_filters, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/graphics/ImageGcDrawer.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java
GC can be initialize with `GC(drawable)` or `GC(drawable, style)`. Currently `Image(Device, ImageGcDrawer, height, width)` doesn't consider `style` attribute while initializing `GC`. We need to create a new constructor for `Image` _e.g._ `Image(Device, ImageGcDrawer, height, width, style)` for which later `GC` inside `ImageGcDrawer` is initialized considering the style provided to it.
Now from implementation side, you can override `getGcStyle()` to provide styling in `GC` _e.g._ `LEFT_TO_RIGHT`, etc
Before this change, there was no way for consumer to provide styling using `ImageGcDrawer`. 
```java
final ImageGcDrawer imageGcDrawer = (gc, width, height) -> {
gc.fillRectangle(0, 0, 16, 16);
};
Image = new Image(Display.getDefault(), imageGcDrawer, 1, 1);
}
```
Now with this change. …
=> Add getGcStyle() method to accommodate styling

Jenkinsfile
For linux.x86_64 the jdk-resources for gtk(3) and gtk4 are downloaded, stashed and deleted into/from the same directory. This leads to concurrency issues and build failures.
=> [Build] Stash jdk-resources with respect to WS to prevent overwrites

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_browser_Browser.java
Also, use `String::isEmpty` to check for the size of the location instead of its length
=> Add details to test_LocationListener_ProgressListener_cancledLoad

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_graphics_Image.java
Due to the on-demand creation of image handles, there is not necessarily a handles anymore from which image data is retrieved when requesting is via the getImageData(...) methods. This results in potentially different kinds of image data (including different anti-aliasing results) depending on whether a handle has already been created for an image at the given zoom or not.
This change adapts the Image implementation for ImageDataProvider and ImageFileNameProvider to always use the image data retrieved from a native handle. To this end, it temporarily creates a handle if necessary. In order to avoid repeated loading and handle creation for the same source of image, a cache for the already retrieved image data is introduced. For both the consistent retrieval of image data and the avoidance …
=> [Win32] Ensure consistent image data returned for filename/data provider

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Shell.java
This commit contributes to filling the unpainted region unoccupied by the menu bar and the client area in a window, including the MenuItem hover overlay remains in the area after hovering over them as sometimes MenuItems have their height more than the height of the menu bar, leading to painting in the unmanaged region - hence, contributing to an artifact line.
* Have your primary monitor at 250% and secondary at 125%.
* Start the IDE and move to 125% monitor.
**Undesired Behaviour: ** There's an artifact line between the menu bar and the client area inside the window of the IDE.
**Expected Behaviour: ** There should not be any region in the Window which remains unpainted leading to adverse effects / artifact lines.
contributes to …
=> Fill unpainted region in Window in win32 #62

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/graphics/Image.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/graphics/ImageDataLoader.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/graphics/ImageLoader.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/image/FileFormat.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java
The ImageLoader and FileFormat implementations currently combine the check whether an image can be provided at a specific scale value and the provision of an image in the scale itself. In case a consumer wants to test whether an image can be provided at a specific scale, it needs to request that image at that scale, even if it will not be used later one, e.g., because it cannot be provided in the required scale.
With this change, ImageLoader and FileFormat provide separate methods for validating whether an image can be retrieved at a specific zoom (such as from an SVG) and the retrieval of the image itself. This is employed by the Cocoa Image implementation to avoid unnecessary load operations and in the Win32 Image implementation to correct erroneous scaling from an already initialized …
=> Allow to test for loading image at zoom and fix faulty Win32 image load

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_graphics_Image.java
- Leverage assertThrows()
- Remove marker messages
- general code clean-ups
=> Clean-up Test_org_eclipse_swt_graphics_Image

bundles/org.eclipse.swt/Eclipse SWT Drag and Drop/gtk/org/eclipse/swt/dnd/Clipboard.java, bundles/org.eclipse.swt/Eclipse SWT Drag and Drop/gtk/org/eclipse/swt/dnd/TextTransfer.java, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/gtk4.c, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/gtk4_stats.h, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/org/eclipse/swt/internal/gtk4/GTK4.java
The list of available types is calculated using the GDK4 clipboard and
no longer falls back to the GTK3 bindings.
Note that UTF8_STRING, COMPOUND_TEXT and STRING_ID are not implemented
for GTK4, which is why those types must not be used in the TextTransfer,
regardless of whether X11 or Wayland is used.
=> [GTK4] Implement Clipboard.getAvailableTypes()

bundles/org.eclipse.swt/Eclipse SWT Browser/win32/org/eclipse/swt/browser/Edge.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_browser_Browser.java
This PR cotributes to replicating the behaviour of Edge:evaluate as
it is in WebKit - it must not wait for the execution of script to obtain
the result, in case evaluate is called inside a WebView callback. This
PR also makes sure that OpenWindowListeners are execute
synchronously or asynchronously depending on if the
handleNewWindowRequested is called from the evaluate script. Moreover,
this enables all the tests which were failing because of Edge:evaluate
limitations.
contributes to
https://github.com/eclipse-platform/eclipse.platform.swt/issues/1771 and
https://github.com/eclipse-platform/eclipse.platform.swt/issues/1919
=> Edge:evaluate deadlock fix

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/internal/DefaultSWTFontRegistry.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/internal/ScalingSWTFontRegistry.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_graphics_FontData.java
Creating clone of FontData to be used as a key in map of ScalingSWTFontRegistry and DefaultSWTFontRegistry to make it immutable and inaccessible from outside of the class
=> Make FontData key in map immutable

binaries/pom.xml, bundles/org.eclipse.swt/forceQualifierUpdate.txt
In the SWT fragment jars published in the Eclipse p2-repository the localization files had the wrong names, which are used at dev-time to avoid localization when launching SWT from a development environment.
Furthermore the 'swt.jar' is now not modified anymore before adding it to the assembly for the download-page, which ensures intact signatures.
Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2189
=> Fix localization filenames and preserve signature of swt.jar

bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/make_linux.mak
The port is in early stages and there are still many deprecated usages that should be ported rather than silenced (as in the gtk3 port).
=> Do not treat warnings as errors in gtk4 port

bundles/org.eclipse.swt/Eclipse SWT Browser/win32/org/eclipse/swt/browser/Edge.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_browser_Browser.java
Add a test to it.
Fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/1919
=> Support cascaded java callbacks in Edge #1919

.github/workflows/maven.yml, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_browser_Browser.java
According to https://webkitgtk.org/reference/webkit2gtk/stable/signal.WebView.create.html
_The new WebKitWebView must be related to web_view, see WebKitWebView:related-view for more details._
To ensure this, org.eclipse.swt.browser.WebKit.create(Composite, int)
does the following:
```java
Composite parentShell = parent.getParent();
Browser parentBrowser = WebKit.parentBrowser;
if (parentBrowser == null && parentShell != null) {
Control[] children = parentShell.getChildren();
for (int i = 0; i < children.length; i++) {
if (children[i] instanceof Browser) {
parentBrowser = (Browser) children[i];
break;
}
}
}
if (parentBrowser == null) {
webView = WebKitGTK.webkit_web_view_new();
} else {
webView = WebKitGTK.webkit_web_view_new_with_related_view(((WebKit)parentBrowser.webBrowser).webView);
} …
```
=> Fix browser tests on Linux that open a new window + revert downgrade of WebKit for the Linux GH runner

bundles/org.eclipse.swt.svg/about.html, bundles/org.eclipse.swt.svg/build.properties
The recently added org.eclipse.swt.svg fragment is lacking the required about.html file. This change adds the file to the generated source and binary artifacts bundles.
Fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/2009
=> Add missing about.html to org.eclipse.swt.svg fragment #2009

bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/CTabFolder.java
Setting tooltip to null on mouse enter results in an unpredictable GTK tooltip behavior which in most cases simply doesn't show at all.
Fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/2017
=> CTabFolder: don't unset tooltip value on mouse enter

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Control.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Control.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Control.java
The `Control#getLocation()` and `Control#setLocation(...)` operations currently claim to always work (i.e., yield reasonable values or actually change the location). This specification is incorrect when executing these methods in shells on a platform that uses the Wayland protocol. 
Currently, there does not seem to be a fix to make the implementation fulfill the specification. In case we claim that SWT can be used on Wayland, the specification thus has to be adapted to reflect that behavior. This change adds an according warning to the specification in order to avoid that clients rely on the specification to be fulfilled.
Currently, most UI elements requiring a separate shell/dialog are not placed as expected when using a platform with Wayland.  In the Eclipse SDK, this includes the …
=> Correct contracts of Control#[get|set]Location() #790

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/SwtTestUtil.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_graphics_Image.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_internal_SVGRasterizer.java
Don't consider the 'PLUGIN_PATH' property anymore, which is set in I-build tests and whose handling doesn't work anymore.
Fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/2001 (hopefully).
=> Resolve resources URLs as file-URLs if running in an OSGi environment

bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/DPIUtil.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/DPIUtilTests.java
Cairo auto-scaling was enabled in DPIUtil for every OS in a recent commit. This corrects the setting to be only applied on Linux/GTK and thus also issues arising from it. In addition, it removes the unnecessary setter for the auto-scaling and disables the tests that previously required it as they are meaningless without productive use of disabled Cairo auto-scale on Linux anyway.
Fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/2031
=> Correct Cairo autoscaling setting in DPIUtil and remove setter #2031

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/graphics/Image.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/image/ImageColorTransformer.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/graphics/Image.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java
Each OS-specific implementation of the Image class has its own implementation of an algorithm to calculate a disabled representation of a given image. In addition, the algorithm used on Windows and MacOS produces bad results, which is why usually pre-generated disabled icons are used.
This change centralizes the implementations of those algorithms in ImageColorTransformers. The implementations used for the pre-generated disabled icons is added as default algorithm with an enhanced and the existing GTK-conforming algorithms being provided as options. It is supposed to render the usage of pre-generated disabled version of icons obsolete in many cases.
This is based on the snippet for testing different algorithms proposed by @killingerm and the according discussion in …
=> Unify and improve image disablement calculation algorithm

bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/DPIUtil.java
This PR addresses and issue with DPIUtil#runWithAutoScaleValue. It only adapted DPIUtil#autoScaleValue temporarily. As DPIUtil#deviceZoom is directly affected by autoScaleValue, it is important to adjust it temporarily as well.
fixes https://github.com/eclipse-platform/eclipse.platform.ui/issues/2897
=> Fix for runWithAutoScaleValue

bundles/org.eclipse.swt/Eclipse SWT Drag and Drop/win32/org/eclipse/swt/dnd/DropTarget.java
This PR addresses issues, when DnD across multiple monitors with monitors specific scaling is used. If the monitors have different zoom dragging into a table or tree on the second monitor will detect the wrong destination items depending on the zoom. To address this the zoom should always be inherited from the underlying control if available.
Monitor setup with two different monitors:
- Primary should be the smaller zoom (e.g. 100)
- Secondary should be the bigger zoom (e.g. 150)
- Start the runtime IDE with monitor specific scaling active
1. Open and position the IDE on the secondary monitor and the File explorer on the primary monitor
2. Open the Project explorer with at least one project to drag into
3. Drag a file from the File explorer over to the project
4. You will notice the hover …
=> [win32] Fix DnD across multiple monitors

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java
This PR adds a wrapper for images created with an existing OS handle to ensure all existing image constructors are tied to a final wrapper instance.
=> [win32] Wrapper for existing image handles

bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/DPIUtil.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/DPIUtilTests.java
This commit extends the logic when a Rectangle is scaled up/down from points to pixels regarding width and height.
Fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/2003
=> Preserved width/height on scaleUp/Down a Rectangle

bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Composite.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Control.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Display.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Link.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Sash.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Shell.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Table.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Tree.java
Handles remaining widgets code. Continuation of
https://github.com/eclipse-platform/eclipse.platform.swt/pull/2058 .
Part of https://github.com/eclipse-platform/eclipse.platform.swt/issues/1300
=> [GTK] Stop using DPIUtil (take 2)

bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/image/SVGFileFormat.java
When initializing the SVGFileFormat class for loading SVGs, the current context classloader is used by the ServiceLoader to find an SVGRasterizer implementation. This classloader may be incorrect in some cases, i.e., it may not be the plain system classloader or an according OSGi classloader but, e.g., some specific classloader for test execution.
This change makes the ServiceLoader use the same classloader for finding an SVGRasterizer implementation than the classloader of the SVGRasterizer class itself.
Fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/1965
Fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/2049
I am not completely sure if this will always yield a "correct" classloader or whether the classloader of the `SVGRasterizer` may also be …
=> Use proper classloader for finding SVGRasterizer #1965 #2049

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java
This PR refactors Image in the win32 implementation as Image#imageProvider is final and always != null now. With this the handling and creation of new handles and ImageData was unified.
Relies on https://github.com/eclipse-platform/eclipse.platform.swt/pull/2027 being merged first and includes this commit because of that.
=> [win32] Cleanup image wrappers

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Caret.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Composite.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Control.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/TableItem.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/TreeItem.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Widget.java
This PR unifies the extraction of the target zoom of a font to be
affected by the zoom context of the underlying Widget. Before there
were different strategies like getting it from the Shell.
=> [win32] Use consistent font zoom retrieval

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/graphics/Image.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/DPIUtil.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/graphics/Image.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java
This PR contributes to refactoring the logic for scaling the ImageData using GC from DPIUtil to Image for each platform, where it belongs better and DPIUtil calls the platform specific code from the method DPIUtil:autoScaleImageData.
=> Refactor DPIUtil:autoScaleImageData for better design

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_graphics_Image.java
Due to the on-demand creation of image handles, there is not necessarily a handles anymore from which image data is retrieved when requesting is via the getImageData(...) methods. This results in potentially different kinds of image data (including different anti-aliasing results) depending on whether a handle has already been created for an image at the given zoom or not.
This change adapts the implementation of Image based on static ImageData and streams to always use the image data retrieved from a native handle. To this end, it temporarily creates a handle if necessary. In order to avoid repeated loading and handle creation for the same source of image, a cache for the already retrieved image data is introduced.
<s>⚠️ This is based on and should thus be merged after …
=> [Win32] Ensure consistent image data returned for data-based images

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Composite.java
This commit reverts moving the initialization of GCData.font in Composite#WM_Paint in commit 033d733.
Fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/2066
=> [win32] Fix GC font for composite

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java
This PR moves some initialization checks related to ImageFileNameProvider and ImageDataProvider into the matching Wrapper implementation.
=> [win32] Move some Image initialization checks

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java
This PR is a simple refactoring and just moves the code that is equal to all AbstractImageProviderWrapper implementations back to Image.
=> [win32] Move of unified code from Wrapper to Image

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java
This PR moves the cleanup of OS handle of images from Image to the subclass Image#ImageHandle.
Main reason to do this is Image#destroyHandleForZoom can easily be called with the wrong zoom. Calling destroy explicitly on ImageHandle reduces risk of too much or not deleted handles
=> [win32] Delegate handle destruction to ImageHandle

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/graphics/Image.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/DPIUtil.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/graphics/Image.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java, examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet367.java, examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet382.java
This PR extends the usage of ImageGcDrawar to support SWT.Transparency as style that will initialize each GC with a proper transparent bitmap.
**Important:** 
Adaption for GTK and Cocoa will be added when we agree on the approach
I can extract to DPIUtil change into a separate PR
=> Extend ImageGcDrawer to support transparency

Jenkinsfile, bundles/org.eclipse.swt.svg/META-INF/p2.inf
Ensure that the applicable implementation fragments are available for svg fragment
Part of
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/3006
=> Fix svg fragment build

bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/internal/SessionManagerDBus.java
For example this simplifies disabling the `SessionManagerDBus` in CI environments where no bus is available.
At our CI-server, which formally doesn't have an X-Server installed and uses xvnc I see the following warnings:
```
SWT SessionManagerDBus: Failed to connect to org.gnome.SessionManager: Failed to execute child process “dbus-launch” (No such file or directory)
SWT SessionManagerDBus: Failed to connect to org.xfce.SessionManager: Failed to execute child process “dbus-launch” (No such file or directory)
```
Setting the system-property `org.eclipse.swt.internal.SessionManagerDBus.disable` disables the `SessionManagerDBus` right from the start and prevents these warnings. But I have to set that system-property in the Maven/Tycho pom.xml as well as in all headless eclipse executions we …
=> Support disabling the GTK SessionManagerDBus via environment variables

binaries/org.eclipse.swt.cocoa.macosx.aarch64/forceQualifierUpdate.txt, binaries/org.eclipse.swt.cocoa.macosx.x86_64/forceQualifierUpdate.txt, binaries/org.eclipse.swt.gtk.linux.loongarch64/forceQualifierUpdate.txt, binaries/org.eclipse.swt.gtk.linux.ppc64le/forceQualifierUpdate.txt, binaries/org.eclipse.swt.gtk.linux.riscv64/forceQualifierUpdate.txt, binaries/org.eclipse.swt.gtk.linux.x86_64/forceQualifierUpdate.txt, binaries/org.eclipse.swt.win32.win32.aarch64/forceQualifierUpdate.txt, binaries/org.eclipse.swt.win32.win32.x86_64/forceQualifierUpdate.txt, bundles/org.eclipse.swt/forceQualifierUpdate.txt
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/3011
=> Force qualifier updates

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/GC.java
This PR adapts the extraction of the correct image handle in the windows implementation when using an Image with a GC. As the image will always pass the exact zoom it needs to the GC using the autoscaled zoom together with an Image can lead to unexpected results when fixed values for swt.autoScale are passed, e.g. scaling ImageData can result in endless loops.
This effect can be seen e.g. by executing Snippet119 with
```
-Dswt.autoScale=200
```
=> [win32] Prevent loop with fix swt.autoScale value

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Cursor.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Control.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Shell.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Tracker.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Tree.java
Supersedes https://github.com/eclipse-platform/eclipse.platform.swt/pull/2071
Fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/2057
- #2092 
- Use 2 monitors with different zoom levels (none of them should match the zoom level passed to `-Dswt.autoScale` in the next step)
- Run `Snippet119` with the following JVM parameters: 
- `-Dswt.autoScale=200` (or use another zoom level that doesn't match any of the zooms in your monitors)
- `-Dswt.autoScale.updateOnRuntime=true`
Expected: the size of the cursor matches the size of the current monitor and **not** the one you provided for `-Dswt.autoScale`
- Move the window of the snippet to the monitor 
Expected: the size of the cursor still matches the size of the current monitor and **not** the one you provided for …
=> Do not use DPIUtil.getNativeDeviceZoom() to get the cursor handle #2057

bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Canvas.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Caret.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Combo.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Control.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/ExpandBar.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/ExpandItem.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/List.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Menu.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/ScrollBar.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Shell.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/TabItem.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Text.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/ToolBar.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/ToolItem.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/ToolTip.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Tracker.java
They are not needed at all, double some calls (like checkWidget()), and overall complicate debugging and understanding the codebase. Continuation of
https://github.com/eclipse-platform/eclipse.platform.swt/pull/2100
=> [GTK] Remove more *InPixels method

bundles/org.eclipse.swt/Eclipse SWT/cairo/org/eclipse/swt/graphics/Path.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/graphics/Device.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/graphics/Region.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Composite.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Control.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Display.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Link.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/ScrollBar.java
Remove nowadays useless extra methods that even has the bad side effect of duplicating checks.
Continuation of
https://github.com/eclipse-platform/eclipse.platform.swt/pull/2101
=> [GTK] Even more *InPixel method removal

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java, examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet382.java
This PR adapts and copies all handles in the copy constructor in Image. As each image now manages possibly more than one OS handles at the same time in the windows implementation, it is important to apply the operation on all of them.
=> [win32] Adapt/copy all handles on Image copy

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java
This PR adapts all places, where operation where executed with OS handles created for a specific zoom that could use any zoom. Therefor now any existing handle is used or, if none exists yet, a temporary handle is created and destroyed afterwards.
=> [win32] Utilize temporary image handles

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java
This PR wraps the GC initialization for the ImageGcDrawer to directly pass the zoom from the wrapper when the GC is initialized. In all other cases the GC will be initialized with 100 zoom.
=> [win32] Improve GC init for ImageGcDrawer

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Font.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/internal/SWTFontProvider.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/internal/ScalingSWTFontRegistry.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Control.java
Creating a new static method to retrieve font handle. Handles will no longer be created during initialization. Also destroy condition is changed since handle being 0 doesn't mean that it was destroyed anymore.
- Run the following snippet with following VM arguments:
```
```
```java
public class SWTFontExample {
shell.setText("SWT Font Example");
shell.setSize(400, 200);
shell.setLayout(new FillLayout());
Label label = new Label(shell, SWT.CENTER);
label.setText("Hello, SWT with Custom Font!"); …
```
=> Create Font handles on demand

Jenkinsfile
Fixes following warnings in the build:
```
[WARNING] useSystemClassLoader setting has no effect when not forking
[WARNING] The parameter forkCount should likely not be 0. Forking a JVM
for tests improves test accuracy. Ensure to have a <forkCount> >= 1.
```
=> Fix surefire warnings in build

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_browser_Browser.java
Until it's fixed, the test shall remain deactivated.
In response to: https://github.com/eclipse-platform/eclipse.platform.swt/pull/2106#issuecomment-2857050688 (@akurtakov )
=> Deactivate toggling test for the Edge browser

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/graphics/Color.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/graphics/Color.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Color.java
They were added a while ago but they are not used and their visibility makes them unusable outside the same package.
What confuses me is the comment (JavaDoc) saying `Prevents uninitialized instances from being created outside the package`. Maybe @jonahgraham / @akurtakov remember why they were needed or what the JavaDoc means? 
- Introduced in 6f25fa51112fbf1670baee56c085ab60273daf47
- Fix for https://bugs.eclipse.org/bugs/show_bug.cgi?id=563560
- Related to https://bugs.eclipse.org/bugs/show_bug.cgi?id=563018
=> Remove unused constructors in Color

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Font.java
The on-demand creation of Font handles does not consider that a font may already have been disposed when first retrieving it's handle, which triggers the on-demand initialization. To avoid that this initialization after disposal fails, this change adds a check for the font being destroyed when performing the initialization.
Fixes https://github.com/eclipse-platform/eclipse.platform.ui/issues/2960
=> [Win32] Do not initialize font when already disposed

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java
This PR removes Image#initialNativeZoom in the windows implementation. To achieve this all usages of this field are replaces by either using a concrete zoom values or by creating a temporary handle.
=> [win32] Remove Image#initialNativeZoom

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java
This PR adjusts the order in the Image copy constructor. As the call to ImageProviderWrapper#createCopy creates cached variants for some implementation. These created variants could be missing disablement/greyed state. Therfore this flag is set before that.
=> [win32] Fix for Image disablement

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java
This PR fixes a regression introduced with f10721a that did not properly retain the currently drawn zoom level when an ImageGcDrawer is used. That leads to issues with zoom != 100.
=> [win32] Fix double buffer paint with ImageGcDrawer

bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/DPIUtil.java
This is a refactoring _i.e._ no functionality has been changed here.
Changes introduced:
- Rename `autoScaleMethodSetting` to `AUTO_SCALE_METHOD_SETTING`
- Declare it `final` _i.e._ turn it into a constant
- Add the method `AutoScaleMethod::forString` for better readability
- Use the method to get the desired method and default to `AUTO` if nothing (or some invalid value) was set in the system property
- Set the value of `autoScaleMethod` based on the value of the constant instead of the system setting. If the constant was `AUTO` then the method is set to `NEAREST`
=> Refactoring: Transform the field DPIUtil.autoScaleMethodSetting to a constant

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/graphics/Font.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/graphics/Font.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Font.java
=> Remove unused constructors in Font

bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Combo.java
Fixes " UnsatisfiedLink 'long
org.eclipse.swt.internal.gtk3.GTK3.gtk_entry_get_text(long)'" problem at runtime.
=> [GTK] Fix Combo.getSelection on GTK 4

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/graphics/Image.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/graphics/Image.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java, examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet215.java, examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet292.java, tests/org.eclipse.swt.tests.gtk/ManualTests/org/eclipse/swt/tests/gtk/snippets/Bug531667_CanvasPrint_does_not_work.java, tests/org.eclipse.swt.tests.gtk/ManualTests/org/eclipse/swt/tests/gtk/snippets/Bug547529_ControlPrintBroken.java, tests/org.eclipse.swt.tests.gtk/ManualTests/org/eclipse/swt/tests/gtk/snippets/Bug547529_ImageLoaderStriping.java, tests/org.eclipse.swt.tests.gtk/ManualTests/org/eclipse/swt/tests/gtk/snippets/Bug547557_ShellPrintGC.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_graphics_Image.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_graphics_TextLayout.java, tests/org.eclipse.swt.tests/ManualTests/org/eclipse/swt/tests/manual/Bug529534_CTabFolder_topRight_wrapped.java
Deprecate Image constructor that accepts Rectangle in favor of Image(display, width, height).
=> Deprecate Image(Rectangle) constructor and replace usages

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/GC.java
This PR reduces the calls to Image#win32_getHandle(int) in GC. When drawing an image with a GC multiple draw... methods are calling each other for that operation. All those methods are refetching the handle via Image#win32_getHandle(int) with getZoom(). To support use cases where a method uses a different zoom to get a handle to draw the handle is now fetched in the top most methods and are passed to the other methods directly.
This PR does not change any behavior of the drawing of images.
=> [win32] Reduce calls to Image#win32_getHandle(int)

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_Combo.java
These only look awkward in failures. This is also prep step for whenever suite is to be migrated to JUnit 5.
=> Remove dummy assert message in Combo tests

bundles/org.eclipse.swt/Eclipse SWT Browser/common/org/eclipse/swt/browser/Browser.java
When using WebView2 as browser engine in SWT without a WebView2 runtime being available on the system, browser initialization fails. In order to more gracefully handle the case that a system has no such runtime installed (like on some Windows 10 systems), this change introduces an automatic fallback to Internet Explorer in case no WebView2 runtime is found. In addition, once the first browser is instiantiated (either during application startup or when a view containing a browser is opened), it shows an error dialog informing about the missing runtime and the fallback to IE, and its point to the error log, to which an error is posted that also contains a link to FAQ. This makes it possible to easily copy the link, which is not possible from the message box (or maybe someone knows how to …
=> [Edge] Add fallback when WebView2 runtime is not present #2000

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/GC.java
This commit adapts the drawImage method in GC in the windows implementation for copying and (probably) scaling an area from a source image into the GC target. With the Image supporting multiple handles now, the handle from the source image is no longer always chosen by the zoom context of the GC but sometimes from the target size, e.g. if an image should be drawn with a scale of 2 on a 100% monitor, it might provide better results to use an image handle fitting for 200%.
If you execute the Snippet below with and without the PR you should see something like below: left with this PR and right without this PR. Top row is simulating a GC on 100%, bottom row on 200% zoom. Scale factors for each of each of the three images are 1, 1.5 and 2, so100%, 150% and 200% on top and 200%, 300% and 400% …
=> [win32] Choose best Image handle drawing with GC

tests/org.eclipse.swt.tests/ManualTests/org/eclipse/swt/tests/manual/Issue0445_HiDPISmoothScaling.java
This pull request removes the call to DPIUtil.getDeviceZoom() from a test. The commit is intended as a test to ensure that the subsequent refactoring commits will trigger the GitHub workflow.
=> Remove DPIUtil.getDeviceZoom() in test which just prints to console

bundles/org.eclipse.swt/Eclipse SWT Browser/win32/org/eclipse/swt/browser/Edge.java, bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/browser/EdgeTests.java
Use Path.equals() instead of URI.equals() to compare the URI paths.
This will will handle upper/lower-case differences correctly which can arise, e.g. when symlinks are involved.
Fixes #2061.
=> Edge: Fix URI_FOR_CUSTOM_TEXT_PAGE in case of case mismatch

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Control.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Widget.java
This PR introduces the data attribute AUTOSCALE_DISABLED for the windows implementation for Widgets. This will disable autoscaling for this Widget and all of its children. This is a necessary requirement for complex usages utilizing GC. Without disabling autoscaling rendering artifacts will be introduced when only parts of the GC are redrawn on monitor specific scaling with some zoom value, e.g. 175%. This commit serves as starting point to harden this feature before considering extracting an API out of it.
=> [win32] Allow disablement of autoscale per Widget

bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Shell.java
Fetch GdkDisplay from GdkSurface as done on Wayland
=> [GTK4] Stop Shell.bringToTop from crashing on Gtk 4.x

examples/.settings_shared/org.eclipse.jdt.core.prefs
There is one extra change about unused lambda warnings which was autoadded by JDT that's why I keep it in.
=> Do not show warnings for missing javadoc in examples

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Tree.java
This PR contributes to handling wmNotify event for tooltip of a Tree regardless of if the Tree object maintains the handle of the tooltip in itemToolTipHandle. If there's a tooltip which is not handled by wmNotifyToolTip, it is completely maintained by windows and hence can span over multiple montiors. Hence, with this PR such tooltips are also positioned inside a single monitor to prevent any infinite loop.
Here's the explanation:
1. For a tree where the tooltip is not maintained in itemToolTipHandle (Since createToolTips was not called -> no createItem(TreeItem, ...) calls or _addListener() call with SWT.Paint or MeasureItem), wmNotifyToolTip cannot handle its drawing and hence it is completely drawn and positioned by windows, which can be risky -> can lead to inifinite loop if the …
=> Fit tooltip of the tree on a single monitor #62

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Composite.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_Composite.java
This reverts commit 807b159fb65000762a179e6793cdd29e86a99cd4.
Add regression test.
Fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/2162
=> Revert "Replace usages of new Image(device, width, height)..." #2162

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_Spinner.java
* Use assertThrows
* Do not override parent test method so it actually gets executed
=> Simplify Spinner test

examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/SnippetExplorer.java
Makes it easier to view the text as it appears in the launcher.
=> Use text block in SnippetExplorer

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java
This PR adapts the zoom passed to the GC when it is initialized for a plain Image created via Image#Image(Device, int, int) with a given width and height. It will fall back to DPIUtil#getDeviceZoom() again to revert to original bevahiour and prevent blurry rescaling of old usages.
=> [win32] Adapt GC zoom when using plain images

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_graphics_Image.java
When copying an image based on an input stream, the copied provider wrapper was erroneously created on the original image. This change adapts the instantiation to create the warpper on the correct image.
Fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/2188
=> [Win32] Initialize copied image provider wrapper on correct image #2188

bundles/org.eclipse.swt/Eclipse SWT Accessibility/gtk/org/eclipse/swt/accessibility/AccessibleObject.java
It simply doesn't exist there thus causes a number of CRITICAL/WARNING.
=> [GTK] Safeguard ATK to not be used on GTK 4.x

examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/SnippetLauncher.java
PocketPC and JavaXPCom are dead technologies - no need to special handling them.
Catch only IOExceptions (rather than Exception)
=> Streamline SnippetLauncher

bundles/org.eclipse.swt/Eclipse SWT Drag and Drop/win32/org/eclipse/swt/dnd/ImageTransfer.java, examples/org.eclipse.swt.examples/META-INF/MANIFEST.MF, examples/org.eclipse.swt.examples/src/org/eclipse/swt/examples/clipboard/ClipboardExample.java
Copy and paste no longer tries to autoscale the image. The image is always copied and pasted at 100% zoom.
The purpose of this change is to:  
1) Fix an issue in the clipboard example where the pasted image had different zoom levels across monitors  
2) Remove all calls to `DPIUtil.get[Native]DeviceZoom()`
Previously, when copying an image in the clipboard example, the image at the current zoom level was stored to clipboard using `getImageDataAtCurrentZoom()`. However, in normal Windows behavior (e.g., Paint), images are always copied at their original size regardless of the current zoom. When pasting, the image is pasted at 100% zoom, and the application handles zoom internally when displaying the image.
To match this behavior, copy and paste now always handle images at 100% scale, …
=> Fix zoom issue during copy paste in clipboard example

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_browser_Browser.java
This PR adds relevant loggings for debugging purposes to the Browser tests which sporadically fail for Edge Browser.
contributes to #2098, #2113 and #2063
=> Sporadically failing Browser Tests logging for Edge Browser

bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Control.java
GTK4 doesn't have such api anymore and it would have to be handled at the rendering layer as per
https://gitlab.gnome.org/GNOME/gtk/-/commit/0ce19eed083c79c5fb4091db3ecaf528346e610f .
=> [GTK] Fix Gtk4 test crash in Control.setRegion

bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/graphics/GCWin32Tests.java, bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/graphics/RegionWin32Tests.java, bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/graphics/TransformWin32Tests.java, bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/widgets/ControlWin32Tests.java, bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/widgets/WidgetWin32Tests.java, tests/org.eclipse.swt.tests.win32/ManualTests/org/eclipse/swt/widgets/PatternWin32ManualTest.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/DPIUtilTests.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_graphics_GC.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_graphics_Image.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_Display.java
DPIUtil.get[Native]DeviceZoom() is no longer meaningful when monitor-specific scaling is used, so its usage has been removed from most tests. In some cases , these have been left unchanged for now.
Among the occurrences mentioned in [Eclipse Platform Issue #195](https://github.com/vi-eclipse/Eclipse-Platform/issues/195), most have been addressed. Still the following four cases remain unmodified:
```
1)org.eclipse.swt.tests.junit.Test_org_eclipse_swt_graphics_GC.executeWithNonDefaultDeviceZoom(Runnable)
2)org.eclipse.swt.tests.junit.DPIUtilTests.setup()
3)org.eclipse.swt.tests.junit.Test_org_eclipse_swt_graphics_Image.test_updateWidthHeightAfterDPIChange()
```
In these three tests, `getDeviceZoom()` is used to capture the zoom level before execution and restore it afterward. No suitable …
=>  Removing getDeviceZoom from tests

bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Button.java
From Gtk documentation "GtkImage displays its image as an icon, with a size that is determined by the application. See GtkPicture if you want to show an image at is actual size."
=> [GTK] Button images should be GtkImage not GtkPicture

bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Shell.java
It's GTK 3 (even X11) concept that Wayland doesn't have - "windows are windows". See
https://discourse.gnome.org/t/replacing-gtk-window-set-type-hint-in-gtk4/22599/2 for explanation from developers.
=> [GTK] Gtk 4 don't have the concept of window hints

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/graphics/FontData.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/graphics/FontData.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Font.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/FontData.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/internal/DefaultSWTFontRegistry.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/internal/ScalingSWTFontRegistry.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_graphics_FontData.java
This change will give us a chance to use proper channel to create a deep copy of FontData object instead of using FontData(fd.toString)
=> New FontData Constructor to create a deep copy

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_Item.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_MenuItem.java
Use assertThrows and assertFalse to make things more obvious.
=> Simplify MenuItem tests assertions

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/CoordinateSystemMapper.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Display.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/MultiZoomCoordinateSystemMapper.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/SingleZoomCoordinateSystemMapper.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Tree.java
This commit contributes to moving
Tree:getContainingMonitorBoundsInPixels and
Tree:fitRectangleBoundsIntoMonitor to CoordinateSystemMapper and Display,
respectively for better clarity and encapsulation.
contributes to
https://github.com/eclipse-platform/eclipse.platform.swt/issues/62 and
https://github.com/eclipse-platform/eclipse.platform.swt/issues/128
=> Reorganized monitor-bound utils in Tree

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/GC.java
This PR ensures that the GC always uses the font with the correct zoom in the windows implementation. There is currently no issue caused by this. This is required for the GC to be recreatable on demand. This will be added in a different PR.
=> [win32] Refetch GC font on demand

bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/widgets/ControlWin32Tests.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/internal/ScalingSWTFontRegistry.java
Previously, system fonts were not cached during their creation in ScalingSWTFontRegistry. This change ensures that  system fonts, are now cached in fontsKeyMap
=> Cache all Fonts in ScalingSWTFontRegistry on creation

bundles/org.eclipse.swt/Eclipse SWT Drag and Drop/gtk/org/eclipse/swt/dnd/Clipboard.java
It's not possible to paste text data with accented characters (CP-1252) from a Windows VNC connection to a Linux server. Pasting text into other desktop applications works just like gedit. In the code to be merged, each type is attempted (in the order UTF8_STRING, COMPOUND_TEXT, STRING) until the text can be retrieved from the clipboard.
In the gtkclipboard.c file (request_text_received_func function) of the GTK3 native library it does something similar:
```
static void
request_text_received_func (GtkClipboard     *clipboard,
GtkSelectionData *selection_data,
gpointer          data)
{
RequestTextInfo *info = data;
gchar *result = NULL;
result = (gchar *) gtk_selection_data_get_text (selection_data);
if (!result)
{
/* If we asked for UTF8 and didn't get it, try compound_text;
* if we asked …
```
=> Fail to get text from the clipboard when text is Latin-1 encoded but transfer data type is UTF8_STRING

bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/MenuItem.java
This allows to use more shortcuts to be displayed for a menu item, e.g. `Ctrl+Keypad +` or `Alt+Down`.
=> MenuItem (GTK): allow additional shortcut words #1852

tests/org.eclipse.swt.tests.win32/ManualTests/org/eclipse/swt/tests/win32/snippets/Bug121220_AlphaTransparencyWithPatterns.java, tests/org.eclipse.swt.tests.win32/ManualTests/org/eclipse/swt/tests/win32/snippets/Bug536008_DarkDisabledLabel.java, tests/org.eclipse.swt.tests.win32/ManualTests/org/eclipse/swt/tests/win32/snippets/Bug560358_DarkMenuBar.java, tests/org.eclipse.swt.tests.win32/ManualTests/org/eclipse/swt/tests/win32/snippets/Bug560546_GC_drawString_vs_GC_drawText.java, tests/org.eclipse.swt.tests.win32/ManualTests/org/eclipse/swt/tests/win32/snippets/Bug563475_DarkDisabledTable.java, tests/org.eclipse.swt.tests/ManualTests/org/eclipse/swt/tests/manual/Bug205199_Label_Image_vs_Text.java, tests/org.eclipse.swt.tests/ManualTests/org/eclipse/swt/tests/manual/Bug529534_CTabFolder_topRight_wrapped.java, tests/org.eclipse.swt.tests/ManualTests/org/eclipse/swt/tests/manual/Bug562233_DisposeExceptions.java, tests/org.eclipse.swt.tests/ManualTests/org/eclipse/swt/tests/manual/Bug577878_GTK_TreeTable_NoDragImageWithPaintItem.java, tests/org.eclipse.swt.tests/ManualTests/org/eclipse/swt/tests/manual/Issue0021_HdcLeak_ImageCreateGdipImage.java, tests/org.eclipse.swt.tests/ManualTests/org/eclipse/swt/tests/manual/Issue0146_CopyImageToClipBoard.java, tests/org.eclipse.swt.tests/ManualTests/org/eclipse/swt/tests/manual/Issue0603_WrongTaskBarOverlays.java
Replacing Image(Display, int, int) with Image(Display, ImageGcDrawer, int, int) in Tests. Manual Tests.
=> Refactor Image(Display, int, int) in Tests (Manual Test)

pom.xml
With https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/3140 they will no longer be published thus it makes no sense to generate them anymore.
=> Stop generating feature source

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/graphics/Image.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_graphics_Image.java
An Image based on an ImageGcDrawer currently initializes two image representations for 100% and 200% zoom, so that an appropriate representation for each of the two zoom levels can be retrieved. This, however, leads to issues when creating a GC on an Image created in that way, as only one of the two representations (the one fitting to the current device zoom) will be modified by the GC. If later the representation with the other zoom is used, it will not contain the changes performed by the GC.
One such scenario is starting an application at a monitor with one zoom (used as the device zoom throughout the application lifecycle then) and moving the shell to a monitor with a different zoom. An image will then be modified only for the zoom of the first monitor, thus if using it inside a …
=> [macOS] Initialize image data from ImageGcDrawer only at device zoom

tests/org.eclipse.swt.tests.win32/JUnit Tests/org/eclipse/swt/tests/win32/Test_org_eclipse_swt_dnd_DND.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_graphics_GC.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_graphics_Image.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_graphics_TextLayout.java
Replacing Image(Display, int, int) with Image(Display, ImageGcDrawer, int, int) in Tests. Automated Test Case.
=> Refactor Image(Display, int, int) in Tests (Automated Tests)

Jenkinsfile
Currently the build is aborted if the branch tip is at a commit, which was committed with the email of the 'Eclipse Platform Bot'. This is done to prevent rebuilds after a commit for a SWT native binary rebuild was pushed by the bot. But because that bot is also used for other kind of commits, this test leads to false positives. This is a consequence of
- https://github.com/eclipse-platform/eclipse.platform.swt/pull/2207
This reworks the pipeline to check if the head commit has a SWT-native-binary build tag attached, which is a more precise indicator.
This also fixes the check if a native rebuild is enforced, when testing if the build can be skipped.
=> [Build] Remove check for SWT native binary rebuild commit

bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/internal/LegacySWTFontRegistryTests.java, bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/widgets/ControlWin32Tests.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/internal/LegacySWTFontRegistry.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/internal/SWTFontProvider.java
**Summary**
This PR introduces the following changes:
1)Always use ScalingSWTFontRegistry
2)Rename DefaultSWTFontRegistry -> LegacySWTFontRegistry as this is not default anymore
3)Add a system property to use LegacySWTFontRegistry without monitor specific scaling active
4)Deprecate the LegacySWTFontRegistry(DefaultSWTFontRegistry)
5)additionally the change also makes sure all fonts are cached when they are created, this is necessary to make sure the systemfonts would also be cached when they are created (this change is to fix  Test_org_eclipse_swt_graphics_GC.test_setFontLorg_eclipse_swt_graphics_Font which was broken with ScalingSwtFontRegistry)
**Reproduction Steps**
To use the legacy font registry instead of the default scaling registry, launch the application with the following system …
=> Deprecate DefaultSWTFontRegistry and Completely switch to ScalingSWTFontRegistry

bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/TabFolder.java, tests/org.eclipse.swt.tests/pom.xml
Added missing null/disposal check for cases when tab has no control set. Issue can be seen and verified fixed using Snippet266.
=> [GTK] Fix NPE in switch page on gtk 4.x

bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/widgets/ControlWin32Tests.java, bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/widgets/CoordinateSystemMapperTests.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/graphics/MonitorAwarePoint.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/graphics/MonitorAwareRectangle.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/graphics/Point.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/graphics/Rectangle.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/DPIUtil.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/MultiZoomCoordinateSystemMapper.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/DPIUtilTests.java
The two commits in https://github.com/eclipse-platform/eclipse.platform.swt/pull/2200 were merged without proper validation and cause builds to fail due APi errors.
This is a simple revert of https://github.com/eclipse-platform/eclipse.platform.swt/pull/2200.
=> Revert broken api

bundles/org.eclipse.swt/Eclipse SWT WebKit/gtk/org/eclipse/swt/browser/WebKit.java, bundles/org.eclipse.swt/Eclipse SWT WebKit/gtk/org/eclipse/swt/internal/webkit/WebKitGTK.java
This changes adds a search dialog to WebKit browsers. The search dialog is opened with Ctrl+F and has next/previous word matching capabilities.
Fixes: #2222
=> Add search capabilities to WebKit based Browser

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/GC.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/GCData.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Pattern.java
This PR provides a minimal implementation to apply the operation pattern on GC that is used on most other resources to re-create resources on zoom changes. A difference in this implementation is that there is always exactly one OS handle per GC. On zoom change the existing handle is cleaned up a created for the new zoom. There is no use case that requires managing of multiple handles per GC.
This PR does not change any existing behavior. It encapsulated all actions inside the GC into operations. A different PR will utilize this to trigger a re-creation of an existing GC for a different zoom level.
=> [win32] Apply Operation pattern on GC

bundles/org.eclipse.swt/Eclipse SWT Drag and Drop/win32/org/eclipse/swt/dnd/DropTarget.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/internal/Win32DPIUtils.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Display.java
This PR sets temporarily the DPI awareness of the thread to PerMonitorV2 if necessary, when DnD operations are executed. This is necessary as the process could be started with System Aware DPI mode which is inherited from the native methods related to DnD.
Its a bit complicated because its not reproducible with runtime. You will need to replace the three affected classes e.g. in the SWT jar of an I-Build with the changes in this PR to see the improvement.
fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/2246
=> [win32] Ensure correct DPI awareness for DnD

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/GC.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java
This PR  adapts the behavior of the commonly used pattern of a GC that draw onto a plain image. In the windows implementation the monitor specific scaling could lead to issues with this pattern, because during creation time of an GC/Image combo it was not always clear with which zoom the final result will be drawn upon. This commit will redraw the GC on an image handle if a new zoom is requested. The handle for the old zoom of the image will be kept, but if another operation of the GC is executed it will only be applied on the new handle.
You can use this small windows specific snippet to force an image redraw with a different zoom
```java
package org.eclipse.swt.snippets;
import …
```
=> [win32] Refresh GC handle when related image 

bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/widgets/ControlWin32Tests.java, bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/widgets/CoordinateSystemMapperTests.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/graphics/MonitorAwarePoint.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/graphics/MonitorAwareRectangle.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/graphics/Point.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/graphics/Rectangle.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/DPIUtil.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/MultiZoomCoordinateSystemMapper.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/DPIUtilTests.java
Reverts https://github.com/eclipse-platform/eclipse.platform.swt/pull/2264 and also adds the appropriate API filters as per https://github.com/eclipse-platform/eclipse.platform.swt/pull/2200#issuecomment-3008208197.
=> Reintroduce OfFloat (internal) classes #62

bundles/org.eclipse.swt.svg/META-INF/MANIFEST.MF, bundles/org.eclipse.swt.svg/src/org/eclipse/swt/svg/JSVGRasterizer.java
The image data generated for a rasterized SVG currently uses a 32 bit data array and an alpha values array. The alpha values for every pixel are stored in both the alpha values array as well as the alpha channel of the 32 bit data array. This is a redundant representation not giving any benefits but just leading to unnecessary memory consumption.
This change adapts the SVG rasterization to create image data with a 24 bit data array, such that the alpha values are only stored in the alpha array.
This was detected via and would also resolve:
- https://github.com/eclipse-platform/eclipse.platform.ui/issues/3047
I have to admit that I am not completely sure when a 32 bit data array can/must be used together with an alpha data array, thus having duplicate representation of alpha data. When …
=> Remove duplicate representation of alpha values in image data from SVG

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/graphics/Image.java
The `autoScale` methods no longer have relevance in the Win32 implementation, so this commit extracts the macOS-specific DPI scaling logic into a dedicated `CocoaDPIUtil` class. This improves platform separation and maintains cleaner, OS-specific code boundaries.
=> Refactor: Move Cocoa-specific DPI methods to CocoaDPIUtil

tests/org.eclipse.swt.tests.win32/JUnit Tests/org/eclipse/swt/graphics/ImageWin32Tests.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/SwtTestUtil.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_graphics_Image.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_Button.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_Caret.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_Decorations.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_Label.java, tests/org.eclipse.swt.tests/ManualTests/org/eclipse/swt/tests/manual/Bug569752_DetectNonDisposedOsResources.java
Replacing Image(Display, int, int) with Image(Display, ImageGcDrawer, int, int) in Tests. Basic Case
=> Refactor Image(Display, int, int) in Tests (No Ops)

bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/DPIUtil.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/graphics/GC.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/graphics/Image.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/graphics/TextLayout.java
This commit introduces a dedicated `GtkDPIUtil` class to isolate GTK-specific DPI logic, improving platform separation and maintainability.
Since the GTK scaling factor is always 1, the `autoScaleUp` and `autoScaleDown` methods effectively return the input unchanged. These methods and their usages have been removed from the GTK implementation to eliminate unnecessary code.
Also clarifies that `autoScale` no longer applies to the Win32 implementation and is being decoupled accordingly.
=> Refactor: Move GTK-specific DPI logic to GtkDPIUtil

bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Control.java
Fixes #344.
Running snippet 62 and double clicking used to register two up events but only one down event when there should also have been two. This was due to the use of SWT.MouseDoubleClick instead of SWT.MouseDown. I have modified it such that in the event SWT.MouseDoubleClick fails, SWT.MouseDown is tried instead. This keeps the double click as an option for the future if support is added.
I also changed the behaviour so triple clicks and higher are now treated as double clicks rather than being ignored.
=> Fix Double Click not Registering Snippet 62 

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_SWT.java
It was wrongly bound to enable when the disable param is passed.
=> Make isLocal disable param really disable

bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/gtk4.c, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/gtk4_stats.h, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/org/eclipse/swt/internal/gtk4/GTK4.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/DateTime.java
=> Fix size of DateTime widget on Gtk 4

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/graphics/Image.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/graphics/Image.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Caret.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_graphics_Image.java
The deprecated method getBoundsInPixel() in Image is marked for removal along with its tests.
=> Mark Deprecated getBoundsInPixel for removal

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/GC.java
Previously, stringExtent calculated the width of a string in pixels using GC.getZoom(), which could lead to inconsistencies if the provided font had a different zoom level. This change ensures that the pixels-to-points conversion uses the zoom of the specified font.
Fixes #2311 
Reproduction Steps
On a 100% monitor, set these parameters:
```
-Dswt.enable.autoScale=true
-Dswt.autoScale=150
-Dswt.autoScale.method=nearest
```
Screenshots
<table>
<tr>
<td align="center" valign="top">
<br/>
<sub>Current Behaviour</sub>
</td>
<td align="center" valign="top">
<br/>
<sub>With This Change</sub>
</td>
</tr>
</table>
Have tested the changes on zooms **100,150,200&225** with` -Dswt.autoScale`=**150 ,100 &200,**
=> Use font zoom in stringExtent and textExtent

bundles/org.eclipse.swt/Eclipse SWT PI/win32/org/eclipse/swt/internal/win32/OS.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/MenuItem.java
For menu items of type CHECK and RADIO with an image, it create an second image with a checkmark/circle over the original image.
=> [win32] Add workaround for missing selection indicator for menu item with image on Win11 (#501)

tests/org.eclipse.swt.tests.win32/JUnit Tests/org/eclipse/swt/graphics/ImageWin32Tests.java, tests/org.eclipse.swt.tests.win32/JUnit Tests/org/eclipse/swt/tests/win32/AllWin32Tests.java, tests/org.eclipse.swt.tests.win32/JUnit Tests/org/eclipse/swt/tests/win32/KeyboardLayoutTest.java, tests/org.eclipse.swt.tests.win32/JUnit Tests/org/eclipse/swt/tests/win32/Test_org_eclipse_swt_dnd_DND.java, tests/org.eclipse.swt.tests.win32/JUnit Tests/org/eclipse/swt/tests/win32/Test_org_eclipse_swt_events_KeyEvent.java, tests/org.eclipse.swt.tests.win32/JUnit Tests/org/eclipse/swt/tests/win32/Win32DPIUtilTests.java, tests/org.eclipse.swt.tests.win32/JUnit Tests/org/eclipse/swt/tests/win32/widgets/TestTreeColumn.java, tests/org.eclipse.swt.tests.win32/JUnit Tests/org/eclipse/swt/tests/win32/widgets/Test_org_eclipse_swt_widgets_Display.java, tests/org.eclipse.swt.tests.win32/META-INF/MANIFEST.MF, tests/org.eclipse.swt.tests.win32/ManualTests/org/eclipse/swt/tests/win32/snippets/Bug512629_test_fullscreen_before_open.java, tests/org.eclipse.swt.tests.win32/ManualTests/org/eclipse/swt/tests/win32/snippets/Bug567422_DNDCrash.java
This migrates the Win32 tests for SWT to JUnit5, including the usage of JUnit 5 test annotations, assertions and test suite.
=> Migrate SWT Win32 tests to JUnit 5

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/GC.java
**Description:**
Each Operation subclass now maintains its own list of disposable SWT resources. These are added to a `disposables `list within the Operation and are disposed when the GC is disposed. This ensures cleanup of resources.
**Steps to Reproduce:**
There is currently an issue with SWT resource tracking due to monitor-specific scaling. To reproduce the warning:
1)Temporarily comment out [`resourcesWithZoomSupport.add(resource);`](https://github.com/eclipse-platform/eclipse.platform.swt/blob/master/bundles/org.eclipse.swt/Eclipse%20SWT/win32/org/eclipse/swt/graphics/Device.java#L967)  in the Device class (i.e., the implementation of registerResourceWithZoomSupport):
2)Start the Eclipse runtime workspace with the following VM argument: …
=> Track and dispose resources created by operations in GC

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/GC.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java, tests/org.eclipse.swt.tests.win32/JUnit Tests/org/eclipse/swt/graphics/ImageWin32Tests.java, tests/org.eclipse.swt.tests.win32/META-INF/MANIFEST.MF
When an image is drawn on a GC, that image may be disposed right afterwards. Since the GC can live much longer and a handle for that GC at a different zoom may be requested later on, such that the operations in the GC are re-applied, the stored image may be disposed by then. This can currently lead to errors because of access to disposed resources.
To avoid that, this change ensures that in case a drawn image becomes disposed, a copy of it is created and stored for the lifetime of the GC.
⚠️ This depends on the GC operation disposal logic of and thus contains those changes and needs to be merged after https://github.com/eclipse-platform/eclipse.platform.swt/pull/2328
=> [Win32] Avoid disposed image usage in GC operations

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Cursor.java
**Description**
Before this change, the cursor used DPIUtil.validateAndGetImageDataAtZoom() to get image data. However, this method could return image data at a different zoom level if the exact match wasn't available from the ImageDataProvider. As a result, the cursor could be scaled incorrectly, since the returned image data was assumed to match the requested zoom.
With this change, a temporary Image is created, and Image.getImageData(zoom) is called to get properly scaled image data for the requested zoom level.
**Steps to reproduce:**
Run the below  snippet  at **150% monitor zoom**. The ImageDataProvider in the snippet returns image data only for zoom levels 100 and 200.
**Without this change**
When run without any `swt.autoScale` VM argument, the cursor size was incorrectly scaled …
=> Fix cursor loading incorrect image size when ImageData is unavailable at requested zoom

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/GC.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Region.java
This PR refactors GC.SetClippingRegionOperation to store Region and hence refactors GC:setClipping(Region) to call the Operation instead of GC:setClipping(long) for a better behaviour on a GC refresh. Additionally this PR also makes Region operations compatible with GC Operation Strategy by following:
1. Copy Resource on Operation Creation
2. Register the region object as a disposable
Contributes to
https://github.com/eclipse-platform/eclipse.platform.swt/issues/62 and https://github.com/eclipse-platform/eclipse.platform.swt/issues/128
=> Store Region in GC.SetClippingRegionOperation #62

tests/org.eclipse.swt.tests.gtk/ManualTests/org/eclipse/swt/tests/gtk/snippets/Bug569468_GtkLafSync.java
Keep the SWT workspace with a bit less warnings.
=> Remove useless suppress warning

bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Control.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Widget.java
Gtk 3 "popup-menu" signal no longer exists on Gtk 4 thus popup menu has to be handled by the generic "gesture-press".
Renamed the Gtk 3 handler to acknowledge the fact it doesn't belong to Gtk 4 port and removed wrong effort to port the popup-menu handler to Gtk 4.
=> [GTK] Support popup menu on Gtk 4

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_graphics_GC.java
Some GC tests are explicitly executed on a non-default device zoom. However, most of them use a GC as subject to test that is  created in a setup method that is thus using the original device zoom instead of the non-default one set by the test afterwards.
This change ensures that when executing a test with a non-default device zoom, the GC used as subject to test is recreated to rely on that modified device zoom.
Contributes to https://github.com/eclipse-platform/eclipse.platform.swt/issues/2334
=> Correct GC tests to properly execute at non-default device zoom

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/GC.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_graphics_GC.java
When calling GC#setFont(), a copy of the given font is created. However, the font may be null, leading to an exception. In addition, a font should be retrieved from the font provider instead of creating a new font that is manually disposed later on.
This change ensures that null fonts are properly handled and that the stored font is retrieved from the provider.
Fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/2350
=> [Win32] Properly handle setting null font to GC #2350

bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/graphics/Image.java
The device zoom is hard-coded to 100% when creating blank images. Setting it to the current device zoom in the constructor is both wrong and unnecessary, given that the value will be immediately overwritten.
=> [GTK] Remove duplicate device-zoom initialization in Image

bundles/org.eclipse.swt/Eclipse SWT Browser/win32/org/eclipse/swt/browser/Edge.java
This PR releases the HandleCoreWebView2SwtCallback resource created by Edge browser in createControllerInitializationCallback after it has been registered by CreateCoreWebView2Controller method as otherwise the HandleCoreWebView2SwtCallback object can cause memory leaks if left unreleased.
fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/2339
*How to test:*
1. On master, test this snippet:
```java
package org.eclipse.swt.snippets;
import org.eclipse.swt.browser.*;
public class Snippet138 {
Shell parentShell = new Shell(display);
long allocatedMemory = …
```
=> Release Edge callbacks after registering

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/MenuItem.java
In `MenuItem#calculateRenderSize`, a GC (graphics context) is created using `this.getMenu().getShell()`. However, this assumes that the menu returned by `getMenu()` is non-null, which is only valid for MenuItems with style `SWT.CASCADE` that have an explicitly assigned submenu.
For MenuItems with styles like `SWT.PUSH`, `SWT.CHECK`, or `SWT.RADIO`, the result of `getMenu()` is null, as these items do not have submenus. Attempting to call `getShell()` on a null Menu leads to a `NullPointerException` during size computation.
To address this, we replace:
`GC gc = new GC(this.getMenu().getShell());`
with:
`GC gc = new GC(this.getParent().getShell());`
This ensures that the GC is always created using the Shell associated with the parent Menu, which is guaranteed to exist, regardless of the …
=> Fix NPEs in MenuItem#calculateRenderSize() and MenuItem#getMonitorZoom()

binaries/org.eclipse.swt.cocoa.macosx.aarch64/.settings/.api_filters, binaries/org.eclipse.swt.cocoa.macosx.x86_64/.settings/.api_filters, binaries/org.eclipse.swt.gtk.linux.aarch64/.settings/.api_filters, binaries/org.eclipse.swt.gtk.linux.loongarch64/.settings/.api_filters, binaries/org.eclipse.swt.gtk.linux.ppc64le/.settings/.api_filters, binaries/org.eclipse.swt.gtk.linux.riscv64/.settings/.api_filters, binaries/org.eclipse.swt.gtk.linux.x86_64/.settings/.api_filters, binaries/org.eclipse.swt.win32.win32.aarch64/.settings/.api_filters, binaries/org.eclipse.swt.win32.win32.x86_64/.settings/.api_filters, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/graphics/MonitorAwarePoint.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/graphics/MonitorAwareRectangle.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/graphics/Point.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/graphics/Rectangle.java
The MonitorAwareRectangle/MonitorAwarePoint classes have been replaced by Rectangle.WithMonitor and Point.WithMonitor. They have been marked as deprecated but not removed because of issues with API tooling, however they were marked as non-API so they may be removed without any deprecation period.
This change effectively removes the classes, only keeping package-internal stubs of them as otherwise API tooling currently fails.
This is not the cleanest solution as it is driven by tooling limitations, but I don't think we should unnecessarily keep those classes and I am currently stuck in debugging the tooling issue:
- https://github.com/eclipse-tycho/tycho/issues/5148
Since API tooling treats this change as a breaking API change despite the `@noreference` Javadoc tag, according API filters …
=> Effectively remove replaced MonitorAwareRectangle/MonitorAwarePoint

bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/StyledText.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_custom_StyledText.java
- Updated productive code to prevent IllegalArgumentException when replacing text in a StyledText control with variable line height and no focus, by adding boundary checks.
- Added a regression test to validate the fix: ensures no exception is thrown when replacing the full text range under these conditions.
Fixes: eclipse-platform/eclipse.platform.swt#2302
=> Fix replaceTextRange logic for unfocused StyledText with variable line height

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Cursor.java
While retrieving the handle for the cursor for specific zoom, currently we scale up the cursor source image but not the hotspot coordinates. This commit ensures we have per-zoom coordinates for the cursor.
=> Fix Cursor hotspot coordinate calculation

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Cursor.java
Extracting out the OS handle creation logic into separate methods. Intention is to make them reusable if someone want to create only a OS handle within a Cursor class.
=> [Win32] Refactor the Cursor constructors 

bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/widgets/ControlWin32Tests.java, bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/graphics/Image.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/DPIUtil.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/graphics/Image.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java
Fixes #2353 
In PR #2249, a strict check was introduced  that `ImageData` should be linearly scaled for 
zoom levels. And imageDataProviders in SWT repo not following this strict checks were modified (eg to return only imageData at 100%).
However, this change broke `DPIUtil.autoScaleImageData`. That function creates an Image using the system zoom level, draws it on a GC at scaled dimensions, and then requests ImageData at 100% zoom from the image. Since the `ImageDataProvider` was now restricted to 100% zoom only, requesting imageData at other zoom levels during creation of  image at system zoom level triggered recursive calls,  causing a stack overflow error.
The current commit reverts the behavior of the `ImageDataProvider` used in` DPIUtil.autoScaleImageData` to return the same …
=> Fix stack overflow in DPIUtil.autoScaleImageData

bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Table.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Tree.java
Owner draw with check button creates custom GtkCellRendererToggle but it's final on Gtk 4.
=> [GTK] Prevent "no more handles" in Tree/Table on Gtk 4

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/SingleZoomCoordinateSystemMapper.java
This PR replaces the usage of the zoom attribute in methods in the `SingleZoomCoordinateMapper` that translate `Point` and `Rectangle` from and to display coordinates to use `DPIUtil.getDeviceZoom()` instead. As each widget inherits its zoom from  `DPIUtil.getDeviceZoom()` when the `SingleZoomCoordinateMapper` is involved, the behavior is not changed in most scenarios. but this PR fixes the scenarios, if a widget is scaled to a different zoom, e.g. by utilizing `widget.setData("AUTOSCALE_DISABLED", true)` the current implementation will break all conversions. One important factor in the CoordinateMapper implementation is to have a consistent translation from and to display coordinates. In the `MultiZoomCoordinateSystemMapper` this is achieved by extracting the Monitor (zoom) out of the …
=> [win32] Use deviceZoom in single zoom mapper

bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Canvas.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Composite.java, examples/org.eclipse.swt.examples/src/org/eclipse/swt/examples/controlexample/Tab.java
Make the code slightly more readable
=> [Gtk] Use foreach

bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/graphics/Device.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Display.java
Fixes a number of "Gdk-CRITICAL **: 14:38:20.208:
gdk_monitor_get_scale_factor: assertion 'GDK_IS_MONITOR (monitor)' failed" warnings in the console.
This doesn't make SWT fail but it's better to play safe. See https://gitlab.gnome.org/GNOME/gtk/-/issues/5075 for some background information.
=> [GTK] Fix gdk_monitor_get_scale_factor on Gtk 4 on X11

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_graphics_GC.java
Using JUnit 5 Assumptions in JUnit 4 Test led to assumptions being treated as failures rather than skipped tests.
Use newer JUnit features like assertThrows and etc.
=> Convert GC test to JUnit 5

bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Control.java
GtkWidgets can act as containers thus SwtFixed don't have to used always.
=> [GTK] Do not try to remove fixedHandle if there is none

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/GC.java
This issue reverts the behavior of `GC::textExtent` to use `GC::getZoom()` instead of the font’s zoom, as the previous change(#2306) introduced a regression.
I am yet unable to identify the root cause of the regression. From my understanding, With a monitor zoom of 150 even in the case of `Integer200`, the text when drawn with `OS.DrawText`  is drawn according to monitor zoom (e.g., 150), which aligns with `gc.font.zoom`. Based on this, it seemed reasonable to use the font’s zoom to calculate the text extent as `gc.textExtent()` works by drawing text in pixels with `OS.drawText()` and therefore should convert pixels to points using the zoom the text was drawn with.
However, since the change causes a regression which makes eclipse almost unsusable at Integer200, this PR reverts the …
=> Revert usage of getZoom() when calculating TextExtent

bundles/org.eclipse.swt/Eclipse SWT Browser/common/org/eclipse/swt/browser/Browser.java
When a browser is opened and the WebView2 engine used as default is not available, a dialog pops up with additional information and the ability to switch back to the Internet Explorer for the current application session. By now, the dialog lacked the information that the switch to the Internet Explorer is not permanent. In addition, it was not possible to disable that dialog, e.g., for scenarios in which an application is executed in some automation and such a popup blocks automated processes.
This change adapts the dialog message to clarify that the switch to Internet Explorer will lose its effect on next application start and refers to the information link which gives more insights on how to permanently switch back to Internet Explorer. In addition, it adds a system property to disable …
=> [Edge] Improve dialog when WebView2 engine is not available #2035

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java
This PR extends the internal zoom used in Image in the windows implementation to a complex object. This is preparatory work to provide a consistent behavior independent of the auto scale mode, e.g. when an Image is drawn with a GC.
The introduced ZoomContext is only used in one place with two different values for targetZoom and nativeZoom, in Image#applyUsingAnyHandle. This is the correct way to fill ZoomContext here, but the zoom does not matter for the usages of this method anyway.
=> [win32] Introduce ZoomContext in Image

bundles/org.eclipse.swt/Eclipse SWT Browser/win32/org/eclipse/swt/browser/Edge.java
For the unlikely (but possible) case in which the callback is executed too late and the browser/display has already been disposed.
=> Check if the browser is disposed before scheduling runnable in Edge

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Cursor.java
Currently, the `Cursor`implementation has a design flaw related to the `isIcon` field:
- It is used by handle provider implementations to distinguish ways in which a handle shall be created, which requires access of the provider to data of a cursor and requires some instantiations to pass dummy values (mask==null). 
- It defines how handles for that cursor have to be created and destroyed, without any guarantee that creation and destroyal are implemented in a conforming way.
This change gets rid of the `isIcon` field by two means:
- It introduces a `CursorHandle` class that encapsulates the destroy logic for a handle and assign it upon creation of the handle, such that destroy logic fits to how the handle was created.
- It also introduces an `ImageDataWithMaskHandleProvider` that properly …
=> [Win32] Properly encapsulate cursor handle creation and disposal

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/GC.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/GCData.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java
This PR adapts the logic when a bitmap or icon is drawn with the GC in the windows implementation. As of now, the autoscale zoom was used to identify the image handle to use. If the image is itself drawn with a ImageGCDrawer, information about the original native zoom was lost, which led to inconsistencies in fonts depending on the auto scale mode. This PR forwards the native zoom in this case to enable the Image to initialize the GC accordingly. This was e.g. an issue with auto scale mode integer200 as described in #2385.
=> [win32] Fix inconsistency when an Image with GC is drawn on a GC

bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Shell.java
This is a continuation of bd1cdd6ea39b2785a4b28905eedeac28caabcaf0 where a 'GTK_IS_WIDGET (widget)' warning is logged when measuring the height of a NULL titlebar. This issue appears when e.g. calling setBounds() on a Shell.
To reproduce this warning, run e.g. Snippet16.
=> [GTK4] Fix GtkWidget warning when updating shell bounds

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_graphics_Image.java
This fixes a regression from https://github.com/eclipse-platform/eclipse.platform.swt/pull/1989 as reported by @sratz: https://github.com/eclipse-platform/eclipse.platform.swt/pull/1989#issuecomment-3195890789
A caching mechanism for ImageData introduced to some provider implementations inside the Image class leads to Image#getImageData() returning an ImageData object, which if modified affects the underlying Image. This contradicts the contract of that method, which states that changes to that object will not affect the Image.
This change ensures that Image#getImagetData() only returns objects that are not used internal of the Image instance. To this end, clones of the ImageData are created where necessary.
=> [Win32] Ensure Image#getImageData() returns no internal data

prepareNextDevCycle.sh
It will be called by the pipeline to prepare a new development cycle and automates the configuration of SWT build scripts for the new cycle. This is used by
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/3260
=> [RelEng] Add individual release preparation script for SWT

bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/os.c, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/os_stats.h, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/org/eclipse/swt/internal/gtk/OS.java, bundles/org.eclipse.swt/Eclipse SWT Program/gtk/org/eclipse/swt/program/Program.java
Make Program class explicitly check for "/usr/bin/flatpak"(flatpak) and for "env"(snap) commands and use the commandline in this case instead of the command only.
Command line is not used every time to not introduce breakage unintentionally in some other cases.
=> [GTK] Support launching Flatpak/Snap applications

bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Table.java
Fixes an issue in
https://github.com/eclipse-platform/eclipse.platform.swt/pull/2472
=> [Gtk] Ensure gtk_tree_path_free is called before returning

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Table.java
The Table.DRAG_IMAGE_SIZE constant specifies the width of the drag image when a table item is dragged. Previously, this value was fixed in pixels, which caused the drag image to appear too small on high-DPI monitors.
This change redefines DRAG_IMAGE_SIZE in points and converts it to pixels based on the current zoom level, ensuring consistent drag image sizing across different display scales.
- Run the following snippet in 100% monitor zoom and then 250% monitor zoom
- Try to drag the leaf item 
- The drag item should look bigger in 250% monitor
```java
import org.eclipse.swt.dnd.*;
public class DragImageOfTableItemExample {
public static void main(String[] args) …
```
=> Scale Table.DRAG_IMAGE_SIZE by zoom level instead of using fixed pixels

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/TableColumn.java
The Tree.SORT_WIDTH constant specifies the extra width added to a column when a sort column is set (`setSortColumn`). This reserves space for the sort indicator. Previously, it was defined as a fixed pixel.
- Run the following snippet with 250% zoom
- You will notice extra pixels on the Sort column width than previous state.
```
package org.eclipse.swt.snippets;
public class TableColumnSortWidthExample {
public static void main(String [] args) {
final Display display = new Display();
System.setProperty("swt.autoScale", "quarter");
System.setProperty("swt.autoScale.updateOnRuntime", "true");
shell.setText("Custom gradient …
```
=> Scale Table.SORT_WIDTH by zoom level instead of using fixed pixels

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Tree.java
The Tree.DRAG_IMAGE_SIZE constant specifies the width of the drag image when a tree item is dragged. Previously, this value was fixed in pixels, which caused the drag image to appear too small on high-DPI monitors.
This change redefines DRAG_IMAGE_SIZE in points and converts it to pixels based on the current zoom level, ensuring consistent drag image sizing across different display scales.
- Run the following snippet in 100% monitor zoom and then 250% monitor zoom
- Try to drag the leaf item 
- The drag item should look bigger in 250% monitor
```java
import org.eclipse.swt.dnd.*;
public class DragImageOfTreeItemExample {
public static void main (String [] args) { …
```
=> Scale Tree.DRAG_IMAGE_SIZE by zoom level instead of using fixed pixels

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/internal/ImageList.java
Images inside an ImageList may become disposed. For that reason, methods like indexOf() or add() check for the images inside the list being disposed to null them. This check is missing in the getHandle() method used when requesting the ImageList handle for a different zoom, which can lead to exceptions because of access to a disposed Image instance.
This change adapts the ImageList implementation to always consider that an image inside the list may have been disposed. The according cleanup logic is factored out from all places.
Fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/2432
=> [Win32] Clean up disposed images when retrieving image list handle #2432

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Composite.java
This PR contributes to reducing the number of redraws and only draw once all the widgets have performed scaling using their Widget:handleDpiChange handlers.
contributes to
https://github.com/eclipse-platform/eclipse.platform.swt/issues/62 and https://github.com/eclipse-platform/eclipse.platform.swt/issues/128
=> Only redraw once after scaling every widget #62

tests/org.eclipse.swt.tests.win32/JUnit Tests/org/eclipse/swt/graphics/ImageWin32Tests.java, tests/org.eclipse.swt.tests.win32/JUnit Tests/org/eclipse/swt/tests/win32/SwtWin32TestUtil.java, tests/org.eclipse.swt.tests.win32/JUnit Tests/org/eclipse/swt/tests/win32/Test_org_eclipse_swt_dnd_DND.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_graphics_Image.java, tests/org.eclipse.swt.tests/META-INF/MANIFEST.MF, tests/org.eclipse.swt.tests/pom.xml
- makes multiple test methods with more comprehensive names out of a combined single one
- adds test method for additional use case
- adds win32-specific tests methods for specifics in Windows image handling
=> Improve and extend tests for Image#getImageData()

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Table.java
The Table.VISTA_EXTRA and Table.EXPLORER_EXTRA constants specify additional spacing applied to table items when using the Vista or Explorer themes. Previously, both were defined as fixed pixel values, which worked at 100% zoom but did not
scale properly on high-DPI monitors.
This change redefines VISTA_EXTRA and EXPLORER_EXTRA in points and converts them to pixels based on the current zoom level, ensuring consistent spacing for themed table items across different display scales.
- Run Snippet 7 from Snippet Explorer with Primary monitor of 250%
- You will notice the width is bit (2 px) wider than previous state since we take zoom into consideration.
=> Scale Table.EXPLORER_EXTRA by zoom level instead of using fixed pixels

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/FontDialog.java
The FontDialog implementation creates a font handle based on the selection in the dialog to extract information about the font size out of that created font. Due to point/pixel conversion and roundings that depend on the current DPI (affected by the primary monitor zoom), the resulting font size selected differs from what the user has selected. For example, when selecting a 10pt font, the result of the dialog will contain a height of 9.75pt on a 100% monitor and of 10.2pt on a 125% monitor.
At the same time, the dialog manages the logically selected size, i.e., in the given scenario the selected 10pt, which could be used instead.
This change replaces the complex and imprecise font height extraction logic with a simple read of the actual value selected by the user.
Note that this will not …
=> [Win32] Use exact selected font size from FontDialog

binaries/org.eclipse.swt.cocoa.macosx.aarch64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.cocoa.macosx.x86_64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.gtk.linux.aarch64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.gtk.linux.loongarch64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.gtk.linux.ppc64le/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.gtk.linux.riscv64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.gtk.linux.x86_64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.win32.win32.aarch64/META-INF/MANIFEST.MF, binaries/org.eclipse.swt.win32.win32.x86_64/META-INF/MANIFEST.MF, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/graphics/Point.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/graphics/Rectangle.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/internal/Win32DPIUtils.java
This PR adds Rectangle.OfFloat.from and Point.OfFloat.from methods and removes the Win32DPIUtils.FloatAwareGeometryFactory class to make these methods OS-independent.
=> Add OfFloat.from methods in Point/Rectangle

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/GC.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_graphics_GC.java
When calling `GC#drawImage()`, an operation is created (like for every execution on GC) which stores the image to draw. Since the image may be disposed afterwards, a dispose listener is registered to the image, such that the image can be copied and maintained inside the operation in case of a disposal until that operation itself is disposed. The listener is currently not de-registered when disposing the GC and its operations, thus the GC operations (and thus also the containing GC) will still be referenced (as listeners from the image) until that image is disposed. Since images may be long living (or never be disposed at all), this can lead to a memory leak.
This change removes the listener from the image upon disposal of a GC and its operations such that no memory can occur.
Fixes …
=> [Win32] Fix potential memory leak in GC#drawImage #2499

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_Shell.java
We cannot set/determine the location of the shell using Window Handle on
GTK4. So fix the test not to test the set and get location on GTK4.
see https://github.com/eclipse-platform/eclipse.platform.swt/issues/2498
=> GTK4: Fix GTK4 shell location test.

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Cursor.java
On Windows, the mouse pointer size can be increased in Accessibility settings. Previously SWT always created cursors at their logical bitmap size (e.g. 16x16, 32x32), ignoring the accessibility scale.
This change reads `CursorBaseSize` from
`HKCU\Control Panel\Cursors` and uses it as a scale factor when creating SWT cursors. For example, with scale = 5, a 16px cursor bitmap is scaled to 80px before being displayed, matching the user’s configured pointer size.
This aligns SWT custom cursors with the system accessibility setting and improves usability for users with enlarged cursors.
- Run following snippet.
<details><summary>Snippet386</summary>
<p>
```java
public class Snippet386 {
private static final int IMAGE_SIZE_IN_POINTS = 16; …
```
=> SWT: Respect Windows accessibility cursor size setting

bundles/org.eclipse.swt.svg/src/org/eclipse/swt/svg/JSVGRasterizer.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/image/SVGRasterizer.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/JSVGRasterizerTest.java
It shall be possible to draw images at a custom zoom or size while maintaining the best achievable quality. To support this, images originating from an SVG source must be rasterized at the required size.
The internal API introduced in this PR enables loading SVGs at custom sizes, allowing images to be drawn at any requested zoom level or resolution, as discussed in in https://github.com/vi-eclipse/Eclipse-Platform/issues/326
> **Goal** It shall be possible to draw images at a custom zoom/size at the best achievable quality. This means either
> 
> * rescaling from the most fitting zoomed version of the image that exists
> * rasterizing the image at the according size from an SVG source
This PR specifically adds the internal API to handle rasterization for images coming from SVG sources.
=> Add internal API in SVGrasterizer to rasterize images at given height and width

bundles/org.eclipse.swt/Eclipse SWT Browser/common/org/eclipse/swt/browser/Browser.java, bundles/org.eclipse.swt/Eclipse SWT Browser/win32/org/eclipse/swt/browser/Edge.java, bundles/org.eclipse.swt/Eclipse SWT PI/win32/org/eclipse/swt/internal/ole/win32/ICoreWebView2.java
- MouseListener
- up
- down
- doubleClick
- MouseMoveListener
- move
- MouseTrackListener
- exit
- enter
- MouseWheelListener
- scroll
- DragDetectListener
- dragDetected
The implementation is JavaScript-based by attaching listeners to the DOM for all relevant events and forwarding them to the WebView via `window.chrome.webview.postMessage()`.
The event handling is analogous to IE's
`IE#handleDOMEvent(org.eclipse.swt.ole.win32.OleEvent)`.
Note: Since the implementation is JavaScript-based, this requires JavaScript to be enabled on the Browser instance.
When JavaScript is disabled, we keep using the timer-based fallback implementation introduced in #1551.
As JavaScript is only truly enabled *after* navigation has finished, we also keep using this workaround when the Browser is first …
=> Edge: Implement mouse-related event listener support

bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/widgets/WidgetWin32Tests.java
Some of the tests in WidgetWin32Tests assert the size of the controls after DPI_CHANGE. The tests work fine since theres no updateLayout called but its deffered to be executed after the thread is free and hence the controls size are unaffected. However this is risky and layouting can make the values arbitrary and the tests can fail. Hence, we simply test the absolute values without using any Layout in this PR.
=> Fix specific WidgetWin32Tests to not use Layout

bundles/org.eclipse.swt.tools/JNI Generation/org/eclipse/swt/tools/internal/ASTType.java, bundles/org.eclipse.swt.tools/JNI Generation/org/eclipse/swt/tools/internal/NativesGenerator.java, bundles/org.eclipse.swt.tools/JNI Generation/org/eclipse/swt/tools/internal/ReflectType.java, bundles/org.eclipse.swt.tools/META-INF/MANIFEST.MF, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/os_custom.c, bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/os_custom.h, features/org.eclipse.swt.tools.feature/feature.xml
A number of places in the GTK4 API there is the possibility of passing in arrays of Strings, i.e. Java String[] -> char ** as input argument to C side.
This change adds better support to the JNI generator for this use case by converting the jobjectArray (String[]) to char ** on the C side.
Part of #2126
Split out of #2538
=> Improve support for Arrays of Strings in JNI Generator

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/graphics/Image.java, bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/internal/NativeImageLoader.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/graphics/ImageDataLoader.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/graphics/ImageLoader.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/image/FileFormat.java, bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/image/SVGFileFormat.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/graphics/Image.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/internal/NativeImageLoader.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/internal/NativeImageLoader.java
Extend ImageLoader to able to load images at a given target height and width in addition to the current behavior of only being able to load images at a target zoom. This is required to load images in svg format at custom height and width.
The extensions added in this change is used in https://github.com/eclipse-platform/eclipse.platform.swt/pull/2526 That PR also contains snippets through which these changes are tested.
This depends on https://github.com/eclipse-platform/eclipse.platform.swt/pull/2514, Only last commit is relevant for this PR
=> Extend ImageLoader to be able to load images at a given height and width

bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/widgets/CoordinateSystemMapperTests.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/MultiZoomCoordinateSystemMapper.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Shell.java
Previously, dialog positioning could be incorrect if the monitor was misidentified when restoring location. By returning the shell's location as a Point.WithMonitor (including monitor reference), we ensure dialogs and secondary shells open on the intended monitor, even in multi-monitor setups. This fixes issues where dialogs could appear on the wrong monitor after moving the parent shell.
- Run the runtime workspace with monitor specific scaling turned on.
- Move the window to secondary monitor on the right (could be of any zoom)
- Resize the window to smaller size
- Open the **"Open Type"** window using `Ctrl + Shift + T`
- Move the Open Type window towards very left of the screen. 
- Close Open Type window
- Maximize the size of main window. 
- Open the **Open Type** dialog again
- You …
=> GetLocation as Point.WithMonitor to ensure correct monitor association

bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/CTabFolderRenderer.java, bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/graphics/GC.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/graphics/GC.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/GC.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_graphics_GC.java
Introduces a new method that draws the full image into a specified destination rectangle without requiring source bounds. Consumers no longer need to call image.getBounds() to determine image dimensions, unlike the existing drawImage method (Image image, int srcX, int srcY, int srcWidth, int srcHeight, int destX, int destY, int destWidth, int destHeight), which required knowing the image size in advance.
=> Add drawImage API that takes only a destination rectangle

tests/org.eclipse.swt.tests.win32/JUnit Tests/org/eclipse/swt/tests/win32/Test_org_eclipse_swt_events_KeyEvent.java, tests/org.eclipse.swt.tests.win32/META-INF/MANIFEST.MF
Since the upgrade of the default GitHub Actions runner for Windows to Windows Server 2025, the key event tests started to fail sporadically. Until a solution is found, this temporarily disables the tests to avoid that it hides actual issues when investigating the build results.
For the used system variable to identify the GHA environment, see https://docs.github.com/en/actions/reference/workflows-and-actions/variables#default-environment-variables
Contributes to https://github.com/eclipse-platform/eclipse.platform.swt/issues/2516
=> Disable Win32 key event test in GitHub Actions runs #2516

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/graphics/Cursor.java, bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/graphics/Cursor.java, bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Cursor.java, tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_graphics_Cursor.java
The constructor Cursor(Device, ImageData source, ImageData mask, int hotspotX, int hotspotY) allows creating a cursor by providing a source image and a 1-bit mask to define transparency. This approach requires developers to manually define mask pixels and works reliably only in fixed DPI environments.
With the introduction of multi-monitor DPI support, this constructor produces inconsistent results.
- Masks do not scale properly when using DPIUtil.autoScaleImageData, leading to visual artifacts.
- Developers need to handle scaling and mask adjustments manually, which is error-prone.
=> Deprecation: Cursor(Device, ImageData, ImageData, int, int)

bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Canvas.java
In https://github.com/eclipse-platform/eclipse.platform.swt/pull/2582 I've mixed the handlers. This fixes it to not call into each other.
=> [GTK4] Do not mix gtk 3 and 4 focus event handlers
