bundles/org.eclipse.swt.tools/Oomph/platformSwt.setup

https://github.com/eclipse-platform/eclipse.platform.swt/issues/4

Migrate platformSwt.setup to use github URIs

---

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Display.java
bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Text.java

[win32] More updates for Text's icons in dark theme

---

tests/org.eclipse.swt.tests/ManualTests/org/eclipse/swt/tests/manual/Issue0021_HdcLeak_ImageCreateGdipImage.java

Fixes #25
Regression from #21
Signed-off-by: Alexandr Miloslavskiy <alexandr.miloslavskiy@syntevo.com>

#25 Fix compilation error in test snippet on Linux

---

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_Button.java

Disabling new test on Linux for now.
Fixes issue
https://github.com/eclipse-platform/eclipse.platform.swt/issues/27

test_traverseCheckButton fails on Linux

---

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Button.java
tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_Button.java

Change-Id: I09f81bc5041bb1aa61fb7b62300a772aa6853abf
Signed-off-by: Rolf Theunissen <rolf.theunissen@gmail.com>

#6 [win32] Keyboard shortcuts for radio buttons don't work anymore (#24)

---

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/TextLayout.java

Change-Id: I74f0fc34159d2ae6442b501eb2e8038c82c03ac2

Bug 579626 - RTL text is not rendered correctly on TextLayout #37

---

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_graphics_TextLayout.java

Change-Id: Ifc4d0c853fca421dd5b455164f38aca876633fb6

One JUnit failure seen on SWT Windows results #51

---

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/internal/BidiUtil.java

prevent slow systemcalls for every character

resolveTextDirection using Character.getDirectionality (fixes #90)

---

.github/workflows/maven.yml
bundles/org.eclipse.swt/buildSWT.xml
bundles/org.eclipse.swt/pom.xml
pom.xml
tests/org.eclipse.swt.tests.win32/JUnit Tests/org/eclipse/swt/widgets/Test_org_eclipse_swt_widgets_Display.java
tests/org.eclipse.swt.tests.win32/META-INF/MANIFEST.MF
tests/org.eclipse.swt.tests.win32/pom.xml

**DO NOT MERGE**
These are just some tests of the new GH action verification

Test GH action compile error on different platforms

---

.github/workflows/junit.yml
.github/workflows/maven.yml
README.md
tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_browser_Browser.java
tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/memoryleak/Test_Memory_Leak.java

Lets see if we can get the tests running...

Enable Tests for GH action

---

.github/workflows/maven.yml

@iloveeclipse lets see if we can reproduce this here...

Add different java versions to the matrix

---

bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/DPIUtil.java

Removing upper limit for scaling
fixes #93

HiDPI and Ubuntu 22.04 #93

---

CODEOWNERS

Fixes #66 . This works fine in my own repository.

Fix codeowners glob

---

bundles/org.eclipse.swt/Eclipse SWT Printing/win32/org/eclipse/swt/printing/PrintDialog.java
bundles/org.eclipse.swt/Eclipse SWT Printing/win32/org/eclipse/swt/printing/Printer.java

No need for if (value!=false), can simply be if (value).

Simplyfies if statements in printing package

---

bundles/org.eclipse.swt/Eclipse SWT Printing/cocoa/org/eclipse/swt/printing/Printer.java

This PR takes care of Cocoa printing package
Change-Id: I74bbaf2597d6fc50e96b7a90d94df16d67f255fa

[Cocoa]Simplyfies if statements in printing package

---

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Table.java
bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Tree.java

Change-Id: I78f7138aaa31398d5fa5019a8398c576babd30c2
Reviewed-on:
https://git.eclipse.org/r/c/platform/eclipse.platform.swt/+/180344
Signed-off-by: Sravan Kumar Lakkimsetti <sravankumarl@in.ibm.com>

Bug 568383 - [Big Sur] Tree text is shortened with Ellipsis

---

bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/StyledText.java
tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_custom_StyledText.java

Reproduces issue
https://github.com/eclipse-platform/eclipse.platform.swt/issues/144

[StyledText] Test scroll then wordwrap

---

tests/org.eclipse.swt.tests/ManualTests/org/eclipse/swt/tests/manual/Issue0146_CopyImageToClipBoard.java

Original example code, slightly modified, is from
https://github.com/eclipse-platform/eclipse.platform.swt/issues/143
See https://github.com/eclipse-platform/eclipse.platform.swt/issues/146

Manual example for issue #146

---

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_browser_Browser.java

See https://github.com/eclipse-platform/eclipse.platform.swt/issues/108

Fail the test if the overall leaks count increases significantly

---

bundles/org.eclipse.swt.tools.base/pom.xml
bundles/org.eclipse.swt.tools.spies/pom.xml
bundles/org.eclipse.swt.tools/pom.xml
bundles/org.eclipse.swt/pom.xml
examples/org.eclipse.swt.examples.browser.demos/pom.xml
examples/org.eclipse.swt.examples.launcher/pom.xml
examples/org.eclipse.swt.examples.ole.win32/pom.xml
examples/org.eclipse.swt.examples.views/pom.xml
examples/org.eclipse.swt.examples/pom.xml
features/org.eclipse.swt.tools.feature/pom.xml
local-build/local-build-parent/pom.xml
local-build/org.eclipse.swt.fragments.localbuild/pom.xml
pom.xml
tests/org.eclipse.swt.tests.cocoa/pom.xml
tests/org.eclipse.swt.tests.gtk/pom.xml
tests/org.eclipse.swt.tests.win32/pom.xml
tests/org.eclipse.swt.tests/pom.xml

Tracked in [eclipse.platform.releng.aggregator#290](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/290) and [eclipse.platform.releng.aggregator#291](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/291)
Need to wait to merge until after 4.24 Release

WIP: POM and product version changes for 4.25 release

---

bundles/org.eclipse.swt/META-INF/MANIFEST.MF
bundles/org.eclipse.swt/pom.xml

Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/313

Version bumps for 4.25 stream.

---

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_custom_StyledText.java
tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_graphics_TextLayout.java

Preliminary changes to get a bit saner tests before looking why they fail on Jenkins.

Improve tests that fail on jenkins

---

bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/CTabFolder.java
bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/CTabFolderRenderer.java
bundles/org.eclipse.swt/META-INF/MANIFEST.MF
bundles/org.eclipse.swt/pom.xml

Adds a thick line under the active tab of each folder; and use the
selection color for the "active with focus".

More visible highlight of active CTab(Folder) #55

---

.github/ISSUE_TEMPLATE/bug_report.md

- Fixed missing check-box in Preview and text indentation.
Change-Id: I34dad3559a3e0a299bae4569aeed06f509bebc06

SWT new Bug template:

---

Jenkinsfile
pom.xml

Tracked in eclipse-platform/eclipse.platform.releng.aggregator#293

Run verification build with Java 17.

---

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/graphics/TextLayout.java

Fixes #201
In TextLayout, the line count is not computed correctly when there is a trailing new
line causing wrong output for getLineOffsets() and getLineCount().
The fix is to handle this case (similar to Text.getLineCount())

Test failure in TextLayout.test_getLineOffsets on Mac

---

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Table.java
tests/org.eclipse.swt.tests.win32/ManualTests/org/eclipse/swt/tests/win32/snippets/SWTIssue223.java

fixes #223 
Change-Id: Ie6ea38db33f395efbba13d2451584fed84bfe395

Table remains visible though setVisible(false) was called

---

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Table.java

- revised patch to fix broken Git-History & Ctrl+3 view in Eclipse
fixes #223 
Change-Id: Ia31a5fd18ff49d2421ade4b4721fcf92c9c31b12

Part2: Table remains visible though setVisible(false) was called

---

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java
tests/org.eclipse.swt.tests.win32/ManualTests/org/eclipse/swt/tests/win32/snippets/SWTIssue185.java

Fixes #185 
Change-Id: Idec2ddb0086a58c8d28c7616a628e2802d06ce56

GC#drawIcon draws *.ico(for some icons) with black background on Windows10

---

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/graphics/TextLayout.java

This reverts commit 51dc75e726e4995ad8cd29150f90c993489b43d7.
Fixes  Hovers are not showing for java in latest i-builds #249

Revert "Test failure in TextLayout.test_getLineOffsets on Mac (#222)"

---

examples/org.eclipse.swt.examples/META-INF/MANIFEST.MF
examples/org.eclipse.swt.examples/pom.xml
examples/org.eclipse.swt.examples/src/org/eclipse/swt/examples/accessibility/CTable.java
examples/org.eclipse.swt.examples/src/org/eclipse/swt/examples/addressbook/AddressBook.java
examples/org.eclipse.swt.examples/src/org/eclipse/swt/examples/controlexample/DialogTab.java
examples/org.eclipse.swt.examples/src/org/eclipse/swt/examples/controlexample/MenuTab.java
examples/org.eclipse.swt.examples/src/org/eclipse/swt/examples/controlexample/ShellTab.java
examples/org.eclipse.swt.examples/src/org/eclipse/swt/examples/controlexample/Tab.java
examples/org.eclipse.swt.examples/src/org/eclipse/swt/examples/texteditor/TextEditor.java
examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet173.java
examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet354.java
examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/SnippetExplorer.java

Examples and snippets are covered.

Replace lambdas with method handles.

---

tests/org.eclipse.swt.tests/META-INF/MANIFEST.MF

Effort to reduce test failures as seen in
https://github.com/eclipse-platform/eclipse.platform.swt/issues/232 .

Make SWT tests fragment.

---

examples/org.eclipse.swt.examples/src/org/eclipse/swt/examples/controlexample/ControlExample.java

Improve Custom/ControlExample(s) to support scrolling to complete contents

---

bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/build.sh

required for https://github.com/eclipse-platform/eclipse.platform.swt/issues/321

Updating dynamic detection of java_home for ppcle

---

.github/workflows/maven.yml

This should make
https://github.com/eclipse-platform/eclipse.platform.swt/issues/251
work.

Replicate Jenkins build in GH action

---

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Tree.java

Reverts code changes from commits:
* 17b40247 - Initial patch that optimizes Tree.setItemCount
* d5270df6 - followup that fixes some regressions in 17b40247
New code comments and snippets are preserved.
The revert is to let Eclipse release safely, a better optimization
attempt will be prepared later.
Signed-off-by: Alexandr Miloslavskiy <alexandr.miloslavskiy@syntevo.com>

Issue #333 - [win32] Revert Tree.setItemCount optimizations

---

bundles/org.eclipse.swt.tools.spies/META-INF/MANIFEST.MF
bundles/org.eclipse.swt.tools.spies/pom.xml

Fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/348

Touch org.eclipse.swt.tools.spies to force signing

---

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Display.java
bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Display.java
bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Display.java
bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Shell.java

SWT Javadoc bash for 4.25

---

bundles/org.eclipse.swt.tools.base/pom.xml
bundles/org.eclipse.swt.tools.spies/pom.xml
bundles/org.eclipse.swt.tools/pom.xml
bundles/org.eclipse.swt/pom.xml
examples/org.eclipse.swt.examples.browser.demos/pom.xml
examples/org.eclipse.swt.examples.launcher/pom.xml
examples/org.eclipse.swt.examples.ole.win32/pom.xml
examples/org.eclipse.swt.examples.views/pom.xml
examples/org.eclipse.swt.examples/pom.xml
features/org.eclipse.swt.tools.feature/pom.xml
local-build/local-build-parent/pom.xml
local-build/org.eclipse.swt.fragments.localbuild/pom.xml
pom.xml
tests/org.eclipse.swt.tests.cocoa/pom.xml
tests/org.eclipse.swt.tests.gtk/pom.xml
tests/org.eclipse.swt.tests.win32/pom.xml
tests/org.eclipse.swt.tests/pom.xml

Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/514

Opening of 4 26 stream for development

---

bundles/org.eclipse.swt/META-INF/MANIFEST.MF
bundles/org.eclipse.swt/pom.xml

Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/540

Version bumps for 4.26 stream

---

bundles/org.eclipse.swt/Eclipse SWT PI/win32/library/build.bat
bundles/org.eclipse.swt/Eclipse SWT PI/win32/library/gdip.h
bundles/org.eclipse.swt/Eclipse SWT PI/win32/library/make_win32.mak

[win32] Native libs: treat warnings as errors

---

bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/os_custom.c
bundles/org.eclipse.swt/Eclipse SWT/common/library/callback.c
bundles/org.eclipse.swt/Eclipse SWT/common/library/swt.c

Java 11 has JNI_VERSION 10 as highest version thus use it through out the code.

Switch JNI_VERSION to 10

---

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Tree.java
bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/TreeItem.java
tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_Tree.java

Fix #396 - Four VirtualLazyTreeViewerTest fail on Windows

---

bundles/org.eclipse.swt/Eclipse SWT PI/win32/library/build.bat

See https://github.com/eclipse-platform/eclipse.platform.swt/issues/417

Try to use Java 11 for native SWT build on Windows

---

bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/gtk3.c
bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/gtk3_stats.c
bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/gtk3_stats.h
bundles/org.eclipse.swt/Eclipse SWT PI/gtk/org/eclipse/swt/internal/gtk3/GTK3.java
bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Button.java

Reverts eclipse-platform/eclipse.platform.swt#408

Revert "[Issue 367] Button Image is wrong size at hi-res scale"

---

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Display.java

Calling OS is heavy overhead compared to jvm internal map.get().

Win Display: use java map instead of OS for control map

---

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Tree.java

Prevent ArrayIndexOutOfBoundsException and cache old order till new order is available after drag and drop.
Drag and drop can be tested with Problems View: A wrong order would show vertical separator lines in the table that do not match the header column.

fix cachedItemOrder #440

---

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Tree.java

The first visible column needs a special treatment.

win: fix forgotten redraw on resized columns #441

---

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_browser_Browser.java

https://github.com/eclipse-platform/eclipse.platform.swt/issues/103
Added Cocoa check for failing test

Test failing on Mac - test_LocationListener_ProgressListener_cancledLoad

---

bundles/org.eclipse.swt.tools.base/pom.xml
bundles/org.eclipse.swt.tools.spies/pom.xml
bundles/org.eclipse.swt.tools/pom.xml
bundles/org.eclipse.swt/pom.xml
examples/org.eclipse.swt.examples.browser.demos/pom.xml
examples/org.eclipse.swt.examples.launcher/pom.xml
examples/org.eclipse.swt.examples.ole.win32/pom.xml
examples/org.eclipse.swt.examples.views/pom.xml
examples/org.eclipse.swt.examples/pom.xml
features/org.eclipse.swt.tools.feature/pom.xml
local-build/local-build-parent/pom.xml
local-build/org.eclipse.swt.fragments.localbuild/pom.xml
pom.xml
tests/org.eclipse.swt.tests.cocoa/pom.xml
tests/org.eclipse.swt.tests.gtk/pom.xml
tests/org.eclipse.swt.tests.win32/pom.xml
tests/org.eclipse.swt.tests/pom.xml

Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/712

POM and product version changes for 4.27 release

---

bundles/org.eclipse.swt/META-INF/MANIFEST.MF
bundles/org.eclipse.swt/pom.xml

Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/725

Version bumps for 4.27 stream

---

bundles/org.eclipse.swt/Eclipse SWT Drag and Drop/gtk/org/eclipse/swt/dnd/ByteArrayTransfer.java
bundles/org.eclipse.swt/Eclipse SWT Drag and Drop/gtk/org/eclipse/swt/dnd/HTMLTransfer.java
bundles/org.eclipse.swt/Eclipse SWT Drag and Drop/gtk/org/eclipse/swt/dnd/ImageTransfer.java
bundles/org.eclipse.swt/Eclipse SWT Drag and Drop/gtk/org/eclipse/swt/dnd/RTFTransfer.java
bundles/org.eclipse.swt/Eclipse SWT Drag and Drop/gtk/org/eclipse/swt/dnd/TextTransfer.java

* instanceof already checks nulls
* String.isEmpty used

Simplify *Transfer check* methods

---

bundles/org.eclipse.swt/Eclipse SWT Drag and Drop/gtk/org/eclipse/swt/dnd/Clipboard.java
bundles/org.eclipse.swt/Eclipse SWT Drag and Drop/gtk/org/eclipse/swt/dnd/ClipboardProxy.java

+ implemented HTML transfer in gtk4 clipboard snippet
Signed-off-by: Jason Wang
Tracked in #476

Bug 476 - SWT clipboard HTML transfer doesn't work

---

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Pattern.java

The bitmap used to create a GDI+ texture brush must not be deleted until after the brush is no longer used.
Fixes issue #486.

Fix issue #486: [win32] Fix use-after-free in Pattern

---

tests/org.eclipse.swt.tests/META-INF/MANIFEST.MF
tests/org.eclipse.swt.tests/pom.xml

See https://github.com/eclipse-platform/eclipse.platform.swt/issues/294

Bump tests bundle version for 4.27

---

Jenkinsfile

Enable publish of code metrics to github

---

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/ToolBar.java

Fix for issue eclipse-platform/eclipse.platform.ui#443

[win32] ToolBar gets resized when mixing ToolItems with text and icon eclipse-platform/eclipse.platform.ui#443

---

bundles/org.eclipse.swt.tools.base/pom.xml
bundles/org.eclipse.swt.tools.spies/pom.xml
bundles/org.eclipse.swt.tools/pom.xml
bundles/org.eclipse.swt/pom.xml
examples/org.eclipse.swt.examples.browser.demos/pom.xml
examples/org.eclipse.swt.examples.launcher/pom.xml
examples/org.eclipse.swt.examples.ole.win32/pom.xml
examples/org.eclipse.swt.examples.views/pom.xml
examples/org.eclipse.swt.examples/pom.xml
features/org.eclipse.swt.tools.feature/pom.xml
local-build/local-build-parent/pom.xml
local-build/org.eclipse.swt.fragments.localbuild/pom.xml
pom.xml
tests/org.eclipse.swt.tests.cocoa/pom.xml
tests/org.eclipse.swt.tests.gtk/pom.xml
tests/org.eclipse.swt.tests.win32/pom.xml
tests/org.eclipse.swt.tests/pom.xml

Fixes https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/916

POM and product version changes for 4.28 release

---

bundles/org.eclipse.swt/Eclipse SWT Drag and Drop/gtk/org/eclipse/swt/dnd/DragSource.java
bundles/org.eclipse.swt/Eclipse SWT Drag and Drop/gtk/org/eclipse/swt/dnd/DropTarget.java
bundles/org.eclipse.swt/Eclipse SWT PI/gtk/org/eclipse/swt/internal/gtk/OS.java
bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Control.java
tests/org.eclipse.swt.tests.gtk/META-INF/MANIFEST.MF
tests/org.eclipse.swt.tests.gtk/ManualNativeCTests/BugSnippets/Issue0400_WaylandDndEvents.cpp
tests/org.eclipse.swt.tests.gtk/ManualNativeCTests/BugSnippets/Issue0400_WaylandDndEvents.sh
tests/org.eclipse.swt.tests.gtk/pom.xml
tests/org.eclipse.swt.tests/ManualTests/org/eclipse/swt/tests/manual/Issue0400_WaylandDifferentDndMouseEvents.java

Fixes #400
Please refer to individual commit messages.

Fix for #400 [GTK][Wayland] Non-standard mouse events during Drag&drop

---

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Shell.java
bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/ToolTip.java
tests/org.eclipse.swt.tests/ManualTests/org/eclipse/swt/tests/manual/Issue0544_WinTooltipJvmCrash.java

Fix #544 - [win32] JVM crash in setToolTipText() since 4.19

---

bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/StyledTextWriterBase.java

Fixing issue https://github.com/eclipse-platform/eclipse.platform.swt/issues/593

No extra paragraph in the HTML clipboard

---

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Control.java
tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_Text.java

Fixes #472
Please refer to commit message for details.

[cocoa] NPE with multi-line Text control in a Group control

---

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/graphics/GC.java

- See https://github.com/eclipse-platform/eclipse.platform.swt/issues/631
- This caching was only being used in one case when drawing text of one character on a transparent background
- This means that if the GC is used to draw more than one text string with different foreground colors the cached color is used instead of the new one
- This reverts commit 2a2325b0699615424fc557f8d6db2190dd304048.

Revert single character text caching on Mac GC

---

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Button.java
bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Display.java
tests/org.eclipse.swt.tests.win32/ManualTests/org/eclipse/swt/tests/win32/snippets/Issue0473_WinDarkArrowButton.java

Issue #473 - [win32][DarkTheme] Button with SWT.ARROW style has light background

---

tests/org.eclipse.swt.tests.gtk/ManualTests/org/eclipse/swt/tests/gtk/snippets/Issue644_CompleteTableEditor.java
tests/org.eclipse.swt.tests.gtk/ManualTests/org/eclipse/swt/tests/gtk/snippets/Issue644_TableEditorWithCanvas.java

Create a table with non editable and editable columns with basic and custom widget as TableEditor.
See https://github.com/eclipse-platform/eclipse.platform.swt/issues/644

SWT TableEditor: Unit test snippet with different table editor and simple canvas editor

---

bundles/org.eclipse.swt/Eclipse SWT Accessibility/cocoa/org/eclipse/swt/accessibility/SWTAccessibleDelegate.java

According to the user this change fixes the problem.
Fixes #650

#650 [macOS, aarch] NPE in SWTAccessibleDelegate.accessibilityAttributeNames

---

bundles/org.eclipse.swt.tools.base/pom.xml
bundles/org.eclipse.swt.tools.spies/pom.xml
bundles/org.eclipse.swt.tools/pom.xml
bundles/org.eclipse.swt/pom.xml
examples/org.eclipse.swt.examples.browser.demos/pom.xml
examples/org.eclipse.swt.examples.launcher/pom.xml
examples/org.eclipse.swt.examples.ole.win32/pom.xml
examples/org.eclipse.swt.examples.views/pom.xml
examples/org.eclipse.swt.examples/pom.xml
features/org.eclipse.swt.tools.feature/pom.xml
local-build/local-build-parent/pom.xml
local-build/org.eclipse.swt.fragments.localbuild/pom.xml
pom.xml
tests/org.eclipse.swt.tests.cocoa/pom.xml
tests/org.eclipse.swt.tests.gtk/pom.xml
tests/org.eclipse.swt.tests.win32/pom.xml
tests/org.eclipse.swt.tests/pom.xml

Tracked https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1100

POM and product version changes for 4.29 release

---

bundles/org.eclipse.swt/META-INF/MANIFEST.MF
bundles/org.eclipse.swt/pom.xml

Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1125

Version bump for 4.29 stream

---

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/ImageLoader.java
examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet319.java

Doesn't try to fix anything. Just code and warnings reduced.

ImageLoader: Use try-with-resource

---

tests/org.eclipse.swt.tests.win32/JUnit Tests/org/eclipse/swt/tests/win32/Test_org_eclipse_swt_dnd_DND.java

The Windows test for DND image transfers expects transparency properties from the dropped image that cannot be guaranteed by the ImageData implementation for alpha channel values.
Since the current behavior of the ImageData implementation is valid, this change adapts the according test case by improving the assertion for the DND image transfer result. In addition, it adds multiple test cases to capture different types of ImageData to be transferred via drag and drop.
Contributes to #116.

Improve Test_org_eclipse_swt_dnd_DND.testImageTransfer #116

---

bundles/org.eclipse.swt.tools.spies/META-INF/MANIFEST.MF
bundles/org.eclipse.swt.tools.spies/forceQualifierUpdate.txt
bundles/org.eclipse.swt.tools.spies/pom.xml
bundles/org.eclipse.swt.tools/forceQualifierUpdate.txt
examples/org.eclipse.swt.examples.browser.demos/META-INF/MANIFEST.MF
examples/org.eclipse.swt.examples.browser.demos/forceQualifierUpdate.txt
examples/org.eclipse.swt.examples.browser.demos/pom.xml
examples/org.eclipse.swt.examples.launcher/META-INF/MANIFEST.MF
examples/org.eclipse.swt.examples.launcher/forceQualifierUpdate.txt
examples/org.eclipse.swt.examples.launcher/pom.xml
examples/org.eclipse.swt.examples.ole.win32/META-INF/MANIFEST.MF
examples/org.eclipse.swt.examples.ole.win32/forceQualifierUpdate.txt
examples/org.eclipse.swt.examples.ole.win32/pom.xml
examples/org.eclipse.swt.examples.views/META-INF/MANIFEST.MF
examples/org.eclipse.swt.examples.views/forceQualifierUpdate.txt
examples/org.eclipse.swt.examples.views/pom.xml
examples/org.eclipse.swt.examples/META-INF/MANIFEST.MF
examples/org.eclipse.swt.examples/forceQualifierUpdate.txt
examples/org.eclipse.swt.examples/pom.xml
tests/org.eclipse.swt.tests/forceQualifierUpdate.txt

Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1184

Bug 527899 [9] Implement JEP 280: Indify String Concatenation

---

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Combo.java
tests/org.eclipse.swt.tests/ManualTests/org/eclipse/swt/tests/manual/Issue0254_NpeInComboMouseDownTest.java

better cache the used display before it gets unset

#254 - [macOS] Possible NPE in Combo.mouseDown

---

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/SwtTestUtil.java

Was needed for #450, and feels useful overall.

SwtTestUtil: new method to wait for event

---

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/SwtTestUtil.java
tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_custom_CCombo.java
tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_custom_StyledText.java
tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_Button.java
tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_Composite.java
tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_Control.java
tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_Shell.java
tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_Widget.java

[cocoa] In tests, Shell sometimes doesn't activate in a timely manner

---

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_Shell.java

Hopefully fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/727

Issue #727: [cocoa] Tests: try to fix test failures

---

bundles/org.eclipse.swt/Eclipse SWT PI/win32/library/build.bat

error log clearer

---

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/SwtTestUtil.java

fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/724

Issue #724: [cocoa] Shell.open() does not always cause Shell to activate

---

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/SwtTestUtil.java

Previous patch didn't help to defeat test failures on GitHub. Add even more debugging code.
For debugging of https://github.com/eclipse-platform/eclipse.platform.swt/issues/724

Issue #724: [cocoa] In tests, Shell sometimes doesn't activate

---

bundles/org.eclipse.swt/Eclipse SWT OLE Win32/win32/org/eclipse/swt/ole/win32/OleFrame.java

https://github.com/eclipse-platform/eclipse.platform.swt/issues/758

OleFrame: fix NPE after dispose #758

---

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_browser_Browser.java

See https://github.com/eclipse-platform/eclipse.platform.swt/issues/722

Disable unstable test_setUrl_local() on Mac

---

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/GC.java

- See https://github.com/eclipse-platform/eclipse.platform.swt/issues/687

Adjust line dashes on hi-dpi device

---

bundles/org.eclipse.swt.tools/Oomph/platformSwt.setup

https://github.com/eclipse-platform/eclipse.platform.swt/issues/774

Fix setup to copy .classpath_cocoa_aarch64 or .classpath_cocoa_x86_64

---

bundles/org.eclipse.swt/.settings/.api_filters
examples/org.eclipse.swt.examples.watchdog/src/org/eclipse/swt/examples/watchdog/TimedEventWatchdog.java

Get a slightly cleaner workspace.

Various warnings

---

bundles/org.eclipse.swt.tools.spies/META-INF/MANIFEST.MF
bundles/org.eclipse.swt.tools.spies/pom.xml
bundles/org.eclipse.swt.tools.spies/src/org/eclipse/swt/tools/views/SleakView.java

Part of https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1056

Migrate from javax.annotation to jakarta.annotation

---

features/org.eclipse.swt.tools.feature/feature.xml

Apply the result of https://github.com/eclipse-pde/eclipse.pde/issues/730

Remove unnecessary attributes from feature.xml files

---

bundles/org.eclipse.swt.tools/Oomph/platformSwt.setup

https://github.com/eclipse-jdt/eclipse.jdt/issues/79

Encourage rebase on forks by configuring the clone default for that

---

bundles/org.eclipse.swt/Eclipse SWT/common/library/make_common.mak

Work towards fixing
https://github.com/eclipse-platform/eclipse.platform.swt/issues/868

Make revision for natives to be 4 too

---

CODEOWNERS

I am removing myself as I no longer have the time to look after the gtk port in general.

Akurtakov no longer codeowner for gtk port

---

bundles/org.eclipse.swt/pom.xml
examples/org.eclipse.swt.examples.ole.win32/pom.xml
local-build/local-build-parent/pom.xml
local-build/org.eclipse.swt.fragments.localbuild/pom.xml
pom.xml
tests/org.eclipse.swt.tests/pom.xml

Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1579

POM and product version changes for 4.31 release

---

bundles/org.eclipse.swt/META-INF/MANIFEST.MF
bundles/org.eclipse.swt/pom.xml
tests/org.eclipse.swt.tests/META-INF/MANIFEST.MF
tests/org.eclipse.swt.tests/pom.xml

This fixes "Only qualifier changed" error in all PRs.

Version bump for 4.31 stream

---

bundles/org.eclipse.swt/.settings/org.eclipse.core.resources.prefs
examples/org.eclipse.swt.examples.ole.win32/.settings/org.eclipse.core.resources.prefs
tests/org.eclipse.swt.tests.cocoa/.settings/org.eclipse.core.resources.prefs
tests/org.eclipse.swt.tests.cocoa/META-INF/MANIFEST.MF
tests/org.eclipse.swt.tests.win32/.settings/org.eclipse.core.resources.prefs
tests/org.eclipse.swt.tests.win32/META-INF/MANIFEST.MF

These should be the last projects in this repository without an explicit encoding set.

Set encoding for projects missing explicit encoding to UTF-8

---

bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/SWT.java

This is related to issue #913, but #913 should be kept open.

SWT: update documentation for Dispose event

---

bundles/org.eclipse.swt.tools.spies/META-INF/MANIFEST.MF
bundles/org.eclipse.swt.tools.spies/forceQualifierUpdate.txt
bundles/org.eclipse.swt.tools/META-INF/MANIFEST.MF
bundles/org.eclipse.swt.tools/forceQualifierUpdate.txt
examples/org.eclipse.swt.examples.browser.demos/forceQualifierUpdate.txt
examples/org.eclipse.swt.examples.views/forceQualifierUpdate.txt
examples/org.eclipse.swt.examples/forceQualifierUpdate.txt
features/org.eclipse.swt.tools.feature/feature.xml
tests/org.eclipse.swt.tests/forceQualifierUpdate.txt

See https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1394 
See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1659

Touch bundles affected by the changed ecj version

---

examples/org.eclipse.swt.examples.launcher/forceQualifierUpdate.txt
examples/org.eclipse.swt.examples.ole.win32/forceQualifierUpdate.txt

See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1661 
See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1659

Touch bundles affected by the changed compilation settings

---

bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/Callback.java
bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/Compatibility.java
bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/internal/BidiUtil.java

Required to enable https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1533.

Fix erroneous <p> tags in JavaDoc of BidiUtil, Callback and Compatibility

---

bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/DPIUtil.java
bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/graphics/Image.java
bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java

In the current implementation, images with some other scaling than 100% are only loaded when an image is available that exactly fits to the desired zoom level. In all other cases, the 100% image is used as a fallback.
With this change, the directly fitting or next larger available image of 150% or 200% is used. Only if none of them exists, the 100% image is used as a fallback. This improves the quality of images when a display scaling of more than 100% is used and no image is provided for exactly that scaling. To simplify the changes, DPIUtil methods returning multiple values were changed to not use parameters to pass returns values and some unnecessary case distinctions have been cleaned up.
The change is applied to the Windows and Linux/GTK implementations. Mac only requires handling …

Use high resolution images with proper scaling whenever available

---

examples/org.eclipse.swt.examples/forceQualifierUpdate.txt

See https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1781

Touch bundles affected by compiler implementation change

---

bundles/org.eclipse.swt/Eclipse SWT Program/cocoa/org/eclipse/swt/program/Program.java
bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/graphics/TextLayout.java
bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/graphics/TextLayout.java

Fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/1050
@niraj-modi 
Can you please review the above changes.

SWT Javadoc basher changes for 4.31

---

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/graphics/GC.java
bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/graphics/GC.java
bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/GC.java
tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_graphics_GC.java

- This reverts commit 657fffb389fdb781db1d18331a31cd104858c4e5.
- This created a regression on Mac
- See https://github.com/eclipse-platform/eclipse.platform.swt/issues/1067

Revert "Correct GC offset calculation #788"

---

.github/workflows/updateRelease.yml

Work towards
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1844

Enable automatic version bumps on milestone creation

---

bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/CTabFolder.java

Reverts eclipse-platform/eclipse.platform.swt#1044

Revert "Set the selection to 1st CTabItem when it is created for the first time"

---

binaries/pom.xml
bundles/org.eclipse.swt/forceQualifierUpdate.txt

Fix https://github.com/eclipse-platform/eclipse.platform.swt/issues/1093

Add all source folders for generation of the api description

---

bundles/org.eclipse.swt.tools.spies/META-INF/MANIFEST.MF
bundles/org.eclipse.swt.tools/META-INF/MANIFEST.MF
examples/org.eclipse.swt.examples.browser.demos/META-INF/MANIFEST.MF
examples/org.eclipse.swt.examples.views/META-INF/MANIFEST.MF
examples/org.eclipse.swt.examples/forceQualifierUpdate.txt
tests/org.eclipse.swt.tests/forceQualifierUpdate.txt

See: eclipse-platform/eclipse.platform.releng.aggregator#1923

Updated bundles with comparator errors

---

binaries/org.eclipse.swt.cocoa.macosx.aarch64/fragment.properties
binaries/org.eclipse.swt.cocoa.macosx.x86_64/fragment.properties
binaries/org.eclipse.swt.gtk.linux.aarch64/fragment.properties
binaries/org.eclipse.swt.gtk.linux.loongarch64/fragment.properties
binaries/org.eclipse.swt.gtk.linux.ppc64le/fragment.properties
binaries/org.eclipse.swt.gtk.linux.x86_64/fragment.properties
binaries/org.eclipse.swt.win32.win32.x86_64/fragment.properties

Extracted from https://github.com/eclipse-platform/eclipse.platform.swt/pull/1034.

Unify architecture in fragment's Bundle-Name

---

bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/widgets/Monitor.java
bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Display.java

https://github.com/eclipse-platform/.github/issues/193

[win] GetDpiForMonitor: prevent devision by zero #193

---

bundles/org.eclipse.swt/Eclipse SWT Accessibility/win32/org/eclipse/swt/accessibility/Accessible.java
bundles/org.eclipse.swt/Eclipse SWT Browser/common/org/eclipse/swt/browser/WebBrowser.java
bundles/org.eclipse.swt/Eclipse SWT Browser/win32/org/eclipse/swt/browser/Edge.java
bundles/org.eclipse.swt/Eclipse SWT OLE Win32/win32/org/eclipse/swt/ole/win32/OLE.java
bundles/org.eclipse.swt/Eclipse SWT PI/common/org/eclipse/swt/internal/Library.java
bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/DPIUtil.java
bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/ExceptionStash.java
bundles/org.eclipse.swt/Eclipse SWT/common/org/eclipse/swt/internal/image/GIFFileFormat.java
bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/DateTime.java
bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/ToolBar.java
bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Tree.java

- Remove unused imports
- Remove unnecessary casts
- Remove redundant semicolons
- Remove unnecessary '$NON-NLS$' tags

Apply clean-up: Remove unnecessary and unused code

---

.github/workflows/maven.yml

See https://www.eclipse.org/lists/cross-project-issues-dev/msg19891.html for context

Remove macos-latest-large label

---

bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Display.java

Depending on the window currently focused the
coordinates returned may be wrong (sometimes even
negative). This happens mainly with popup windows.
Fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/177

Fix getWindowPointerPosition on Wayland #177

---

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Scrollable.java
bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Scrollable.java

Fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/1245
@niraj-modi
Can you please review the above changes.
Tried it on below build. Please dont merge this change since we are still in RC1
I'll be rerunning the same once more post RC1 release then only we'll merge it.

SWT Javadoc bash changes for 4.32

---

binaries/pom.xml
bundles/org.eclipse.swt/pom.xml
examples/org.eclipse.swt.examples.ole.win32/pom.xml
local-build/local-build-parent/pom.xml
local-build/org.eclipse.swt.fragments.localbuild/pom.xml
pom.xml
tests/org.eclipse.swt.tests/pom.xml

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2074

POM and product version changes for 4.33 release

---

bundles/org.eclipse.swt/Eclipse SWT PI/win32/library/os.c
bundles/org.eclipse.swt/Eclipse SWT PI/win32/library/os_stats.h
bundles/org.eclipse.swt/Eclipse SWT PI/win32/org/eclipse/swt/internal/win32/OS.java

* https://github.com/eclipse-platform/eclipse.platform.swt/issues/127
* https://github.com/eclipse-platform/eclipse.platform.swt/pull/1214
This PR provides the access to windows API which are later needed for the following PRs for the support of Multi Zoom Level.

added native bindings for win32

---

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/ToolItem.java

~Fixes:~ Contributes to #1233 (it only fixes the issue for Mac)

Fix Color of Toolbar Item on Dark Background

---

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/TextLayout.java

This PR is a follow up to the PR #1244 which improves the readability of the class TextLayout for win32. The field lineWidth is now renamed to lineWidthInPixels since the field represented the information in pixels.

Renamed the field to improve readability

---

bundles/org.eclipse.swt/Eclipse SWT Tests/win32/org/eclipse/swt/internal/DPITestUtil.java

Adds final modifier and private constructor to the utility class.

Make DPITestUtil a proper utility class

---

examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet285.java

It closes with the "esc" key, as many other snippets do

Allow the Snippet285 to be moved with the mouse

---

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Button.java

In the Windows -> Preference -> General dialog, when moved from higher zoom level (200) to lower zoom level (100), we found a visible gap between the checkboxes whether it was created horizontally or vertically. 
Solution: 
Refresh the checkWidth and checkHeight Size whenever there is a dpi change or when button is created. Factor is calculated by identifying the zoom change e.g. 100 -> 200 should be scaled down to half (currentZoom / primaryZoom)
- Run the RunTimeEnvironment
- Add these lines in your vm arguments  
`-Dswt.autoScale=quarter`
`-Dswt.autoScale.updateOnRuntime=true`
- Go to Windows ->  Preference -> General dialog
- Move the **Preferences Dialog** from 200 to 100 zoom level
- See if the spacing is correct between two check boxes
Spacing should be fixed w.r.t. zoom level …

Adding refreshCheckSize() to refresh the check size **Windows 11 Only**

---

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/ToolBar.java

This commit prevents an ArrayIndexOutOfBounds exception, when the commandIds of toolbar buttons are not in line with button count, e.g. there is an id higher than the button count.
Contributes to #62 and #131

[win32] Prevent exception on toolbar DPI change

---

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/internal/ImageList.java

When an ImageList is scaled (e g. when a ToolBar is scaled due to a zoom changed) null images in the images array (e.g. when a ToolItem is disposed) were not addressed properly. This led to scenarios like this:
Starting on 200%
Without PR on 100% -> The behaviour depends on the index where the images are missing and when the ImageList in scales. In some scenarios, wrong images will be shown, in this scenario, images are missing
With PR on 100%
If a null image is found when scaling an ImageList a valid placeholder image is added to the ImageList.
```
public class ToolbarTest {
public static void main (String [] args) {
Display display = new Display ();
Shell shell …
```

[win32] Fix scaling of imagelist with gaps

---

binaries/org.eclipse.swt.cocoa.macosx.aarch64/META-INF/MANIFEST.MF
binaries/org.eclipse.swt.cocoa.macosx.x86_64/META-INF/MANIFEST.MF
binaries/org.eclipse.swt.gtk.linux.aarch64/META-INF/MANIFEST.MF
binaries/org.eclipse.swt.gtk.linux.loongarch64/META-INF/MANIFEST.MF
binaries/org.eclipse.swt.gtk.linux.ppc64le/META-INF/MANIFEST.MF
binaries/org.eclipse.swt.gtk.linux.x86_64/META-INF/MANIFEST.MF
binaries/org.eclipse.swt.win32.win32.aarch64/META-INF/MANIFEST.MF
binaries/org.eclipse.swt.win32.win32.x86_64/META-INF/MANIFEST.MF
bundles/org.eclipse.swt/META-INF/MANIFEST.MF
bundles/org.eclipse.swt/pom.xml

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2299

Version bumps for 4.34 stream

---

bundles/org.eclipse.swt/Eclipse SWT Browser/win32/org/eclipse/swt/browser/Edge.java

Follow-up on #1187.
Fixes #1139.
Fixes #1417.

Edge: Fix focus handling to emit SWT.FocusIn events

---

bundles/org.eclipse.swt/Eclipse SWT Browser/win32/org/eclipse/swt/browser/Edge.java
bundles/org.eclipse.swt/Eclipse SWT PI/win32/org/eclipse/swt/internal/ole/win32/COM.java
bundles/org.eclipse.swt/Eclipse SWT PI/win32/org/eclipse/swt/internal/ole/win32/ICoreWebView2ContextMenuRequestedEventArgs.java
bundles/org.eclipse.swt/Eclipse SWT PI/win32/org/eclipse/swt/internal/ole/win32/ICoreWebView2_11.java

Support custom context menus and suppressing of context menus by implementing ICoreWebView2_11#add_ContextMenuRequested().

Edge: Support context menu handling via ICoreWebView2_11

---

bundles/org.eclipse.swt/Eclipse SWT Browser/win32/org/eclipse/swt/browser/Edge.java
tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_browser_Browser.java

Follow-up on #1395.
See https://github.com/eclipse-platform/eclipse.platform.swt/pull/1395#issuecomment-2343645550

Edge: Follow-up to local resource handling in setText()

---

features/org.eclipse.swt.tools.feature/feature.xml

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2335

Bump version o org.eclipse.swt.tools.feature

---

tests/org.eclipse.swt.tests/META-INF/MANIFEST.MF

Needed for Screenshots and TracingSuite classes.

 Add dependency to o.e.test to o.e.swt.tests

---

bundles/org.eclipse.swt/Eclipse SWT Browser/win32/org/eclipse/swt/browser/Edge.java

Edge: Fix ICoreWebView2_11 availability check

---

bundles/org.eclipse.swt/Eclipse SWT Browser/win32/org/eclipse/swt/browser/Edge.java
bundles/org.eclipse.swt/Eclipse SWT PI/win32/org/eclipse/swt/internal/ole/win32/COM.java
bundles/org.eclipse.swt/Eclipse SWT PI/win32/org/eclipse/swt/internal/ole/win32/ICoreWebView2_12.java

Edge: Disable internal status bar on the bottom left when hovering link and send out StatusTextEvents instead (like other SWT browser impls)

---

README.md
bundles/org.eclipse.swt.tools/Oomph/PlatformSWTConfiguration.setup
bundles/org.eclipse.swt.tools/Oomph/platformSwt.setup

Additionally add a styled and drag&drop-able Oomph Configuration button.
Part of https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2430

[Oomph-Setup] Add eclipse.swt configuration setup

---

examples/org.eclipse.swt.examples/META-INF/MANIFEST.MF

Fixes broken build after
https://github.com/eclipse-platform/eclipse.platform.swt/pull/1637

Version bump for new stream

---

.github/workflows/maven.yml
Jenkinsfile

Prereq for
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2654

Run verification builds on Java 21

---

.github/workflows/maven.yml
bundles/org.eclipse.swt/Eclipse SWT PI/gtk/library/build.sh

To unblock
- https://github.com/eclipse-platform/eclipse.platform.swt/issues/1653

Disable deprecation warning in GTK at github validataion

---

bundles/org.eclipse.swt/pom.xml
examples/org.eclipse.swt.examples.ole.win32/pom.xml
local-build/org.eclipse.swt.fragments.localbuild/pom.xml
tests/org.eclipse.swt.tests/pom.xml

- Also fix test bundles and any eclipse-plugin packaging simply for consistency.

Fix maven group id to match the actual deployment

---

bundles/org.eclipse.swt/Eclipse SWT Browser/win32/org/eclipse/swt/browser/Edge.java

WebView initialization may fail in some cases, for which the Microsoft documentation proposes to retry initialization. The Edge implementation already covers that case, but accidentally cancels the initialization of the Edge instance even though a retry of initializing the contained WebView is triggered.
This change properly separates actual initialization abortions and retries and corrects the retry functionality.

[Win32] Correct WebView initialization retry logic in Edge

---

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/internal/SWTFontProvider.java

The SWTFontProvider is Win32-internal for accessing font registries that manage the fonts for a device at different zoom levels. Currently, this class does not consider it's accesses' thread-safety.
This change makes the SWTFontProvider thread-safe under current usage contexts:
- Make the internal map thread-safe as it may be modified from different threads (used for the different devices/displays) concurrently. Using a ConcurrentHashMap ensures that read access stays fast. Write access only happens once per device creation.
- Document non-thread-safety of the provider's operations and the necessity to always call it from the same thread for the same device. All current callers fulfill this requirement, thus no race conditions may occur.

[Win32] Ensure and document thread-safety of SWTFontProvider

---

bundles/org.eclipse.swt/pom.xml

Update forceContextQualifier value for PR https://github.com/eclipse-platform/eclipse.platform.swt/pull/1727

Update forceContextQualifier value

---

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/graphics/Image.java
bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/graphics/Image.java

SWT Javadoc bash for 4.35.
Fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/1841

SWT Javadoc bash for 4.35

---

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/internal/ScalingSWTFontRegistry.java

This PR refactors ScalingSWTFontRegistry to simplify creation and caching of scaled variants of custom and system fonts. This is possible because the conversion of SWT font height in points to the OS font height in pixels no longer relies on the primary monitor zoom, but can directly calculated based on the target zoom a font will be used on now.

[win32] Refactor ScalingSWTFontRegistry

---

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Image.java

And declare the field `private`

Remove redundant initial assignment on field

---

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_widgets_Text.java

Use assertThrows and remove dummy assertion messages as they give no valuable information.

Modernize Text JUnit tests

---

bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/StyledText.java

using Set to collect all the carets needed to be updated and then calling the callback method to execute the dpi change handler

Process DPI change only once per caret

---

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_browser_Browser.java

Edge: Tests: Add test-case for evaluate opening new window

---

bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Display.java

Fixes https://github.com/eclipse-platform/eclipse.platform.swt/issues/1838

Release GtkPrinterOptionWidget

---

binaries/pom.xml

Follow-up on:
- https://github.com/eclipse-platform/eclipse.platform.swt/pull/2079

Refine custom @field and @method javadoc tag heads

---

binaries/pom.xml

Last part of
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2189
to address https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/2189#issuecomment-2831946999.

[Build] Pack swt-download zip after it was signed

---

bundles/org.eclipse.swt/Eclipse SWT Browser/win32/org/eclipse/swt/browser/Edge.java
tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_browser_Browser.java

Edge: Ensure #getText() works even when javascript is disabled

---

bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/List.java
bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Table.java
bundles/org.eclipse.swt/Eclipse SWT/cocoa/org/eclipse/swt/widgets/Tree.java
bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/List.java
bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Table.java
bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/widgets/Tree.java

SWT Javadoc bash for 4.36
Fixes #2160

SWT Javadoc bash for 4.36

---

bundles/org.eclipse.swt/Eclipse SWT PI/gtk/org/eclipse/swt/internal/gtk/swt_theming_fixes_gtk_4_0_0.css
bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/graphics/Device.java

Add css file for gtk4 and start accomodating content in it.

[GTK] Reduce button.toggle padding on GTK 4

---

bundles/org.eclipse.swt/Eclipse SWT Custom Widgets/common/org/eclipse/swt/custom/StyledText.java

Fixes NPE in StyledText on DPI Resizing

---

tests/org.eclipse.swt.tests.gtk/ManualTests/org/eclipse/swt/tests/gtk/snippets/Bug138265_SystemMemoryUsage.java
tests/org.eclipse.swt.tests.gtk/ManualTests/org/eclipse/swt/tests/gtk/snippets/Bug558222_BlackIcon.java
tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_custom_StyledText.java

There is no need to go through RGB, cache and etc. complications.

Simplifying dealing with Colors in tests

---

bundles/org.eclipse.swt/Eclipse SWT/win32/org/eclipse/swt/graphics/Cursor.java

This extracts the hotspot handling of cursors to a common superclass for all cursor handle providers that use hotspot coordinates.
Follow-up cleanup to:
- https://github.com/eclipse-platform/eclipse.platform.swt/pull/2390

[Win32] Extract Cursor hotspot handling into common superclass

---

bundles/org.eclipse.swt.tools/JavadocBasher/org/eclipse/swt/tools/internal/JavadocBasher.java

* Use Java NIO
* Less casting
* Use new collections api
* Stop caring about CVS dirs
* Use foreach

Simplify JavadocBasher

---

tests/org.eclipse.swt.tests/JUnit Tests/org/eclipse/swt/tests/junit/Test_org_eclipse_swt_custom_StyledText.java

add test for https://github.com/eclipse-platform/eclipse.platform.swt/pull/2513

add test verticalIndent_resetsCacheForAllLinesAssumingLowestLineHeight

---

bundles/org.eclipse.swt/Eclipse SWT/gtk/org/eclipse/swt/widgets/Control.java

That case was not handled at all. Fixes
https://github.com/eclipse-platform/eclipse.platform.swt/issues/2534

[GTK4] Support MenuDetect
